Repository diem/diem, pull requests merged in 2020-12, with the labels that each got.

#6763 [move source language] Update compiler API
  language/benchmarks/src/move_vm.rs
  language/libra-tools/transaction-replay/src/lib.rs
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/bin/move-build.rs
  language/move-lang/src/bin/move-check.rs
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/parser/ast.rs
  language/move-lang/tests/move_check_testsuite.rs
  language/move-lang/tests/stdlib_sanity_check.rs
  language/move-prover/spec-lang/src/lib.rs
  language/move-vm/integration-tests/src/compiler.rs
  language/stdlib/src/lib.rs
  language/tools/move-cli/src/main.rs
  language/tools/move-cli/src/package.rs
Labels: cla-signed, language

#6776 add new site redirects
  developers.libra.org/website/siteConfig.js
  developers.libra.org/website/static/js/new-site-redirects.js
Labels: cla-signed

#6767 [state-sync] version counters updates
  state-synchronizer/src/coordinator.rs
  state-synchronizer/src/counters.rs
  state-synchronizer/src/request_manager.rs
Labels: cla-signed

#6759 [codebuild] use dockerhub login
  docker/cluster-test/buildspec.yaml
  docker/init/buildspec.yaml
  docker/mint/buildspec.yaml
  docker/safety-rules/buildspec.yaml
  docker/tools/buildspec.yaml
  docker/validator/buildspec.yaml
Labels: cla-signed

#6734 Cherry pick [faucet] fix cors validation to allow cross domain call in browser
  client/faucet/src/main.rs
Labels: cla-signed

#6710 Cherry-pick PR #6656 [config] rocksdb options to release 1.0
  Cargo.lock
  config/management/genesis/src/verify.rs
  config/management/genesis/src/waypoint.rs
  config/src/config/storage_config.rs
  consensus/src/consensusdb/mod.rs
  execution/db-bootstrapper/Cargo.toml
  execution/db-bootstrapper/src/bin/db-bootstrapper.rs
  execution/executor-benchmark/src/lib.rs
  language/libra-tools/libra-validator-interface/Cargo.toml
  language/libra-tools/libra-validator-interface/src/storage_interface.rs
  libra-node/src/lib.rs
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs
  storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
  storage/backup/backup-cli/src/backup_types/tests.rs
  storage/backup/backup-cli/src/backup_types/transaction/tests.rs
  storage/backup/backup-cli/src/utils/mod.rs
  storage/inspector/Cargo.toml
  storage/inspector/src/main.rs
  storage/libradb/Cargo.toml
  storage/libradb/src/lib.rs
  storage/schemadb/Cargo.toml
  storage/schemadb/src/lib.rs
  storage/schemadb/tests/db.rs
  storage/schemadb/tests/iterator.rs
Labels: cla-signed

#6785 [backup] allow passing in rocksdb options on command line
  config/src/config/storage_config.rs
  storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs
  storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
  storage/backup/backup-cli/src/backup_types/tests.rs
  storage/backup/backup-cli/src/backup_types/transaction/tests.rs
  storage/backup/backup-cli/src/utils/mod.rs
Labels: cla-signed

#6838 [docker] update base docker images.
  docker/ci/alpine/Dockerfile
  docker/ci/arch/Dockerfile
  docker/ci/circleci/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/init/Dockerfile
  docker/mint/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#6856 Revert "logger: change default remote log level to info"
  common/logger/src/diem_logger.rs
Labels: cla-signed

#6889 [Key Manager] Make the key manager smoke test less aggressive.
  testsuite/smoke-test/src/key_manager.rs
Labels: cla-signed

#6893 [backup] backup coordinator metrics
  storage/backup/backup-cli/src/bin/db-backup.rs
  storage/backup/backup-cli/src/coordinators/backup.rs
  storage/backup/backup-cli/src/metrics/backup.rs
  storage/backup/backup-cli/src/metrics/mod.rs
Labels: bors-high-priority, cla-signed, storage

#6895 [Logger] Add backtraces to error logs.
  Cargo.lock
  common/logger/Cargo.toml
  common/logger/src/diem_logger.rs
  common/logger/src/metadata.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#6916 [ci] fix typo in post-land test
  .github/workflows/post-land.yml
Labels: cla-signed

#6936 [post-land] propagate diem name change
  .github/workflows/post-land.yml
Labels: cla-signed

#6968 [cluster-test] Update grafana link
  scripts/cti
Labels: cla-signed

#6997 [small] Replace libra -> diem in repo name in docs
  developers.diem.com/docs/move/creating-coins.md
Labels: cla-signed

#7077 [move-model] Further cleanup of move-model.
  language/move-model/src/ast.rs
  language/move-model/src/builder/README.md
  language/move-model/src/builder/exp_rewriter.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/builder/mod.rs
  language/move-model/src/builder/model_builder.rs
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/builder/spec_builtins.rs
  language/move-model/src/code_writer.rs
  language/move-model/src/lib.rs
  language/move-model/src/model.rs
  language/move-model/src/pragmas.rs
  language/move-model/src/translate.rs
  language/move-model/src/ty.rs
  language/move-model/tests/testsuite.rs
  language/move-prover/abigen/src/abigen.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/clean_and_optimize.rs
  language/move-prover/bytecode/src/compositional_analysis.rs
  language/move-prover/bytecode/src/eliminate_imm_refs.rs
  language/move-prover/bytecode/src/eliminate_mut_refs.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/function_target_pipeline.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/memory_instrumentation.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/reaching_def_analysis.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/bytecode/src/stackless_bytecode_generator.rs
  language/move-prover/bytecode/src/test_instrumenter.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/docgen/src/docgen.rs
  language/move-prover/errmapgen/src/errmapgen.rs
  language/move-prover/src/boogie_helpers.rs
  language/move-prover/src/boogie_wrapper.rs
  language/move-prover/src/bytecode_translator.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
  language/move-prover/src/spec_translator.rs
Labels: cla-signed
