Repository diem/diem, pull requests merged in 2020-08, with the labels that each got.

#5450 [backup] fix that my name is in sample config -_-
  storage/backup/backup-cli/src/storage/command_adapter/s3.sample.toml
Labels: cla-signed

#5471 [noise] change noisy noise log critical -> warning
  network/src/transport.rs
Labels: cla-signed

#5497 [json-rpc] Adding raw bytes for Transaction and Script
  json-rpc/src/methods.rs
  json-rpc/types/src/views.rs
Labels: cla-signed

#5511 [db-bootstrapper] print more information
  Cargo.lock
  execution/db-bootstrapper/src/bin/db-bootstrapper.rs
  storage/storage-interface/src/lib.rs
  testsuite/Cargo.toml
  testsuite/tests/libratest/smoke_test.rs
Labels: cla-signed

#5512 [move-prover] Prover changes and fix resulting from work on error model.
  language/move-prover/spec-lang/src/env.rs
  language/move-prover/spec-lang/src/translate.rs
  language/move-prover/src/boogie_wrapper.rs
  language/move-prover/src/bytecode_translator.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
  language/move-prover/src/prelude.bpl
  language/move-prover/src/spec_translator.rs
  language/move-prover/tests/sources/functional/aborts_if.exp
  language/move-prover/tests/sources/functional/aborts_if_with_code.exp
  language/move-prover/tests/sources/functional/aborts_if_with_code_partial_error.exp
  language/move-prover/tests/sources/functional/arithm.exp
  language/move-prover/tests/sources/functional/cast.exp
  language/move-prover/tests/sources/functional/loops.exp
  language/move-prover/tests/sources/functional/pragma.exp
  language/move-prover/tests/sources/functional/restrictions.exp
  language/move-prover/tests/sources/functional/restrictions.move
  language/move-prover/tests/sources/functional/schema_exp.exp
  language/move-prover/tests/sources/functional/script_incorrect.exp
  language/move-prover/tests/sources/functional/unused_schema.exp
  language/move-prover/tests/sources/functional/unused_schema.move
Labels: cla-signed

#5522 [logging] ensure TCP structured logging writes all data
  common/logger/src/struct_log.rs
Labels: bors-high-priority, cla-signed, logging

#5521 [breaking][storage] trivial: one less level of db dir
  config/src/config/storage_config.rs
Labels: breaking, cla-signed

#5528 ci: enable land-blocking test on the 'canary' branch
  .github/workflows/land-blocking.yml
Labels: cla-signed

#5594 [db-bootstrapper] use read-only for waypoint generation
  execution/db-bootstrapper/src/bin/db-bootstrapper.rs
Labels: cla-signed

#5607 [fix] fix gas consume of native_destroy_signer
  language/move-vm/natives/src/account.rs
Labels: cla-signed

#5609 [dead code][vm] Kill Unused Entries Check
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/mod.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/unused_entry_tests.rs
  language/bytecode-verifier/src/lib.rs
  language/bytecode-verifier/src/unused_entries.rs
Labels: cla-signed

#5614 [consensus] return Err with successful timeout
  consensus/src/epoch_manager.rs
  consensus/src/round_manager.rs
  consensus/src/round_manager_test.rs
Labels: cla-signed

#5618 [consensus] add missing monitor for epoch messages
  consensus/consensus-types/src/epoch_retrieval.rs
  consensus/src/epoch_manager.rs
Labels: cla-signed

#5628 [move prover] add smt.QI threshold options
  language/move-prover/src/cli.rs
Labels: cla-signed

#5630 [execution] Only log skipping when skipping transactions
  execution/executor/src/lib.rs
Labels: cla-signed, logging

#5632 [metrics] update push metrics to leverage prometheus counters
  Cargo.lock
  common/logger/src/counters.rs
  consensus/safety-rules/src/counters.rs
  consensus/safety-rules/src/lib.rs
  consensus/safety-rules/src/main.rs
  consensus/safety-rules/src/persistent_safety_storage.rs
  consensus/safety-rules/src/safety_rules.rs
  secure/key-manager/src/counters.rs
  secure/key-manager/src/lib.rs
  secure/key-manager/src/main.rs
  secure/push-metrics/Cargo.toml
  secure/push-metrics/src/counters.rs
  secure/push-metrics/src/lib.rs
  secure/push-metrics/src/pusher.rs
Labels: cla-signed

#5636 [move-prover] Disable extensionality when array theory is used
  language/move-prover/src/cli.rs
Labels: cla-signed

#5660 [state sync] add size limit to pending LI store to prevent OOM
  config/src/config/state_sync_config.rs
  state-synchronizer/src/coordinator.rs
Labels: deps-changed

#5661 [logging] added tests around logging and levels
  common/logger/src/lib.rs
  common/logger/src/struct_log.rs
  common/logger/src/tests/mod.rs
  common/logger/src/tests/struct_log.rs
Labels: cla-signed, logging

#5663 [cluster-test] Add --chain-id argument
  testsuite/cluster-test/src/cluster.rs
  testsuite/cluster-test/src/main.rs
  testsuite/cluster-test/src/tx_emitter.rs
Labels: cla-signed, deps-changed

#5703 [cluster-test] Increase default cti timeout
  scripts/cti
Labels: bors-high-priority, cla-signed, cluster_test, deps-changed

#5706 fix typo in github workflow step
  .github/workflows/dep-summaries.yml
Labels: cla-signed

#5710 [spec] Add data structure spec
  specifications/data_structure/spec.md
  specifications/images/accumulator.png
  specifications/images/accumulator_proof.png
  specifications/images/full_prefix_tree.png
  specifications/images/replace_empty_subtree.png
  specifications/images/replace_single_subtree.png
  specifications/images/sparse_merkle_copy_on_write.png
  specifications/images/sparse_merkle_proof.png
Labels: cla-signed

#5735 [move-prover] fixed specs in Errors
  language/move-prover/src/bytecode_translator.rs
  language/stdlib/modules/Errors.move
  language/stdlib/modules/doc/Errors.md
Labels: cla-signed

#5746 Add reviewers for crypto code
  .github/CODEOWNERS
Labels: cla-signed

#5745 [crypto, test-only] Point decompression checks + test output
  crypto/crypto/src/unit_tests/ed25519_test.rs
Labels: cla-signed

#5751 [cluster-test] revert change for delete job immdiately once it is done
  testsuite/cluster-test/src/cluster_swarm/cluster_swarm_kube.rs
Labels: bors-high-priority, cla-signed, cluster_test

#5747 enabled adding lints to warning list to clippy
  devtools/x/src/clippy.rs
  devtools/x/src/config.rs
  x.toml
Labels: cla-signed, deps-changed, tcb-deps-changed

#5754 Expose preburn/total values of CurrencyInfoResource
  types/src/account_config/resources/currency_info.rs
Labels: cla-signed

#5780 [Key Manager] Add the missing README to the key manager directory.
  secure/key-manager/README.md
Labels: cla-signed, deps-changed, tcb-deps-changed

#5789 [dependency] update serde-generate to 0.13.0
  Cargo.lock
  common/libradoc/Cargo.toml
  language/transaction-builder/generator/Cargo.toml
  language/transaction-builder/generator/examples/golang/stdlib_demo.go
  language/transaction-builder/generator/src/golang.rs
  summaries/summary-release.toml
Labels: deps-changed

#5792 cherry picking: [backup] transaction restore: not try to write LedgerInfo from the pr…
  language/tools/transaction-replay/src/transaction_debugger_interface.rs
  storage/backup/backup-cli/src/backup_types/transaction/restore.rs
  storage/backup/backup-cli/src/backup_types/transaction/tests.rs
  storage/libradb/src/backup/restore_handler.rs
  storage/libradb/src/lib.rs
  storage/storage-interface/src/lib.rs
Labels: cla-signed

#5811 [move-prover] Bug fixes for `old(..)` + new `update_field` builtin function
  language/move-prover/spec-lang/src/ast.rs
  language/move-prover/spec-lang/src/translate.rs
  language/move-prover/src/prelude.bpl
  language/move-prover/src/spec_translator.rs
  language/move-prover/tests/sources/functional/global_invariants.exp
  language/move-prover/tests/sources/functional/global_invariants.move
  language/move-prover/tests/sources/functional/let.move
  language/stdlib/compiled/stdlib/36_LibraSystem.mv
  language/stdlib/modules/LibraSystem.move
  language/stdlib/modules/LibraTimestamp.move
  language/stdlib/modules/VASP.move
  language/stdlib/modules/doc/LibraSystem.md
  language/stdlib/modules/doc/LibraTimestamp.md
  language/stdlib/modules/doc/VASP.md
Labels: cla-signed

#5812 Create constructor for CurrencyInfoResource
  types/src/account_config/resources/currency_info.rs
Labels: cla-signed

#5814 [Secure Storage] Remove "unimplemented!()" as default implementation for CryptoStorage.
  secure/storage/src/crypto_storage.rs
Labels: cla-signed

#5830 [fix] fix shift error when fuzzing accumulator schema
  types/src/proof/position/mod.rs
Labels: cla-signed

#5831 Typo fixes in type_transaction.md
  json-rpc/docs/type_transaction.md
Labels: cla-signed

#5836 JSON-RPC spec: fixed the data type of event.sequence_number
  json-rpc/docs/type_event.md
Labels: cla-signed
