Repository diem/diem, pull requests merged in 2020-09, with the labels that each got.

#5867 [easy][safety-rules] fix the error representation
  consensus/safety-rules/src/error.rs
Labels: cla-signed

#5873 [storage][dashboard] add restore status panel
  terraform/templates/dashboards/storage.json
Labels: cla-signed

#5885 [ci] Remove checked in summaries
  .circleci/config.yml
  .github/CODEOWNERS
  .github/workflows/dep-summaries.yml
  summaries/summary-default.toml
  summaries/summary-full.toml
  summaries/summary-lec.toml
  summaries/summary-lsr.toml
  summaries/summary-release.toml
Labels: cla-signed

#5886 add tools buildspec
  docker/build-aws.sh
  docker/tools/buildspec.yaml
Labels: cla-signed

#5893 cli: don't init the logger twice
  testsuite/cli/src/main.rs
Labels: bors-high-priority, cla-signed, deps-changed, tcb-deps-changed

#5899 [language][e2e tests] make event handle generation deterministic
  language/testing-infra/e2e-tests/src/account.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#5898 [storage][dashboard] add estimated tree size with prune window counter
  storage/libradb/src/metrics.rs
  storage/libradb/src/pruner/mod.rs
  terraform/templates/dashboards/storage.json
Labels: cla-signed, deps-changed, tcb-deps-changed

#5906 key-manager: define and use a typed log schema
  secure/key-manager/src/lib.rs
  secure/key-manager/src/logging.rs
  secure/key-manager/src/main.rs
Labels: cla-signed

#5907 executor: define and use a typed log schema
  Cargo.lock
  execution/executor/Cargo.toml
  execution/executor/src/lib.rs
  execution/executor/src/logging.rs
  execution/executor/src/speculation_cache/mod.rs
Labels: cla-signed

#5931 Fix dep verifier
  .github/workflows/dep-summaries.yml
Labels: cla-signed

#5935 [cli] fix cli logger
  testsuite/cli/src/main.rs
Labels: cla-signed

#5938 [docker] Fix build script
  docker/libra-build.sh
Labels: cla-signed

#5946 [dkr] add ENABLE_FAILPOINTS to all Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/init/Dockerfile
  docker/mint/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
Labels: cla-signed

#5961 [json-rpc] standard jsonrpc response object
  json-rpc/src/runtime.rs
  json-rpc/types/src/response.rs
  json-rpc/types/src/views.rs
Labels: cla-signed

#5979 [network] remove StructuredLogEntry
  network/src/logging.rs
  network/src/noise/handshake.rs
  network/src/transport.rs
Labels: cla-signed, logging, network

#6001 update client checklist doc
  json-rpc/docs/client_checklist.md
Labels: cla-signed

#6015 [fuzz] disable JellyfishGetWithProof harness
  testsuite/libra-fuzzer/src/fuzz_targets.rs
Labels: cla-signed

#6022 Reordering of ReceivedMintEvent
  types/src/account_config/events/received_mint.rs
Labels: cla-signed

#6043 [ci] Don't run dependency verifier workflow on bors-libra events
  .github/workflows/dep-summaries.yml
Labels: cla-signed

#6063 x: only check for newline at EOF if file isn't empty
  devtools/x/src/lint/whitespace.rs
Labels: bors-high-priority, cla-signed

#6073 [compose] update to valid images
  docker/compose/mint/docker-compose.yaml
  docker/compose/validator-testnet/docker-compose.yaml
Labels: cla-signed

#6092 [dkr] Fix service account auth with gsutil
  docker/tools/Dockerfile
  docker/tools/boto.cfg
Labels: bors-high-priority, cla-signed

#6099 Add HTTPError to JsonRpcAsyncClientError and update is_retriable logic
  client/json-rpc/src/client.rs
Labels: cla-signed

#6111 [transaction builder generator] update serde-generate
  Cargo.lock
  common/libradoc/Cargo.toml
  language/transaction-builder/generator/Cargo.toml
  language/transaction-builder/generator/tests/generation.rs
Labels: deps-changed

#6123 [LBT][compat] propogate validator image rename
  .github/actions/land-blocking/find-lbt-images.sh
Labels: bors-high-priority, cla-signed

#6135 [management] allow owner/operator support for adding new validator
  config/management/operational/src/command.rs
  config/management/operational/src/lib.rs
  config/management/operational/src/owner.rs
  config/management/operational/src/validator_config.rs
Labels: cla-signed

#6148 logger: capture thread name if available
  common/logger/src/libra_logger.rs
Labels: cla-signed

#6162 trivial: improve error message
  storage/accumulator/src/lib.rs
Labels: cla-signed

#6163 [storage] ensure client known_version no newer than leger version, earlier
  storage/libradb/src/lib.rs
Labels: cla-signed

#6242 [move-prover] Turn off verification of fixedpoint32.
  language/move-prover/tests/sources/functional/fixed_point_arithm.exp
  language/move-prover/tests/sources/functional/fixed_point_arithm.move
  language/stdlib/transaction_scripts/doc/overview.md
  language/stdlib/transaction_scripts/mint_lbr.move
Labels: cla-signed

#6264 [Smoke Tests] Update and clean up key manager smoke test.
  testsuite/smoke-test/src/key_manager.rs
Labels: cla-signed

#6286 [move-prover] Update installation instructions.
  language/move-prover/doc/user/install.md
Labels: cla-signed
