Repository diem/diem, pull requests merged in 2020-10, with the labels that each got.

#6364 [move-prover][docgen] Generate use-declarations and reduce constant footprint
  language/move-prover/docgen/src/docgen.rs
  language/move-prover/docgen/tests/sources/LibraTest.spec_inline.md
  language/move-prover/docgen/tests/sources/LibraTest.spec_inline_no_fold.md
  language/move-prover/docgen/tests/sources/LibraTest.spec_separate.md
  language/move-prover/docgen/tests/sources/root_template.spec_inline.md
  language/move-prover/docgen/tests/sources/root_template.spec_inline_no_fold.md
  language/move-prover/docgen/tests/sources/root_template.spec_separate.md
  language/move-prover/docgen/tests/sources/some_script.spec_inline.md
  language/move-prover/docgen/tests/sources/some_script.spec_inline_no_fold.md
  language/move-prover/docgen/tests/sources/some_script.spec_separate.md
  language/move-prover/spec-lang/src/ast.rs
  language/move-prover/spec-lang/src/env.rs
  language/move-prover/spec-lang/src/ty.rs
  language/stdlib/modules/doc/AccountFreezing.md
  language/stdlib/modules/doc/AccountLimits.md
  language/stdlib/modules/doc/Authenticator.md
  language/stdlib/modules/doc/ChainId.md
  language/stdlib/modules/doc/Coin1.md
  language/stdlib/modules/doc/Compare.md
  language/stdlib/modules/doc/CoreAddresses.md
  language/stdlib/modules/doc/Debug.md
  language/stdlib/modules/doc/DesignatedDealer.md
  language/stdlib/modules/doc/DualAttestation.md
  language/stdlib/modules/doc/Errors.md
  language/stdlib/modules/doc/Event.md
  language/stdlib/modules/doc/FixedPoint32.md
  language/stdlib/modules/doc/Genesis.md
  language/stdlib/modules/doc/Hash.md
  language/stdlib/modules/doc/LBR.md
  language/stdlib/modules/doc/LCS.md
  language/stdlib/modules/doc/Libra.md
  language/stdlib/modules/doc/LibraAccount.md
  language/stdlib/modules/doc/LibraBlock.md
  language/stdlib/modules/doc/LibraConfig.md
  language/stdlib/modules/doc/LibraSystem.md
  language/stdlib/modules/doc/LibraTimestamp.md
  language/stdlib/modules/doc/LibraTransactionPublishingOption.md
  language/stdlib/modules/doc/LibraVMConfig.md
  language/stdlib/modules/doc/LibraVersion.md
  language/stdlib/modules/doc/Offer.md
  language/stdlib/modules/doc/Option.md
  language/stdlib/modules/doc/RecoveryAddress.md
  language/stdlib/modules/doc/RegisteredCurrencies.md
  language/stdlib/modules/doc/Roles.md
  language/stdlib/modules/doc/SharedEd25519PublicKey.md
  language/stdlib/modules/doc/Signature.md
  language/stdlib/modules/doc/Signer.md
  language/stdlib/modules/doc/SlidingNonce.md
  language/stdlib/modules/doc/TransactionFee.md
  language/stdlib/modules/doc/VASP.md
  language/stdlib/modules/doc/ValidatorConfig.md
  language/stdlib/modules/doc/ValidatorOperatorConfig.md
  language/stdlib/modules/doc/Vector.md
  language/stdlib/transaction_scripts/doc/overview.md
Labels: cla-signed

#6368 [libra-framework] Cleanup of Event, FixedPoint32, LibraTimestamp, and Roles
  language/stdlib/modules/Event.move
  language/stdlib/modules/FixedPoint32.move
  language/stdlib/modules/LibraTimestamp.move
  language/stdlib/modules/Roles.move
  language/stdlib/modules/doc/AccountFreezing.md
  language/stdlib/modules/doc/AccountLimits.md
  language/stdlib/modules/doc/Authenticator.md
  language/stdlib/modules/doc/ChainId.md
  language/stdlib/modules/doc/Coin1.md
  language/stdlib/modules/doc/Compare.md
  language/stdlib/modules/doc/CoreAddresses.md
  language/stdlib/modules/doc/Debug.md
  language/stdlib/modules/doc/DesignatedDealer.md
  language/stdlib/modules/doc/DualAttestation.md
  language/stdlib/modules/doc/Errors.md
  language/stdlib/modules/doc/Event.md
  language/stdlib/modules/doc/FixedPoint32.md
  language/stdlib/modules/doc/Genesis.md
  language/stdlib/modules/doc/Hash.md
  language/stdlib/modules/doc/LBR.md
  language/stdlib/modules/doc/LCS.md
  language/stdlib/modules/doc/Libra.md
  language/stdlib/modules/doc/LibraAccount.md
  language/stdlib/modules/doc/LibraBlock.md
  language/stdlib/modules/doc/LibraConfig.md
  language/stdlib/modules/doc/LibraSystem.md
  language/stdlib/modules/doc/LibraTimestamp.md
  language/stdlib/modules/doc/LibraTransactionPublishingOption.md
  language/stdlib/modules/doc/LibraVMConfig.md
  language/stdlib/modules/doc/LibraVersion.md
  language/stdlib/modules/doc/Offer.md
  language/stdlib/modules/doc/Option.md
  language/stdlib/modules/doc/RecoveryAddress.md
  language/stdlib/modules/doc/RegisteredCurrencies.md
  language/stdlib/modules/doc/Roles.md
  language/stdlib/modules/doc/SharedEd25519PublicKey.md
  language/stdlib/modules/doc/Signature.md
  language/stdlib/modules/doc/Signer.md
  language/stdlib/modules/doc/SlidingNonce.md
  language/stdlib/modules/doc/TransactionFee.md
  language/stdlib/modules/doc/VASP.md
  language/stdlib/modules/doc/ValidatorConfig.md
  language/stdlib/modules/doc/ValidatorOperatorConfig.md
  language/stdlib/modules/doc/Vector.md
  language/stdlib/modules/doc/overview.md
  language/stdlib/modules/references_template.md
  language/stdlib/transaction_scripts/doc/overview.md
Labels: cla-signed

#6473 [consensus][observability] Capture time as a gauge
  consensus/src/epoch_manager.rs
Labels: cla-signed

#6484 [Key Manager] Log the key manager config on startup for better observability.
  secure/key-manager/src/main.rs
Labels: cla-signed

#6499 Cherry-pick PR #6480 into release-0.23: [cluster-test] fix feature of reusable account
  testsuite/cluster-test/src/tx_emitter.rs
Labels: cla-signed

#6503 [move-prover][documentation] Framework specification overview.
  language/stdlib/modules/doc/overview.md
  language/stdlib/modules/overview_template.md
  language/stdlib/transaction_scripts/doc/spec_documentation.md
  language/stdlib/transaction_scripts/doc/transaction_script_documentation.md
  language/stdlib/transaction_scripts/spec_documentation_template.md
  language/stdlib/transaction_scripts/transaction_script_documentation_template.md
Labels: cla-signed, documentation

#6520 Add NamedChain for pre-mainnet
  types/src/chain_id.rs
Labels: cla-signed

#6535 libra-node: periodically dump interesting state
  common/debug-interface/src/node_debug_service.rs
  libra-node/src/lib.rs
Labels: cla-signed

#6546 Cherry-pick PR #6542 into release-1.0: [libra-node] fix test json-rpc service
  libra-node/src/lib.rs
Labels: cla-signed

#6575 [move-prover][doc] Fixing broken link.
  language/move-prover/doc/user/spec-lang.md
Labels: cla-signed, documentation

#6585 [sccache] fixing shameful logic bug
  devtools/x/src/utils.rs
Labels: cla-signed

#6583 [cherry-pick][state sync] verify waypoint's end-of-epoch li matches end-of-chunk v…
  state-synchronizer/src/coordinator.rs
  state-synchronizer/src/tests/integration_tests.rs
  testsuite/smoke-test/src/state_sync.rs
Labels: bors-high-priority

#6581 [cherry-pick] [state sync] prune outdated LIs from PendingLedgerInfo
  state-synchronizer/src/coordinator.rs
  state-synchronizer/src/tests/integration_tests.rs
Labels: bors-high-priority

#6610 [cherry-pick][network] fix memory leak, remove stream-ratelimiter from network
  network/src/peer/mod.rs
Labels: bug, cla-signed, network

#6579 Cherry pick [json-rpc] fix cors validation to allow cross domain call in browser for release 1.0
  json-rpc/src/runtime.rs
  json-rpc/src/tests/unit_tests.rs
Labels: cla-signed

#6600 cherry-pick [json-rpc] get_metadata only return move version info when requesting latest version
  json-rpc/docs/method_get_metadata.md
  json-rpc/docs/type_metadata.md
  json-rpc/src/methods.rs
  json-rpc/tests/integration_test.rs
Labels: cla-signed
