Repository diem/diem, pull requests merged in 2020-11, with the labels that each got.

#6642 ci: stop using set-env
  .github/workflows/land-blocking.yml
  .github/workflows/post-land.yml
Labels: cla-signed

#6643 Cherry-pick PR #6627 into release-1.0: [config] set chunk size for state sync to 1k
  config/src/config/state_sync_config.rs
  state-synchronizer/src/tests/integration_tests.rs
Labels: cla-signed

#6665 [logger] Opening logs for write+append, instead of only write
  common/logger/src/libra_logger.rs
Labels: cla-signed

#6687 [dep] update futures/future-util
  Cargo.lock
  common/bounded-executor/Cargo.toml
  common/channel/Cargo.toml
  common/channel/many-keys-stress-test/Cargo.toml
  common/metrics/Cargo.toml
  consensus/Cargo.toml
  json-rpc/Cargo.toml
  language/libra-tools/libra-events-fetcher/Cargo.toml
  language/move-prover/Cargo.toml
  libra-node/Cargo.toml
  mempool/Cargo.toml
  mempool/src/shared_mempool/coordinator.rs
  network/Cargo.toml
  network/builder/Cargo.toml
  network/memsocket/Cargo.toml
  network/netcore/Cargo.toml
  network/simple-onchain-discovery/Cargo.toml
  network/socket-bench-server/Cargo.toml
  network/src/protocols/health_checker/mod.rs
  network/src/protocols/rpc/mod.rs
  secure/json-rpc/Cargo.toml
  secure/key-manager/Cargo.toml
  state-synchronizer/Cargo.toml
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-service/Cargo.toml
  storage/storage-service/Cargo.toml
  testsuite/cluster-test/Cargo.toml
  testsuite/cluster-test/src/main.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#6657 Cherry-pick PR #6642 into release-1.0: ci: stop using set-env
  .github/workflows/land-blocking.yml
  .github/workflows/post-land.yml
Labels: cla-signed

#6691 [network] Decrease Healthchecker logs
  network/src/protocols/health_checker/mod.rs
Labels: cla-signed, logging, network

#6699 [backup] default chunk size: 128M
  storage/backup/backup-cli/src/utils/mod.rs
Labels: cla-signed

#6697 Cherry-pick PR #6668 into release-1.0: [storage] shrink default prune_window
  config/src/config/storage_config.rs
Labels: cla-signed

#6702 Cherry-pick PR #6699 into release-1.0: [backup] default chunk size: 128M
  storage/backup/backup-cli/src/utils/mod.rs
Labels: cla-signed

#6717 [json-rpc] add field Metadat#accumulator_root_hash to protobuf definition
  json-rpc/types/src/proto/jsonrpc.proto
Labels: cla-signed

#6721 [serde-generate] upgrade to 0.16.0
  Cargo.lock
  common/libradoc/Cargo.toml
  language/transaction-builder/generator/Cargo.toml
  language/transaction-builder/generator/examples/java/custom_libra_code/AccountAddress.java
Labels: deps-changed

#6694 [Consensus] Improve error handling for failure to initialize safety rules
  consensus/safety-rules/src/error.rs
  consensus/safety-rules/src/persistent_safety_storage.rs
  consensus/safety-rules/src/safety_rules.rs
  consensus/src/epoch_manager.rs
Labels: cla-signed

#6715 [move-stdlib] Minor fix in the comments of the transaction scripts
  client/transaction-builder/src/stdlib.rs
  language/stdlib/compiled/transaction_scripts/abi/freeze_account.abi
  language/stdlib/compiled/transaction_scripts/abi/unfreeze_account.abi
  language/stdlib/compiled/transaction_scripts/abi/update_dual_attestation_limit.abi
  language/stdlib/compiled/transaction_scripts/abi/update_exchange_rate.abi
  language/stdlib/compiled/transaction_scripts/abi/update_minting_ability.abi
  language/stdlib/transaction_scripts/doc/transaction_script_documentation.md
  language/stdlib/transaction_scripts/freeze_account.move
  language/stdlib/transaction_scripts/unfreeze_account.move
  language/stdlib/transaction_scripts/update_dual_attestation_limit.move
  language/stdlib/transaction_scripts/update_exchange_rate.move
  language/stdlib/transaction_scripts/update_minting_ability.move
Labels: cla-signed, move-stdlib

#6705 [backup] restrict state_snapshot_interval to be n times transaction_b…
  storage/backup/backup-cli/src/coordinators/backup.rs
  storage/backup/backup-cli/src/lib.rs
  testsuite/smoke-test/src/storage.rs
Labels: cla-signed

#6735 [ci] turn dependabot up to eleven
  .github/dependabot.yml
Labels: cla-signed

#6746 [circleci] use target determinator to only run a subset of unit tests
  .circleci/config.yml
Labels: cla-signed

#6747 [x] don't ignore deleted files in changed-since
  devtools/x/src/changed_since.rs
Labels: cla-signed

#6755 Update a broken link of Execution in README.md
  README.md
Labels: cla-signed
