Repository diem/diem, pull requests merged in 2021-01, with the labels that each got.

#7102 [network] emit metadata on new and lost peers
  mempool/src/tests/shared_mempool_test.rs
  network/src/connectivity_manager/mod.rs
  network/src/connectivity_manager/test.rs
  network/src/peer_manager/conn_notifs_channel.rs
  network/src/peer_manager/mod.rs
  network/src/peer_manager/tests.rs
  network/src/protocols/health_checker/test.rs
  network/src/protocols/network/mod.rs
  state-synchronizer/src/tests/integration_tests.rs
Labels: cla-signed

#7109 [ci] check remote for target base branch
  .circleci/get_pr_info.sh
Labels: bors-high-priority, cla-signed

#7108 point to the new pfn testnet config
  developers.diem.com/docs/node/config-deploy-fn.md
  docker/compose/public_full_node/public_full_node.yaml
Labels: cla-signed

#7107 [circleci] log about the state of looked up pr info
  .circleci/get_pr_info.sh
Labels: cla-signed

#7100 Cherry-pick PR #6955 into release-1.1: [diem framework] Increase max number of child accounts to 2^16 from 2^8
  client/transaction-builder/src/stdlib.rs
  language/e2e-testsuite/src/tests/vasps.rs
  language/stdlib/compiled/error_descriptions/error_descriptions.errmap
  language/stdlib/compiled/stdlib/024_VASP.mv
  language/stdlib/compiled/stdlib/035_RecoveryAddress.mv
  language/stdlib/compiled/transaction_scripts/abi/add_recovery_rotation_capability.abi
  language/stdlib/modules/RecoveryAddress.move
  language/stdlib/modules/VASP.move
  language/stdlib/modules/doc/RecoveryAddress.md
  language/stdlib/modules/doc/VASP.md
  language/stdlib/transaction_scripts/add_recovery_rotation_capability.move
  language/stdlib/transaction_scripts/doc/transaction_script_documentation.md
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite::tests::transaction_builder::recovery_address.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite::tests::vasps::max_child_accounts_for_vasp.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite::tests::vasps::max_child_accounts_for_vasp_recovery_address.exp
Labels: bors-high-priority

#7114 [types] utility function for converting access path into struct tag
  language/tools/resource-viewer/src/cached_access_path_table.rs
  language/tools/resource-viewer/src/lib.rs
  types/src/access_path.rs
Labels: cla-signed

#7063 [language] follow up to latest prologue/epilogue changes
  language/diem-vm/src/errors.rs
  language/e2e-testsuite/src/tests/verify_txn.rs
  language/move-core/types/src/vm_status.rs
  language/move-lang/functional-tests/tests/diem/diem_account/prologue_invalid_gas_currency.move
  language/stdlib/compiled/error_descriptions/error_descriptions.errmap
  language/stdlib/compiled/stdlib/029_DiemAccount.mv
  language/stdlib/modules/DiemAccount.move
  language/stdlib/modules/TransactionFee.move
  language/stdlib/modules/doc/DiemAccount.md
  language/stdlib/modules/doc/TransactionFee.md
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite::tests::verify_txn::publish_and_register_new_currency.exp
  specifications/move_adapter/README.md
Labels: cla-signed

#7128 [move-prover] Fix hanging if boogie is not found and print which path was tried.
  language/move-prover/src/boogie_wrapper.rs
  language/move-prover/src/prover_task_runner.rs
Labels: cla-signed

#7154 Cherry-pick PR #7113 into release-1.1: [storagte] state pruner: offload the first seek to the worker thread
  storage/diemdb/src/pruner/mod.rs
  storage/diemdb/src/pruner/test.rs
Labels: cla-signed

#7174 [mempool] return accepted for submitting same transaction in mempool
  json-rpc/tests/integration_test.rs
  mempool/Cargo.toml
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/tests/core_mempool_test.rs
Labels: bors-squash, cla-signed

#7191 [move-prover] Deactivate flaky test.
  language/move-prover/tests/sources/functional/cross_module_invariant.exp
  language/move-prover/tests/sources/functional/cross_module_invariant.move
Labels: cla-signed

#7180 [gha] caches: gha and sccache
  .circleci/config.yml
  .github/actions/build-setup/action.yml
  .github/actions/docker-checks/action.yml
  .github/workflows/ci-test.yml
  docker/ci/alpine/Dockerfile
  docker/ci/arch/Dockerfile
  docker/ci/centos/Dockerfile
  docker/ci/circleci/Dockerfile
  docker/ci/github/Dockerfile
  x.toml
Labels: cla-signed

#7196 [diem] Don't use serde::export private types
  language/move-model/src/builder/module_builder.rs
  network/netcore/src/transport/mod.rs
  network/src/connectivity_manager/mod.rs
  network/src/peer/mod.rs
  network/src/peer_manager/mod.rs
  network/src/protocols/wire/handshake/v1/mod.rs
  network/src/transport/mod.rs
  storage/backup/backup-cli/src/metadata/view.rs
  storage/diemdb/src/backup/backup_handler.rs
  types/src/account_state.rs
  types/src/chain_id.rs
Labels: cla-signed

#7193 [Secure Storage] Update vault request timeout and error handling.
  secure/storage/vault/src/lib.rs
Labels: cla-signed

#7168 Cherry-pick PR #7150 into release-1.1: [secure-storage] support github branches
  config/management/src/secure_backend.rs
  config/src/config/secure_backend_config.rs
  secure/storage/github/src/lib.rs
  secure/storage/src/error.rs
  secure/storage/src/github.rs
  secure/storage/src/tests/github.rs
  secure/storage/src/tests/suite.rs
Labels: cla-signed

#7179 Cherry-pick PR #7174 into release-1.1: [mempool] return accepted for submitting same transaction in mempool
  json-rpc/tests/integration_test.rs
  mempool/Cargo.toml
  mempool/src/core_mempool/transaction_store.rs
  mempool/src/tests/core_mempool_test.rs
Labels: cla-signed

#7219 Cherry-pick PR #7197 into release-1.1: [storage] smaller prune_window
  config/src/config/storage_config.rs
Labels: cla-signed

#7258 readme: update rustdoc link and remove circleci status
  README.md
Labels: cla-signed

#7265 [gha] single job if needed for bors
  .github/actions/matches/action.yml
  .github/workflows/ci-test.yml
Labels: cla-signed

#7257 [move][testing] Make dependencies in IR tests unique
  Cargo.lock
  language/ir-testsuite/Cargo.toml
  language/ir-testsuite/tests/testsuite.rs
Labels: cla-signed

#7294 [network] Pin inner rpc future to stack to avoid Box
  network/src/protocols/rpc/mod.rs
Labels: cla-signed, network

#7293 [dependency] updating smallvec
  Cargo.lock
Labels: bors-low-priority, cla-signed, deps-changed, tcb-deps-changed

#7281 [docker] updates and tests
  docker/ci/alpine/Dockerfile
  docker/ci/github/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/init/Dockerfile
  docker/mint/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: bors-low-priority, cla-signed

#7315 [move prover] minor improvements to domains and utility functions
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/clean_and_optimize.rs
  language/move-prover/bytecode/src/dataflow_analysis.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/usage_analysis.rs
Labels: cla-signed

#7297 [json-rpc] Support TLS on JSON-RPC port
  Cargo.lock
  config/src/config/json_rpc_config.rs
  json-rpc/Cargo.toml
  json-rpc/src/runtime.rs
  json-rpc/src/tests/utils.rs
Labels: cla-signed, deps-changed

#7309 [move-prover] Extend compositional analysis to allow summaries of different type v2
  language/move-prover/bytecode/src/compositional_analysis.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/usage_analysis.rs
Labels: cla-signed

#7316 [diemdb] correct rocksdb property names
  storage/diemdb/src/lib.rs
Labels: cla-signed

#7303 [cherry-pick][dependency] updating smallvec
  Cargo.lock
Labels: cla-signed, deps-changed, tcb-deps-changed

#7326 Updates security url
  SECURITY.md
Labels: cla-signed

#7321 [vm] Fix bug in creation of normalized types
  language/vm/src/normalized.rs
Labels: cla-signed

#7325 [gha] docker pushes and release audit
  .circleci/config.yml
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test.yml
  .github/workflows/daily.yml
  .github/workflows/docker-publish.yml
Labels: cla-signed

#7306 [x] adding json/toml output to generate-summaries
  devtools/x/src/diff_summary.rs
  devtools/x/src/generate_summaries.rs
Labels: cla-signed

#7334 [website] fix SDK docs link
  developers.diem.com/docs/sdks/overview.md
Labels: cla-signed

#7320 [move-prover] Extending the Prover for the `emits` statements
  language/move-prover/src/prelude.bpl
  language/move-prover/src/spec_translator.rs
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/emits.move
  language/stdlib/modules/Diem.move
  language/stdlib/modules/Event.move
  language/stdlib/transaction_scripts/update_exchange_rate.move
Labels: cla-signed

#7353 [backup] fix failure with updated tokio
  storage/backup/backup-cli/src/storage/command_adapter/command.rs
Labels: cla-signed

#7329 [backup] support for specifying trusted waypoints in restore / verify
  Cargo.lock
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-cli/src/backup_types/epoch_ending/restore.rs
  storage/backup/backup-cli/src/backup_types/epoch_ending/tests.rs
  storage/backup/backup-cli/src/backup_types/state_snapshot/tests.rs
  storage/backup/backup-cli/src/backup_types/tests.rs
  storage/backup/backup-cli/src/backup_types/transaction/tests.rs
  storage/backup/backup-cli/src/bin/db-backup.rs
  storage/backup/backup-cli/src/coordinators/verify.rs
  storage/backup/backup-cli/src/utils/mod.rs
Labels: cla-signed

#7354 [deps] kube update
  Cargo.lock
  testsuite/cluster-test/Cargo.toml
Labels: cla-signed

#7319 [backup] trait ErrorNotes
  storage/backup/backup-cli/src/metadata/cache.rs
  storage/backup/backup-cli/src/storage/command_adapter/command.rs
  storage/backup/backup-cli/src/storage/command_adapter/config.rs
  storage/backup/backup-cli/src/storage/command_adapter/mod.rs
  storage/backup/backup-cli/src/storage/local_fs/mod.rs
  storage/backup/backup-cli/src/storage/mod.rs
  storage/backup/backup-cli/src/utils/backup_service_client.rs
  storage/backup/backup-cli/src/utils/error_notes.rs
  storage/backup/backup-cli/src/utils/mod.rs
  storage/backup/backup-cli/src/utils/read_record_bytes.rs
Labels: cla-signed

#7323 [move][vm] Versioned deserializer
  language/vm/src/deserializer.rs
  language/vm/src/file_format_common.rs
  language/vm/src/unit_tests/signature_token_tests.rs
Labels: cla-signed, language

#7328 [cluster-test] Clone vault image to ECR and pull from ECR instead of …
  testsuite/cluster-test/src/cluster_swarm/templates/vault_spec_template.yaml
Labels: cla-signed

#7358 update faucet documentation
  client/faucet/README.md
  json-rpc/docs/service_testnet_faucet.md
Labels: cla-signed

#7370 [move source language] Don't inline asisgnments to parameters
  language/move-lang/functional-tests/tests/move/commands/if_assignment.move
  language/move-lang/src/cfgir/eliminate_locals.rs
  language/move-lang/src/cfgir/mod.rs
Labels: bug-fix, cla-signed, language

#7373 [gha] report on all docker errors at end of each step:
  .github/workflows/docker-publish.yml
  docker/docker_republish.sh
Labels: cla-signed

#7379 [circle] remove it
  .circleci/config.yml
  .circleci/get_pr_info.sh
Labels: cla-signed

#7380 [release-1.1] Remove circle-ci config
  .circleci/config.yml
  .circleci/get_pr_info.sh
Labels: bors-high-priority, cla-signed

#7375 [Storage] Make jellyfish merkle tree value generic
  storage/backup/backup-cli/src/utils/mod.rs
  storage/diemdb/src/backup/restore_handler.rs
  storage/diemdb/src/schema/jellyfish_merkle_node/mod.rs
  storage/diemdb/src/state_store/mod.rs
  storage/jellyfish-merkle/src/iterator/iterator_test.rs
  storage/jellyfish-merkle/src/iterator/mod.rs
  storage/jellyfish-merkle/src/jellyfish_merkle_test.rs
  storage/jellyfish-merkle/src/lib.rs
  storage/jellyfish-merkle/src/mock_tree_store.rs
  storage/jellyfish-merkle/src/node_type/mod.rs
  storage/jellyfish-merkle/src/node_type/node_type_test.rs
  storage/jellyfish-merkle/src/restore/mod.rs
  storage/jellyfish-merkle/src/restore/restore_test.rs
  storage/jellyfish-merkle/src/test_helper.rs
  storage/jellyfish-merkle/src/tree_cache/mod.rs
  storage/jellyfish-merkle/src/tree_cache/tree_cache_test.rs
  testsuite/diem-fuzzer/src/fuzz_targets/storage.rs
Labels: cla-signed

#7404 [mempool][documentation] Fixed line break in mempool README.md
  mempool/README.md
Labels: cla-signed

#7393 [language] switch diem tests to exp mode -- admin_scripts/authenticator/block
  language/move-lang/functional-tests/tests/diem/admin_scripts/basic_admin_script.exp
  language/move-lang/functional-tests/tests/diem/admin_scripts/basic_admin_script.move
  language/move-lang/functional-tests/tests/diem/authenticator/authenticator.exp
  language/move-lang/functional-tests/tests/diem/authenticator/authenticator.move
  language/move-lang/functional-tests/tests/diem/block/block_prologue.exp
  language/move-lang/functional-tests/tests/diem/block/block_prologue.move
  language/move-lang/functional-tests/tests/diem/block/expired_transaction.exp
  language/move-lang/functional-tests/tests/diem/block/expired_transaction.move
  language/move-lang/functional-tests/tests/diem/block/get_block_height.exp
  language/move-lang/functional-tests/tests/diem/block/invalid_initialization_address.exp
  language/move-lang/functional-tests/tests/diem/block/invalid_initialization_address.move
  language/move-lang/functional-tests/tests/diem/block/none_validator_propser.exp
  language/move-lang/functional-tests/tests/diem/block/none_validator_propser.move
  language/move-lang/functional-tests/tests/diem/block/older_timestamp.exp
  language/move-lang/functional-tests/tests/diem/block/older_timestamp.move
  language/move-lang/functional-tests/tests/diem/block/vm_proposer.exp
  language/move-lang/functional-tests/tests/diem/block/vm_proposer.move
Labels: cla-signed

#7401 [move source language] Fix arity bug in pack/unpack
  language/move-lang/src/naming/translate.rs
  language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_pack.exp
  language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_pack.move
  language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_unpack.exp
  language/move-lang/tests/move_check/typing/bad_type_argument_arity_struct_unpack.move
Labels: bug-fix, cla-signed, language
