Repository diem/diem, pull requests merged in 2021-05, with the labels that each got.

#8290 [move-compiler] remove dependency on fallible
  Cargo.lock
  language/move-lang/Cargo.toml
  language/move-lang/src/shared/mod.rs
  x.toml
Labels: cla-signed

#8306 [language] remove dependency on diem-proptest-helpers from language-benchmark
  Cargo.lock
  language/benchmarks/Cargo.toml
  language/benchmarks/src/transactions.rs
  x.toml
Labels: cla-signed

#8314 [x] Workaround x context to let us build and run xtest without a git repo
  devtools/x-core/src/lib.rs
  devtools/x-lint/src/runner.rs
  devtools/x/src/cargo/selected_package.rs
  devtools/x/src/changed_since.rs
Labels: cla-signed

#8312 [pruner] fix busy looping after db-restore
  storage/diemdb/src/pruner/mod.rs
Labels: cla-signed

#8319 [json-rpc]: remove the json field metadata if the value is null
  json-rpc/types/src/views.rs
Labels: cla-signed

#8327 [helm] bump era and use get_metadata for test
  helm/fullnode/templates/tests/test-fullnode-connection.yaml
  helm/fullnode/values.yaml
Labels: cla-signed

#8322 Cherry-pick PR #8314 into release-1.2: [x] Workaround x context to let us build and run xtest without a git repo
  devtools/x-core/src/lib.rs
  devtools/x-lint/src/runner.rs
  devtools/x/src/cargo/selected_package.rs
  devtools/x/src/changed_since.rs
Labels: cla-signed

#8323 Cherry-pick PR #8319 into release-1.2: [json-rpc]: remove the json field metadata if the value is null
  json-rpc/types/src/views.rs
Labels: bors-high-priority, cla-signed, sev3-mitigate

#8330 [workspace-hack] exclude the fail crate
  Cargo.lock
  common/workspace-hack/Cargo.toml
  x.toml
Labels: cla-signed

#8332 [move-prover] Reactivate CVC4 tests and document usage.
  language/move-prover/boogie-backend/src/boogie_helpers.rs
  language/move-prover/boogie-backend/src/options.rs
  language/move-prover/boogie-backend/src/prelude/vector-array-intern-theory.bpl
  language/move-prover/boogie-backend/src/prelude/vector-array-theory.bpl
  language/move-prover/boogie-backend/src/prelude/vector-smt-seq-theory.bpl
  language/move-prover/doc/dev/cvc4.md
  language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if_assume_assert.move
  language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
  language/move-prover/tests/sources/functional/address_quant.cvc4_exp
  language/move-prover/tests/sources/functional/address_serialization_constant_size.cvc4_exp
  language/move-prover/tests/sources/functional/address_serialization_constant_size.move
  language/move-prover/tests/sources/functional/arithm.cvc4_exp
  language/move-prover/tests/sources/functional/axioms.move
  language/move-prover/tests/sources/functional/cast.cvc4_exp
  language/move-prover/tests/sources/functional/choice.cvc4_exp
  language/move-prover/tests/sources/functional/choice.move
  language/move-prover/tests/sources/functional/consts.cvc4_exp
  language/move-prover/tests/sources/functional/consts.move
  language/move-prover/tests/testsuite.rs
  scripts/dev_setup.sh
Labels: cla-signed

#8331 [move-prover] Update vector theory benchmark lab based on new mono backend
  language/move-prover/lab/data/vector-theories/boogie_array.fun_data
  language/move-prover/lab/data/vector-theories/boogie_array.mod_data
  language/move-prover/lab/data/vector-theories/notebook.ipynb
  language/move-prover/lab/data/vector-theories/notebook.pdf
  language/move-prover/lab/data/vector-theories/smt_array.fun_data
  language/move-prover/lab/data/vector-theories/smt_array.mod_data
  language/move-prover/lab/data/vector-theories/smt_array_ext.fun_data
  language/move-prover/lab/data/vector-theories/smt_array_ext.mod_data
Labels: cla-signed

#8334 [ci] relies on bors to check the entire workflow, rather than having an aggregating job.
  .github/workflows/ci-test.yml
Labels: cla-signed

#8341 [backup] update azure config to filter out azcopy garbage outputs
  .github/workflows/transaction-replay.toml
  storage/backup/backup-cli/src/storage/command_adapter/azure.sample.toml
Labels: cla-signed

#8339 [move-prover] Activate and validate most unit tests for cvc4
  .github/workflows/daily.yml
  language/move-prover/doc/dev/cvc4.md
  language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if.move
  language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if_with_code.move
  language/move-prover/tests/sources/functional/address_quant.cvc4_exp
  language/move-prover/tests/sources/functional/address_quant.move
  language/move-prover/tests/sources/functional/address_serialization_constant_size.cvc4_exp
  language/move-prover/tests/sources/functional/address_serialization_constant_size.move
  language/move-prover/tests/sources/functional/arithm.cvc4_exp
  language/move-prover/tests/sources/functional/arithm.move
  language/move-prover/tests/sources/functional/axioms.move
  language/move-prover/tests/sources/functional/cast.cvc4_exp
  language/move-prover/tests/sources/functional/cast.move
  language/move-prover/tests/sources/functional/choice.move
  language/move-prover/tests/sources/functional/consts.cvc4_exp
  language/move-prover/tests/sources/functional/consts.move
  language/move-prover/tests/sources/functional/emits.cvc4_exp
  language/move-prover/tests/sources/functional/emits.move
  language/move-prover/tests/sources/functional/exists_in_vector.move
  language/move-prover/tests/sources/functional/fixed_point_arithm.move
  language/move-prover/tests/sources/functional/global_invariants.move
  language/move-prover/tests/sources/functional/hash_model.cvc4_exp
  language/move-prover/tests/sources/functional/hash_model.move
  language/move-prover/tests/sources/functional/hash_model_invalid.move
  language/move-prover/tests/sources/functional/inconsistency.move
  language/move-prover/tests/sources/functional/invariants_resources.cvc4_exp
  language/move-prover/tests/sources/functional/invariants_resources.move
  language/move-prover/tests/sources/functional/invariants_with_quant.move
  language/move-prover/tests/sources/functional/loops.cvc4_exp
  language/move-prover/tests/sources/functional/loops.move
  language/move-prover/tests/sources/functional/loops_with_memory_ops.move
  language/move-prover/tests/sources/functional/memory.move
  language/move-prover/tests/sources/functional/mono.cvc4_exp
  language/move-prover/tests/sources/functional/mono.move
  language/move-prover/tests/sources/functional/pure_function_call.move
  language/move-prover/tests/sources/functional/pure_function_call_incorrect.move
  language/move-prover/tests/sources/functional/references.move
  language/move-prover/tests/sources/functional/resources.move
  language/move-prover/tests/sources/functional/serialize_model.cvc4_exp
  language/move-prover/tests/sources/functional/serialize_model.move
  language/move-prover/tests/sources/functional/simple_vector_client.cvc4_exp
  language/move-prover/tests/sources/functional/simple_vector_client.move
  language/move-prover/tests/sources/functional/verify_vector.cvc4_exp
  language/move-prover/tests/sources/functional/verify_vector.move
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#8340 [move-prover] instrument write-backs before the Destroy operation
  language/move-prover/bytecode/src/memory_instrumentation.rs
  language/move-prover/bytecode/tests/memory_instr/basic_test.exp
  language/move-prover/interpreter-testsuite/tests/concrete_check/loop.exp
  language/move-prover/interpreter-testsuite/tests/concrete_check/loop.move
Labels: cla-signed

#8343 [gha] open issue when db-restore fails in CI
  .github/workflows/daily.yml
Labels: cla-signed

#8349 [move-lang] Clean up shadowing lib logic
  language/benchmarks/src/move_vm.rs
  language/diem-framework/src/lib.rs
  language/diem-tools/transaction-replay/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/admin_script_builder.rs
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/bin/move-build.rs
  language/move-lang/src/bin/move-check.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/parser/mod.rs
  language/move-lang/src/parser/sources_shadow_deps.rs
  language/move-lang/src/shared/mod.rs
  language/move-lang/tests/move_check_testsuite.rs
  language/move-lang/tests/stdlib_sanity_check.rs
  language/move-model/src/lib.rs
  language/move-vm/integration-tests/src/compiler.rs
  language/tools/move-cli/src/commands.rs
  language/tools/move-cli/src/package.rs
  language/tools/move-unit-test/src/lib.rs
Labels: cla-signed

#8345 specification cleanup
  specifications/transactions/README.md
  specifications/transactions/offchain-api/README.md
  specifications/transactions/onchain/README.md
Labels: cla-signed

#8347 [forge] Implemented Tx Emitter in Forge
  Cargo.lock
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/local.rs
  testsuite/forge/src/interface/network.rs
  testsuite/forge/src/interface/node.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/forge/src/lib.rs
  testsuite/forge/src/main.rs
  testsuite/forge/src/tx_emitter.rs
Labels: cla-signed

#8384 [move-prover] Internalization for expressions plus new rewriter design
  Cargo.lock
  common/workspace-hack/Cargo.toml
  language/move-model/Cargo.toml
  language/move-model/src/ast.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/exp_generator.rs
  language/move-model/src/exp_rewriter.rs
  language/move-model/src/model.rs
  language/move-model/src/spec_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/data_invariant_instrumentation.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
Labels: cla-signed, deps-changed

#8365 [State Sync Performance Test] Add additional checks for possible error cases.
  testsuite/cluster-test/src/experiments/state_sync_performance.rs
Labels: cla-signed

#8366 [stackless-vm] produce a changeset after execution
  language/move-core/types/src/effects.rs
  language/move-prover/interpreter/src/concrete/mod.rs
  language/move-prover/interpreter/src/concrete/player.rs
  language/move-prover/interpreter/src/concrete/ty.rs
  language/move-prover/interpreter/src/concrete/value.rs
  language/move-prover/interpreter/src/lib.rs
  language/tools/move-unit-test/src/test_reporter.rs
  language/tools/move-unit-test/src/test_runner.rs
Labels: cla-signed

#8391 [move-prover] Using immutable collections for SetDomain and MapDomain
  Cargo.lock
  common/workspace-hack/Cargo.toml
  language/move-model/src/ast.rs
  language/move-prover/bytecode/Cargo.toml
  language/move-prover/bytecode/src/access_path.rs
  language/move-prover/bytecode/src/access_path_trie.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/clean_and_optimize.rs
  language/move-prover/bytecode/src/compositional_analysis.rs
  language/move-prover/bytecode/src/dataflow_analysis.rs
  language/move-prover/bytecode/src/dataflow_domains.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/reaching_def_analysis.rs
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/src/verification_analysis.rs
  language/move-prover/bytecode/src/verification_analysis_v2.rs
  language/move-prover/tests/sources/functional/disable_inv.exp
  language/move-prover/tests/sources/functional/disable_inv.inv_v2_exp
  language/move-prover/tests/sources/functional/disable_inv.move
Labels: cla-signed, deps-changed

#8337 [network] Rename ConfigurationChangeListener to ValidatorSetChangeListener
  network/builder/src/builder.rs
  network/simple-onchain-discovery/src/builder.rs
  network/simple-onchain-discovery/src/lib.rs
  network/src/connectivity_manager/mod.rs
  network/src/connectivity_manager/test.rs
  testsuite/cluster-test/src/experiments/load_test.rs
Labels: cla-signed, network, refactoring

#8413 [operational-tool] Make Key file reads trim whitespace
  config/management/operational/src/keys.rs
Labels: cla-signed

#8414 [move-lang] Fix interface generator for 'friend'
  language/move-lang/src/interface_generator.rs
Labels: cla-signed

#8406 [diem-framework] Add specifications to DiemId module
  language/diem-framework/modules/AccountAdministrationScripts.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/DiemId.move
  language/diem-framework/modules/TreasuryComplianceScripts.move
  language/diem-framework/modules/doc/AccountAdministrationScripts.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/modules/doc/DiemId.md
  language/diem-framework/modules/doc/TreasuryComplianceScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/AccountAdministrationScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemId.md
  language/diem-framework/releases/artifacts/current/docs/modules/TreasuryComplianceScripts.md
  language/diem-framework/releases/artifacts/current/docs/scripts/script_documentation.md
  language/diem-framework/releases/artifacts/current/modules/025_DiemId.mv
  language/diem-framework/releases/artifacts/current/script_abis/AccountAdministrationScripts/create_diem_id_domains.abi
  language/diem-framework/releases/artifacts/current/script_abis/TreasuryComplianceScripts/add_diem_id_domain.abi
  language/diem-framework/releases/artifacts/current/script_abis/TreasuryComplianceScripts/remove_diem_id_domain.abi
  language/diem-framework/releases/artifacts/current/transaction_script_builder.rs
  language/diem-framework/script_documentation/script_documentation.md
Labels: cla-signed

#8419 [move-prover] Finishing touches to V2 invariant processing
  language/move-model/src/model.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/bytecode/src/verification_analysis_v2.rs
  language/move-prover/bytecode/tests/mono_analysis/test.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/interpreter-testsuite/tests/concrete_check/event.exp
  language/move-prover/interpreter-testsuite/tests/concrete_check/event.move
  language/move-prover/src/cli.rs
  language/move-prover/tests/sources/functional/ModifiesErrorTest.exp
  language/move-prover/tests/sources/functional/ModifiesErrorTest.move
  language/move-prover/tests/sources/functional/disable_inv.exp
  language/move-prover/tests/sources/functional/disable_inv.move
  language/move-prover/tests/sources/functional/disable_inv_friends.move
  language/move-prover/tests/sources/functional/friend_error.exp
  language/move-prover/tests/sources/functional/friend_error.move
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#8420 Correct the Signer module documentation
  language/move-stdlib/modules/Signer.move
Labels: cla-signed

#8428 [docker] Add curl to tools image
  docker/tools/Dockerfile
Labels: cla-signed

#8431 [move-prover] test case on a potential issue with type quantifier elimination
  language/move-prover/tests/sources/regression/mono_after_global_invariant.move
Labels: cla-signed

#8435 [RPC] Break out testing utils from unit tests
  json-rpc/Cargo.toml
  json-rpc/src/fuzzing.rs
  json-rpc/src/lib.rs
  json-rpc/src/tests/mod.rs
  json-rpc/src/tests/unit_tests.rs
  json-rpc/src/tests/utils.rs
Labels: cla-signed

#8440 [move-stdlib] Add Vault::is_delegation_enabled
  language/move-stdlib/nursery/Vault.move
  language/move-stdlib/nursery/docs/Vault.md
Labels: cla-signed, move-stdlib

#8447 [move-model] Only parse once
  language/move-model/src/lib.rs
Labels: cla-signed
