Repository diem/diem, pull requests merged in 2021-11, with the labels that each got.

#9594 dev-setup: cargo install with '--locked'
  scripts/dev_setup.sh
Labels: cla-signed, bors-high-priority

#9593 deno only lints ./shuffle
  .github/workflows/ci-test.yml
Labels: cla-signed

#9485 [language][diem-transactional-tests] implement validator creation
  Cargo.lock
  diem-move/diem-keygen/src/lib.rs
  language/testing-infra/diem-transactional-test-harness/Cargo.toml
  language/testing-infra/diem-transactional-test-harness/src/diem_test_harness.rs
  language/testing-infra/diem-transactional-test-harness/tests/diem_test_harness/account_creation.exp
  language/testing-infra/diem-transactional-test-harness/tests/diem_test_harness/account_creation.move
  language/testing-infra/diem-transactional-test-harness/tests/diem_test_harness/example.exp
  language/testing-infra/diem-transactional-test-harness/tests/diem_test_harness/example.move
  language/testing-infra/transactional-test-runner/src/framework.rs
  language/testing-infra/transactional-test-runner/src/tasks.rs
Labels: cla-signed

#9573 [GHA] Terminate ci-test workflow earlier once there is job failed
  .github/actions/early-terminator/action.yml
  .github/workflows/ci-test.yml
Labels: cla-signed, bors-high-priority

#9571 [api] change type representation to string format instead of nested object
  api/doc/openapi.yaml
  api/src/tests/accounts_test.rs
  api/src/tests/events_test.rs
  api/src/tests/transactions_test.rs
  api/types/src/lib.rs
  api/types/src/move_types.rs
  api/types/src/transaction.rs
  shuffle/cli/repl.ts
  shuffle/move/examples/main/mod.ts
Labels: cla-signed

#9607 [shuffle] node uses a seed rng for clean reruns
  shuffle/cli/src/node.rs
Labels: cla-signed

#9624 disable api lint on non-rust-lint job
  .github/workflows/ci-test.yml
Labels: cla-signed, bors-high-priority

#9606 [docker] Fix docker init so that it copies compiled Move modules to the expected place and format
  docker/init/Dockerfile
Labels: cla-signed, bors-high-priority

#9627 [move-prover] Update emits.cvc4_exp
  language/move-prover/tests/sources/functional/emits.cvc4_exp
Labels: cla-signed, move-prover

#9569 [move-prover] disable #9545 temporarily and catch warnings in testsuite
  language/move-prover/bytecode/src/global_invariant_analysis.rs
  language/move-prover/bytecode/tests/global_invariant_analysis/uninst_type_param_in_inv.exp
  language/move-prover/tests/sources/functional/uninst_global_invariant.exp
  language/move-prover/tests/sources/regression/mono_after_global_invariant.exp
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#9613 [api] optimizing openapi specificatoin for client code generation
  api/doc/openapi.yaml
Labels: cla-signed

#9631 [api] api spec test job
  .github/workflows/ci-test.yml
  api/Makefile
  scripts/api_lint.sh
Labels: cla-signed

#9641 [mempool] Unsupport MempoolRpc
  mempool/src/shared_mempool/network.rs
Labels: network, mempool, cla-signed

#9637 [shuffle] console invokes script functions via dev api:
  shuffle/move/examples/main/helpers.ts
  shuffle/move/examples/main/mod.ts
Labels: cla-signed

#9639 [State Sync] Update the error message returned by the executor for failed transactions
  execution/executor/src/lib.rs
Labels: cla-signed

#9638 [mempool] Refactor execute broadcast
  Cargo.lock
  mempool/Cargo.toml
  mempool/src/shared_mempool/coordinator.rs
  mempool/src/shared_mempool/network.rs
  mempool/src/shared_mempool/tasks.rs
Labels: mempool, refactoring, cla-signed

#9605 [State Sync] Support a read-only mode for state sync v1.
  state-sync/state-sync-v1/src/bootstrapper.rs
  state-sync/state-sync-v1/src/coordinator.rs
  state-sync/state-sync-v1/src/error.rs
  state-sync/state-sync-v1/src/shared_components.rs
  state-sync/state-sync-v1/tests/integration_tests.rs
  state-sync/state-sync-v1/tests/test_harness.rs
Labels: cla-signed

#9656 [forge] turn on Forge in ci-test
  .github/workflows/ci-test.yml
Labels: cla-signed

#9663 Changed cargo edition of new emitter back to 2018
  crates/transaction-emitter/Cargo.toml
Labels: cla-signed

#9667 [fuzzer] update command for generate coverage report
  testsuite/diem-fuzzer/README.md
Labels: cla-signed

#9672 [GHA] bump up timeout to 40mins
  .github/workflows/ci-test.yml
Labels: cla-signed

#9670 [api] update dev_setup.sh to install nodejs & python tools for api build
  .github/actions/build-setup/action.yml
  .github/workflows/ci-test.yml
  docker/ci/github/Dockerfile
  scripts/dev_setup.sh
Labels: cla-signed

#9675 [shuffle] update readme.md
  shuffle/cli/README.md
Labels: cla-signed

#9680 [shuffle] txn devapi can take version|hash
  shuffle/move/examples/main/devapi.ts
Labels: cla-signed

#9668 [storage] fix fuzzer for schema decoding
  storage/jellyfish-merkle/src/node_type/mod.rs
Labels: cla-signed

#9686 [move-prover] parenthesis the ITE expression when translating to boogie
  language/move-prover/boogie-backend/src/spec_translator.rs
Labels: cla-signed

#9659 [api] test api specification
  api/Makefile
  api/README.md
  api/doc/openapi.yaml
Labels: cla-signed

#9669 [storage] test_no_panic_decoding
  consensus/src/consensusdb/schema/block/test.rs
  consensus/src/consensusdb/schema/quorum_certificate/test.rs
  consensus/src/consensusdb/schema/single_entry/test.rs
  storage/diemdb/Cargo.toml
  storage/diemdb/src/schema/epoch_by_version/test.rs
  storage/diemdb/src/schema/event/test.rs
  storage/diemdb/src/schema/event_accumulator/test.rs
  storage/diemdb/src/schema/event_by_key/test.rs
  storage/diemdb/src/schema/event_by_version/test.rs
  storage/diemdb/src/schema/jellyfish_merkle_node/test.rs
  storage/diemdb/src/schema/ledger_counters/test.rs
  storage/diemdb/src/schema/ledger_info/test.rs
  storage/diemdb/src/schema/mod.rs
  storage/diemdb/src/schema/stale_node_index/test.rs
  storage/diemdb/src/schema/transaction/test.rs
  storage/diemdb/src/schema/transaction_accumulator/test.rs
  storage/diemdb/src/schema/transaction_by_account/test.rs
  storage/diemdb/src/schema/transaction_by_hash/test.rs
  storage/diemdb/src/schema/transaction_info/test.rs
  storage/diemdb/src/schema/write_set/test.rs
  storage/schemadb/Cargo.toml
  storage/schemadb/src/schema.rs
Labels: cla-signed

#9694 [forge] fix gas price test with extra coins per account
  crates/transaction-emitter/src/lib.rs
Labels: cla-signed

#9697 [storage] trivial: default to unimplemented!() to all DbReader/DbWrit…
  execution/executor/src/fuzzing.rs
  json-rpc/src/tests/utils.rs
  state-sync/storage-service/server/src/tests.rs
  storage/storage-client/src/lib.rs
  storage/storage-interface/src/lib.rs
  storage/storage-interface/src/mock.rs
Labels: cla-signed

#9698 [move-vm] separate error code for vector ops
  language/move-core/types/src/vm_status.rs
  language/move-stdlib/src/natives/vector.rs
  language/move-vm/transactional-tests/tests/builtins/vector_ops_out_of_bound.exp
  language/move-vm/transactional-tests/tests/builtins/vector_ops_pop_empty.exp
  language/move-vm/transactional-tests/tests/builtins/vector_ops_unpack_less.exp
  language/move-vm/transactional-tests/tests/builtins/vector_ops_unpack_more.exp
  language/move-vm/types/src/values/values_impl.rs
  language/tools/move-cli/src/sandbox/utils/mod.rs
Labels: cla-signed

#9554 [move-stdlib] Add basic ASCII string support to the Move Stdlib
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DPNFramework/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/bytecode_modules/ASCII.mv
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/docs/ASCII.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/docs/overview.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/source_maps/ASCII.mvsm
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/sources/ASCII.move
  diem-move/diem-framework/DPN/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/bytecode_modules/ASCII.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/docs/ASCII.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/source_maps/ASCII.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/sources/ASCII.move
  language/move-stdlib/docs/ASCII.md
  language/move-stdlib/docs/overview.md
  language/move-stdlib/error_description.errmap
  language/move-stdlib/sources/ASCII.move
  language/move-stdlib/tests/ASCIIStringTests.move
  language/tools/move-cli/tests/testsuite/package_basics/error_map.errmap
Labels: cla-signed

#9692 [api] enable api by default and change rest api and json-rpc to use same port
  api/Operation.md
  api/README.md
  config/src/config/api_config.rs
  diem-node/src/lib.rs
  docker/validator/Dockerfile
  shuffle/cli/src/shared.rs
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: cla-signed

#9702 [diem-framework] Move Vote module to experimental
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DPNFramework/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/abis/Vote/gc_ballots.abi
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/bytecode_modules/Vote.mv
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/docs/Vote.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/docs/overview.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/docs/script_documentation.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/source_maps/Vote.mvsm
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DiemCoreFramework/sources/Vote.move
  diem-move/diem-framework/DPN/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/DPN/releases/artifacts/current/transaction_script_builder.rs
  diem-move/diem-framework/experimental/sources/Vote.move
Labels: cla-signed

#9709 [GHA] Add forge repo for docker republish in ci-post-land
  .github/workflows/ci-post-land.yml
  docker/docker_republish.sh
  scripts/dockerhub_prune.sh
Labels: cla-signed

#9673 [read-write-set] Rename `read-write-set-types` to `move-read-write-set-types`
  Cargo.lock
  language/move-binary-format/Cargo.toml
  language/move-prover/bytecode/Cargo.toml
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/tools/read-write-set/Cargo.toml
  language/tools/read-write-set/dynamic/Cargo.toml
  language/tools/read-write-set/dynamic/src/dynamic_analysis.rs
  language/tools/read-write-set/dynamic/src/normalize.rs
  language/tools/read-write-set/src/lib.rs
  language/tools/read-write-set/types/Cargo.toml
Labels: tcb-deps-changed, deps-changed

#9713 [diem-framework] Move around files. Make packages testable
  Cargo.lock
  diem-move/diem-framework/Cargo.toml
  diem-move/diem-framework/README.md
  diem-move/diem-framework/core/tests/AccountFreezingTests.move
  diem-move/diem-framework/core/tests/AuthenticatorTests.move
  diem-move/diem-framework/core/tests/CRSNTests.move
  diem-move/diem-framework/core/tests/CurrenciesTests.move
  diem-move/diem-framework/core/tests/DiemConfigTests.move
  diem-move/diem-framework/core/tests/DiemTimestampTests.move
  diem-move/diem-framework/core/tests/DiemVersionTests.move
  diem-move/diem-framework/core/tests/RegisteredCurrencyTests.move
  diem-move/diem-framework/core/tests/RolesTests.move
  diem-move/diem-framework/core/tests/SignatureTests.move
  diem-move/diem-framework/core/tests/ValidatorConfigTests.move
  diem-move/diem-framework/core/tests/ValidatorOperatorConfigTests.move
  diem-move/diem-framework/experimental/tests/MultiTokenTests.move
  diem-move/diem-framework/experimental/tests/VoteTests.move
  diem-move/diem-framework/tests/move_unit_test.rs
  language/tools/move-cli/tests/testsuite/package_basics/args.exp
  language/tools/move-cli/tests/testsuite/package_basics/args.txt
  language/tools/move-package/src/lib.rs
Labels: cla-signed

#9728 forge: enable using custom genesis modules locally
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/local/mod.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/forge/src/interface/factory.rs
  testsuite/forge/src/runner.rs
Labels: cla-signed

#9748 [move-stdlib] GUID creation capability
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/bytecode_modules/GUID.mv
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/docs/GUID.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/source_maps/GUID.mvsm
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/sources/GUID.move
  diem-move/diem-framework/DPN/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/bytecode_modules/GUID.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/docs/GUID.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/source_maps/GUID.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/sources/GUID.move
  diem-move/diem-framework/experimental/releases/artifacts/current/error_description/error_description.errmap
  language/move-stdlib/docs/GUID.md
  language/move-stdlib/error_description.errmap
  language/move-stdlib/sources/GUID.move
  language/move-stdlib/tests/GUIDTests.move
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__account_limits__account_limits.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__crsn__can_opt_in_to_crsn.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__crsn__crsns_can_be_executed_out_of_order.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__crsn__crsns_prevent_replay_no_window_shift.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__crsn__crsns_prevent_replay_window_shift.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__crsn__force_expiration_of_crsns.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__multi_agent__multi_agent_mint.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__add_child_currencies.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_add_max_number.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__publish_and_register_new_currency.exp
  language/tools/move-cli/tests/testsuite/package_basics/error_map.errmap
Labels: cla-signed

#9746 [forge] Implemented AOS support and all missed features in txn_emitter
  Cargo.lock
  crates/transaction-emitter/Cargo.toml
  crates/transaction-emitter/src/cluster.rs
  crates/transaction-emitter/src/instance.rs
  crates/transaction-emitter/src/lib.rs
  crates/transaction-emitter/src/main.rs
Labels: cla-signed

#9758 [shuffle] test cmd loads correct key
  shuffle/cli/src/test.rs
Labels: cla-signed

#9761 [move-package] Fix issue where we werent' removing build artifacts between builds
  language/tools/move-package/src/compilation/build_plan.rs
  language/tools/move-package/src/compilation/compiled_package.rs
  language/tools/move-package/tests/test_removal_second_compilation.rs
  language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.compile
  language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.exp
  language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/Move.toml
  language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/sources/A.move
  language/tools/move-package/tests/test_sources/compilation/basic_no_deps_test_mode/sources/ATest.move
Labels: cla-signed

#9763 [experimental] Fix the release folders of experimental
  diem-move/diem-framework/experimental/DPN/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/DPN/releases/artifacts/current/transaction_script_builder.rs
  diem-move/diem-framework/experimental/experimental/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/experimental/releases/artifacts/current/transaction_script_builder.rs
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/bytecode_modules/NFTGallery.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/docs/NFTGallery.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/source_maps/NFTGallery.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/sources/NFTGallery.move
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/docs/FixedPoint32.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/source_maps/FixedPoint32.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/sources/FixedPoint32.move
Labels: cla-signed

#9778 [api] switch to stoplight/elements for rendering api doc, remove dependency on npx & redoc-cli for build
  .github/workflows/ci-post-land.yml
  api/Makefile
  api/build.rs
  api/doc/spec.html
  api/src/index.rs
  docker/build-common.sh
Labels: cla-signed

#9773 [move-package] Only hash Move and package-specific files
  diem-move/diem-framework/DPN/releases/artifacts/current/build/DPNFramework/BuildInfo.yaml
  language/tools/move-package/src/resolution/digest.rs
  language/tools/move-package/tests/package_hash_skips_non_move_files.rs
Labels: cla-signed

#9768 [experimental] check generated files up to date for experimental fram…
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/bytecode_modules/CRSN.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/docs/CRSN.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/docs/Vote.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/source_maps/CRSN.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/sources/CRSN.move
  diem-move/diem-framework/tests/generated_files.rs
Labels: cla-signed

#9752 [move-cli] Only print differences in changed resources during verbose…
  Cargo.lock
  diem-move/df-cli/tests/testsuite/diem_smoke/args.exp
  language/tools/move-cli/Cargo.toml
  language/tools/move-cli/src/sandbox/utils/mod.rs
  language/tools/move-cli/tests/testsuite/events_emit_view/args.exp
Labels: cla-signed, bors-squash

#9816 [vm-genesis] Implement a option to generate genesis with parallel exe…
  Cargo.lock
  config/management/genesis/src/builder.rs
  diem-move/vm-genesis/Cargo.toml
  diem-move/vm-genesis/src/lib.rs
  language/e2e-testsuite/src/tests/parallel_execution.rs
  language/testing-infra/e2e-tests/src/executor.rs
Labels: deps-changed

#9759 [move] Remove empty `;` statement from Move IR
  language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global.mvir
  language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global_invalid.mvir
  language/bytecode-verifier/transactional-tests/tests/reference_safety/imm_borrow_global_lossy_acquire_invalid.mvir
  language/ir-testsuite/tests/move/commands/if_branch_diverges_8.mvir
  language/move-ir-compiler/ir-to-bytecode/src/compiler.rs
  language/move-ir-compiler/ir-to-bytecode/syntax/src/syntax.rs
  language/move-ir/types/src/ast.rs
  language/move-vm/transactional-tests/tests/control_flow/if_branch_diverges_7.mvir
  language/move-vm/transactional-tests/tests/example_programs/sorted-linked-list.mvir
Labels: cla-signed

#9820 [api] update metrics operation doc
  api/Operation.md
Labels: cla-signed

#9790 [forge] Add reconfiguration test in forge
  Cargo.lock
  crates/transaction-emitter/src/lib.rs
  testsuite/forge-cli/src/main.rs
  testsuite/testcases/Cargo.toml
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/reconfiguration_test.rs
Labels: cla-signed

#9792 [experimental] Add an NFT example module with corresponding demo comm…
  Cargo.lock
  diem-move/diem-framework/experimental/Move.toml
  diem-move/diem-framework/experimental/demo-cli/Cargo.toml
  diem-move/diem-framework/experimental/demo-cli/bars_account.key
  diem-move/diem-framework/experimental/demo-cli/demo_commands.sh
  diem-move/diem-framework/experimental/demo-cli/src/main.rs
  diem-move/diem-framework/experimental/demo-cli/user_account1.key
  diem-move/diem-framework/experimental/demo-cli/user_account2.key
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/abis/BARS/mint_bars.abi
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/abis/BARS/register_bars_user.abi
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/bytecode_modules/BARSToken.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/docs/BARS.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/source_maps/BARSToken.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/sources/BARS.move
  diem-move/diem-framework/experimental/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/releases/artifacts/current/transaction_script_builder.rs
  diem-move/diem-framework/experimental/sources/BARS.move
  language/move-prover/tests/testsuite.rs
  sdk/transaction-builder/src/experimental_stdlib.rs
  sdk/transaction-builder/src/lib.rs
  shuffle/move/examples/main/context.ts
Labels: cla-signed

#9835 [move-cli] fix a compile error
  language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
Labels: cla-signed

#9842 [move package manager] document git dependencies
  language/documentation/book/src/packages.md
Labels: cla-signed

#9838 [README] fix broken links to documentation
  README.md
Labels: cla-signed

#9836 [tiny] Small additions to demo-cli
  diem-move/diem-framework/experimental/demo-cli/demo_commands.sh
  diem-move/diem-framework/experimental/demo-cli/root.key
  diem-move/diem-framework/experimental/demo-cli/tc.key
Labels: cla-signed

#9849 [State Sync] Add simple config for state sync driver.
  config/src/config/state_sync_config.rs
Labels: cla-signed

#9861 [shuffle] account creation uses random keys
  language/tools/move-package/src/source_package/manifest_parser.rs
  shuffle/cli/Cargo.toml
  shuffle/cli/new_account.key
  shuffle/cli/src/account.rs
  shuffle/cli/src/build.rs
  shuffle/cli/src/console.rs
  shuffle/cli/src/deploy.rs
  shuffle/cli/src/dev_api_client.rs
  shuffle/cli/src/main.rs
  shuffle/cli/src/new.rs
  shuffle/cli/src/node.rs
  shuffle/cli/src/shared.rs
  shuffle/cli/src/test.rs
  shuffle/cli/src/transactions.rs
  shuffle/integration-tests/src/helper.rs
  shuffle/integration-tests/src/lib.rs
  shuffle/move/examples/integration/helpers.test.ts
  shuffle/move/examples/main/Move.toml
Labels: cla-signed

#9854 Add support for printing in-scope named addresses and values from Move packages
  Cargo.lock
  common/workspace-hack/Cargo.toml
  language/tools/move-cli/src/package/cli.rs
  language/tools/move-cli/tests/testsuite/package_basics/args.exp
  language/tools/move-cli/tests/testsuite/package_basics/args.txt
  language/tools/move-package/Cargo.toml
  language/tools/move-package/src/resolution/resolution_graph.rs
Labels: cla-signed, tcb-deps-changed, deps-changed, bors-squash

#9883 easy: [shuffle] Fix repl_help.ts deno lint errors
  shuffle/move/examples/main/repl_help.ts
Labels: cla-signed

#9840 [api] inject fail points to each endpoint
  Cargo.lock
  api/Cargo.toml
  api/README.md
  api/src/accounts.rs
  api/src/events.rs
  api/src/failpoint.rs
  api/src/index.rs
  api/src/lib.rs
  api/src/transactions.rs
  diem-node/Cargo.toml
  testsuite/cluster-test/src/cluster_swarm/configs/fullnode.yaml
Labels: cla-signed

#9807 [move-prover] Upgrade Z3 version
  scripts/dev_setup.sh
Labels: cla-signed

#9890 Fix a typo
  developers.diem.com/docs/basics/basics-txns-states.md
Labels: cla-signed
