Repository diem/diem, pull requests merged in 2021-07, with the labels that each got.

#8672 [gha] use latest actions, enables gh issues for flaky tests detect in a single run.
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test-complete.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-update-sccache.yml
  .github/workflows/docker-publish.yml
Labels: cla-signed

#8674 [forge] init with cluster vault
  Cargo.lock
  docker/forge/Dockerfile
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
  testsuite/forge/src/main.rs
Labels: cla-signed

#8681 [move-vm-runtime] Improve logging around deserialization of modules
  language/move-vm/runtime/src/loader.rs
Labels: cla-signed

#8615 [language][move-cli] remove diem dependencies
  Cargo.lock
  Cargo.toml
  language/diem-tools/df-cli/Cargo.toml
  language/diem-tools/df-cli/src/main.rs
  language/diem-tools/df-cli/tests/cli_testsuite.rs
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/args.exp
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/args.txt
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/modules/NameService.move
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/modules/NonFungibleToken.move
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/modules/Set.move
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/modules/SimpleSortedLinkedList.move
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/modules/SortedLinkedList.move
  language/diem-tools/df-cli/tests/testsuite/compare_smoke/src/scripts/set.move
  language/diem-tools/df-cli/tests/testsuite/concretize_read_write_set_smoke/args.exp
  language/diem-tools/df-cli/tests/testsuite/concretize_read_write_set_smoke/args.txt
  language/diem-tools/df-cli/tests/testsuite/concretize_read_write_set_smoke/genesis.move
  language/diem-tools/df-cli/tests/testsuite/diem_read_write_set_smoke/args.exp
  language/diem-tools/df-cli/tests/testsuite/diem_read_write_set_smoke/args.txt
  language/diem-tools/df-cli/tests/testsuite/diem_read_write_set_smoke/src/modules/Dummy.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/args.exp
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/args.txt
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/genesis.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/scripts/create_child_vasp_account.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/scripts/create_designated_dealer.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/scripts/create_parent_vasp_account.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/scripts/peer_to_peer_with_metadata.move
  language/diem-tools/df-cli/tests/testsuite/diem_smoke/scripts/tiered_mint.move
  language/diem-tools/transaction-replay/src/lib.rs
  language/move-stdlib/Cargo.toml
  language/move-stdlib/error_description.errmap
  language/move-stdlib/src/lib.rs
  language/move-stdlib/src/main.rs
  language/move-stdlib/src/tests.rs
  language/move-vm/types/src/gas_schedule.rs
  language/tools/move-cli/Cargo.toml
  language/tools/move-cli/src/lib.rs
  language/tools/move-cli/src/main.rs
  language/tools/move-cli/src/sandbox/commands/publish.rs
  language/tools/move-cli/src/sandbox/commands/run.rs
  language/tools/move-cli/src/sandbox/utils/mod.rs
  language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
  language/tools/vm-genesis/src/genesis_gas_schedule.rs
  language/tools/vm-genesis/src/lib.rs
  x.toml
Labels: cla-signed

#8648 Cherry-pick PR #8646 into release-1.3: jsonrpc-types: add default unknown variants to various enums
  json-rpc/types/src/views.rs
Labels: cla-signed

#8649 jsonrpc-types: add default unknown variants to various enums
  json-rpc/types/src/views.rs
Labels: cla-signed

#8702 [move-lang][move-model] Gather used addresses, including in values
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/naming/translate.rs
  language/move-model/src/lib.rs
Labels: cla-signed

#8707 [gha] limit cargo audit log
  .github/workflows/daily.yml
Labels: cla-signed

#8715 Cherry-pick PR #8676 into release-1.3: [mempool] Prevent double decrements of upstream peers metric
  mempool/src/shared_mempool/peer_manager.rs
Labels: cla-signed

#8728 [dev_setup.sh] checks around golang/dotnet install
  scripts/dev_setup.sh
Labels: bors-high-priority, cla-signed

#8732 [move-prover][prover-lab] Create a z3 vs cvc5 basic experiment, nuke Rust-Jupyter-Book dependency
  language/move-prover/boogie-backend/src/boogie_wrapper.rs
  language/move-prover/boogie-backend/src/options.rs
  language/move-prover/boogie-backend/src/prover_task_runner.rs
  language/move-prover/lab/data/cvc/README.md
  language/move-prover/lab/data/cvc/experiments/cvc_boogie_array.fun_data
  language/move-prover/lab/data/cvc/experiments/cvc_boogie_array.mod_data
  language/move-prover/lab/data/cvc/experiments/cvc_boogie_array.toml
  language/move-prover/lab/data/cvc/experiments/z3_boogie_array.fun_data
  language/move-prover/lab/data/cvc/experiments/z3_boogie_array.mod_data
  language/move-prover/lab/data/cvc/experiments/z3_boogie_array.toml
  language/move-prover/lab/data/cvc/fun_by_fun.svg
  language/move-prover/lab/data/cvc/mod_by_mod.svg
  language/move-prover/lab/data/cvc/plot.sh
  language/move-prover/lab/data/cvc/run.sh
  language/move-prover/lab/src/benchmark.rs
  language/move-prover/lab/src/lib.rs
  language/move-prover/lab/src/main.rs
  language/move-prover/lab/src/plot.rs
Labels: cla-signed

#8745 [move-prover] make Verification variant taking a flavor enum
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/function_target_pipeline.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/interpreter/src/shared/variant.rs
Labels: cla-signed

#8735 [move] Extract bytecode-verifier test helper
  language/bytecode-verifier/bytecode-verifier-tests/src/lib.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/support/mod.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs
  language/move-binary-format/src/file_format.rs
Labels: bors-high-priority, cla-signed

#8712 [move] Remove `Compiled{Script,Module}::freeze`
  Cargo.lock
  language/bytecode-verifier/bytecode-verifier-tests/src/support/mod.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/constants_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/duplication_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
  language/bytecode-verifier/src/verifier.rs
  language/compiler/ir-to-bytecode/src/compiler.rs
  language/diem-tools/writeset-transaction-generator/Cargo.toml
  language/diem-tools/writeset-transaction-generator/src/release_flow/mod.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/unit_tests/release_tests.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/verify.rs
  language/move-binary-format/src/deserializer.rs
  language/move-binary-format/src/file_format.rs
  language/move-binary-format/src/proptest_types.rs
  language/move-model/src/lib.rs
  language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
  language/testing-infra/module-generation/src/generator.rs
  language/testing-infra/test-generation/src/abstract_state.rs
  language/testing-infra/test-generation/src/lib.rs
Labels: cla-signed

#8770 client: increase wait_for_transaction timeout
  sdk/client/src/blocking.rs
  sdk/client/src/client.rs
Labels: cla-signed

#8764 [move-cli] Refactor move-cli to make it extensible
  Cargo.lock
  language/diem-tools/df-cli/Cargo.toml
  language/diem-tools/df-cli/src/main.rs
  language/tools/move-cli/src/lib.rs
Labels: cla-signed

#8779 [genesis] support publishing modules that use the friend feature in g…
  language/tools/vm-genesis/src/lib.rs
Labels: cla-signed

#8791 [move-lang] Remove old error reporting
  Cargo.lock
  language/diem-tools/transaction-replay/src/lib.rs
  language/move-lang/Cargo.toml
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/cfgir/absint.rs
  language/move-lang/src/cfgir/borrows/mod.rs
  language/move-lang/src/cfgir/borrows/state.rs
  language/move-lang/src/cfgir/cfg.rs
  language/move-lang/src/cfgir/liveness/mod.rs
  language/move-lang/src/cfgir/locals/mod.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/command_line/compiler.rs
  language/move-lang/src/compiled_unit.rs
  language/move-lang/src/diagnostics/codes.rs
  language/move-lang/src/diagnostics/mod.rs
  language/move-lang/src/errors/mod.rs
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/expansion/byte_string.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/hex_string.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/parser/comments.rs
  language/move-lang/src/parser/lexer.rs
  language/move-lang/src/parser/mod.rs
  language/move-lang/src/parser/syntax.rs
  language/move-lang/src/shared/mod.rs
  language/move-lang/src/to_bytecode/context.rs
  language/move-lang/src/typing/core.rs
  language/move-lang/src/typing/globals.rs
  language/move-lang/src/typing/infinite_instantiations.rs
  language/move-lang/src/typing/recursive_structs.rs
  language/move-lang/src/typing/translate.rs
  language/move-lang/src/unit_test/filter_test_members.rs
  language/move-lang/src/unit_test/mod.rs
  language/move-lang/src/unit_test/plan_builder.rs
  language/move-lang/tests/move_check_testsuite.rs
  language/move-model/src/lib.rs
  language/tools/move-unit-test/src/lib.rs
  language/tools/move-unit-test/src/test_reporter.rs
  language/tools/move-unit-test/tests/test_sources/cross_module_aborts.exp
  language/tools/move-unit-test/tests/test_sources/missing_data.exp
  language/tools/move-unit-test/tests/test_sources/native_signer_creation.exp
  language/tools/move-unit-test/tests/test_sources/native_signer_creation.storage.exp
  language/tools/move-unit-test/tests/test_sources/proposal_test.exp
  language/tools/move-unit-test/tests/test_sources/proposal_test.storage.exp
  language/tools/move-unit-test/tests/test_sources/signer_args.exp
  language/tools/move-unit-test/tests/test_sources/storage_on_error_empty_and_non_empty.exp
  language/tools/move-unit-test/tests/test_sources/storage_on_error_empty_and_non_empty.storage.exp
  language/tools/move-unit-test/tests/test_sources/timeout.exp
  language/tools/move-unit-test/tests/test_sources/unexpected_abort.exp
Labels: cla-signed

#8788 [diem-framework] Add support for unit testing in the Diem Framework
  Cargo.lock
  language/diem-framework/Cargo.toml
  language/diem-framework/modules/AccountFreezing.move
  language/diem-framework/modules/Genesis.move
  language/diem-framework/modules/doc/Genesis.md
  language/diem-framework/releases/artifacts/current/docs/modules/Genesis.md
  language/diem-framework/releases/artifacts/current/modules/Genesis.mv
  language/diem-framework/src/natives/mod.rs
  language/diem-framework/tests/AccountFreezingTests.move
  language/diem-framework/tests/move_unit_test.rs
  language/diem-vm/src/natives.rs
  language/move-lang/functional-tests/tests/diem/diem_account/freezing.move
  language/move-prover/interpreter-testsuite/tests/concrete_check_testsuite.rs
  language/move-stdlib/src/natives/mod.rs
  language/move-vm/runtime/src/native_functions.rs
  language/tools/move-unit-test/src/cargo_runner.rs
  language/tools/move-unit-test/src/lib.rs
  language/tools/move-unit-test/src/main.rs
  language/tools/move-unit-test/src/test_runner.rs
  language/tools/move-unit-test/tests/move_unit_test_testsuite.rs
Labels: cla-signed

#8805 [docker] debian baseimage update
  docker/ci/github/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/faucet/Dockerfile
  docker/forge/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#8818 [gha] work around very large logs sent to slack by prover daily tests.
  .github/actions/slack-file/message_file_to_slack.sh
Labels: cla-signed

#8813 [move-vm] improve the code loading logic
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/runtime.rs
Labels: cla-signed

#8823 [move-prover] Initial cut of tech report.
  language/move-prover/doc/report/arch.png
  language/move-prover/doc/report/arch.tex
  language/move-prover/doc/report/biblio.bib
  language/move-prover/doc/report/formal.tex
  language/move-prover/doc/report/injection.tex
  language/move-prover/doc/report/intro.tex
  language/move-prover/doc/report/macros.tex
  language/move-prover/doc/report/main.pdf
  language/move-prover/doc/report/main.tex
  language/move-prover/doc/report/move.tex
  language/move-prover/doc/report/references.tex
  language/move-prover/doc/report/translation.tex
Labels: cla-signed

#8833 [move] Nits from #8789
  language/move-binary-format/src/normalized.rs
Labels: cla-signed

#8831 [prover] Tech report: Function specification injection
  language/move-prover/doc/report/injection.tex
  language/move-prover/doc/report/macros.tex
  language/move-prover/doc/report/main.pdf
  language/move-prover/doc/report/references.tex
Labels: cla-signed

#8810 [ci] add ci action to post depdive update report on PR
  .github/workflows/dep-update-review.yml
Labels: cla-unsigned

#8837 [move-prover] Tech report: data invariants
  language/move-prover/doc/report/injection.tex
  language/move-prover/doc/report/main.pdf
Labels: cla-signed

#8828 [gha] run transaction-replay test on weekly
  .github/workflows/daily.yml
  .github/workflows/weekly.yml
Labels: cla-signed

#8840 [move-prover] Fix an inconsistency in global invariant processing
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
  language/move-prover/bytecode/src/verification_analysis_v2.rs
Labels: cla-signed

#8832 [move-vm] refactor the module loading logic
  language/move-vm/runtime/src/loader.rs
Labels: cla-signed

#8841 [move-prover] Tech report: global invariants first take
  language/move-prover/doc/report/injection.tex
  language/move-prover/doc/report/main.pdf
  language/move-prover/doc/report/main.tex
  language/move-prover/doc/report/mono.tex
  language/move-prover/doc/report/references.tex
  language/move-prover/doc/report/translation.tex
Labels: cla-signed
