Repository diem/diem, pull requests merged in 2021-03, with the labels that each got.

#7743 [Vault Storage] Reduce default timeouts and support custom timeouts for operator tooling
  config/management/src/secure_backend.rs
  secure/storage/vault/src/lib.rs
Labels: cla-signed

#7772 [move-prover] Use $Mutation as parameters instead of converting to $Value and back
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/clean_and_optimize.rs
  language/move-prover/bytecode/src/eliminate_mut_refs.rs
  language/move-prover/bytecode/src/function_data_builder.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/mut_ref_instrumentation.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/bytecode/src/reaching_def_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/spec_translator.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/bytecode/tests/borrow/basic_test.exp
  language/move-prover/bytecode/tests/borrow/pack_unpack.exp
  language/move-prover/bytecode/tests/clean_and_optimize/pack_unpack.exp
  language/move-prover/bytecode/tests/data_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/data_invariant_instrumentation/params.exp
  language/move-prover/bytecode/tests/eliminate_mut_refs/mut_ref_unpack.exp
  language/move-prover/bytecode/tests/eliminate_mut_refs/mut_ref_unpack.move
  language/move-prover/bytecode/tests/global_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/update.exp
  language/move-prover/bytecode/tests/livevar/basic_test.exp
  language/move-prover/bytecode/tests/livevar/mut_ref_unpack.exp
  language/move-prover/bytecode/tests/memory_instr/basic_test.exp
  language/move-prover/bytecode/tests/memory_instr/mut_ref.exp
  language/move-prover/bytecode/tests/mut_ref_instrumentation/basic_test.exp
  language/move-prover/bytecode/tests/mut_ref_instrumentation/basic_test.move
  language/move-prover/bytecode/tests/reaching_def/basic_test.exp
  language/move-prover/bytecode/tests/reaching_def/mut_ref_unpack.exp
  language/move-prover/bytecode/tests/reaching_def/test_branching.exp
  language/move-prover/bytecode/tests/spec_instrumentation/fun_spec.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
  language/move-prover/src/pipelines.rs
  language/move-prover/src/prelude.bpl
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/loops.exp
  language/move-prover/tests/sources/functional/references.exp
  language/move-prover/tests/sources/functional/references.move
  language/move-prover/tests/sources/functional/simple_vector_client.move
Labels: cla-signed

#7687 [mempool] Add SharedMempool GCing for non-validator peers
  mempool/src/shared_mempool/peer_manager.rs
Labels: cla-signed, mempool

#7799 [tests][move-lang] Reduce move_check_testsuite time by 97%
  language/move-lang/test-utils/src/lib.rs
  language/move-lang/tests/move_check/typing/global_builtins_script.exp
  language/move-lang/tests/move_check/typing/global_builtins_script.move
  language/move-lang/tests/move_check_testsuite.rs
Labels: cla-signed

#7788 [testnet] support a template config for testnet
  diem-node/src/lib.rs
  docker/compose/validator-testnet/docker-compose.yaml
  docker/compose/validator-testnet/validator_node_template.yaml
Labels: cla-signed

#7802 [docker-compose] Check docker logs separately to prevent race condition
  docker/compose/test_docker_compose.sh
Labels: cla-signed

#7762 [specifications] minor fixes and updates to the Move adapter spec
  specifications/move_adapter/README.md
Labels: cla-signed

#7796 [backup] update sample configs
  storage/backup/backup-cli/src/storage/command_adapter/azure.sample.toml
  storage/backup/backup-cli/src/storage/command_adapter/gcp.sample.toml
  storage/backup/backup-cli/src/storage/command_adapter/s3.sample.toml
Labels: cla-signed

#7806 ci: add transaction replay daily job for compatibility testing
  .github/workflows/daily.yml
  .github/workflows/transaction-replay.toml
Labels: cla-signed

#7794 [gha] e2e tests should have messages pushed on e2e test failures
  .github/workflows/ci-test.yml
Labels: cla-signed

#7745 [helm][gha] pfn helm chart test
  .github/workflows/ci-test.yml
  helm/fullnode/templates/tests/test-fullnode-connection.yaml
Labels: cla-signed

#7814 [move-prover] changed name of join function of "joinresult"
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/dataflow_analysis.rs
Labels: bors-squash, cla-signed

#7822 [helm] sync STRUCT_LOG_TCP_ADDR and azure config for backup
  helm/fullnode/files/backup/azure.toml
  helm/fullnode/templates/_helpers.tpl
  helm/fullnode/templates/backup-verify.yaml
  helm/fullnode/templates/backup.yaml
  helm/fullnode/templates/restore.yaml
Labels: cla-signed

#7807 [backup] metadata cache: download to tmp file then rename
  storage/backup/backup-cli/src/metadata/cache.rs
Labels: cla-signed

#7831 Fixes inadvertent change in Coin address
  developers.diem.com/docs/move/creating-coins.md
Labels: cla-signed

#7829 [docker] Add writeset tools into docker image
  docker/build-common.sh
  docker/tools/Dockerfile
Labels: cla-signed

#7821 [GHA] Added build-images step into ci-test workflow
  .github/workflows/ci-test.yml
  .github/workflows/docker-publish.yml
Labels: cla-signed

#7842 [tcb][safety_rules] added state machine specification
  specifications/trusted_computing_base/safety_rules/README.md
Labels: cla-signed

#7825 [deps] update transitive deps
  Cargo.lock
  common/logger/Cargo.toml
  common/metrics-core/Cargo.toml
  common/metrics/Cargo.toml
  common/workspace-hack/Cargo.toml
Labels: cla-signed, deps-changed, tcb-deps-changed

#7828 [Secure Storage] Vault timeout workaround due to ureq bug.
  secure/storage/vault/src/lib.rs
Labels: cla-signed

#7871 ci: ensure that workflows run on main
  .github/actions/land-blocking/find-lbt-images.sh
  .github/workflows/ci-update-sccache.yml
  .github/workflows/daily.yml
  .github/workflows/developer-site-ci.yml
  .github/workflows/docker-publish.yml
  .github/workflows/rustdoc.yml
Labels: cla-signed

#7859 [doc] fix broken link in execution_correctness spec
  specifications/trusted_computing_base/execution_correctness/README.md
Labels: cla-signed

#7879 [doc] update my-first-client doc to rename libra to diem
  developers.diem.com/docs/core/my-first-client.md
Labels: cla-signed

#7881 [gha][lbt] fix typo in trigger condition
  .github/workflows/land-blocking.yml
Labels: cla-signed

#7880 [diem-framework] Updated the emits spec in the Diem Framework
  language/diem-framework/modules/Diem.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/emits.move
Labels: cla-signed

#7891 [diemdb-bench] add reads/bytes_written
  Cargo.lock
  storage/diemdb-benchmark/Cargo.toml
  storage/diemdb-benchmark/src/lib.rs
  storage/jellyfish-merkle/Cargo.toml
  storage/jellyfish-merkle/src/lib.rs
  storage/jellyfish-merkle/src/metrics.rs
  storage/jellyfish-merkle/src/node_type/mod.rs
  storage/jellyfish-merkle/src/tree_cache/mod.rs
Labels: cla-signed

#7810 [move-lang] cyclic dependency checking for friends
  language/move-lang/src/naming/uses.rs
  language/move-lang/tests/move_check/dependencies/friend_cycle_2.exp
  language/move-lang/tests/move_check/dependencies/friend_cycle_2.move
  language/move-lang/tests/move_check/dependencies/friend_cycle_3.exp
  language/move-lang/tests/move_check/dependencies/friend_cycle_3.move
  language/move-lang/tests/move_check/dependencies/intersecting_friend_cycles.exp
  language/move-lang/tests/move_check/dependencies/intersecting_friend_cycles.move
  language/move-lang/tests/move_check/dependencies/intersecting_use_cycles.exp
  language/move-lang/tests/move_check/dependencies/intersecting_use_cycles.move
  language/move-lang/tests/move_check/dependencies/multiple_friend_cycles.exp
  language/move-lang/tests/move_check/dependencies/multiple_friend_cycles.move
  language/move-lang/tests/move_check/dependencies/multiple_use_cycles.exp
  language/move-lang/tests/move_check/dependencies/multiple_use_cycles.move
  language/move-lang/tests/move_check/dependencies/use_cycle_2.exp
  language/move-lang/tests/move_check/dependencies/use_cycle_2.move
  language/move-lang/tests/move_check/dependencies/use_cycle_3.exp
  language/move-lang/tests/move_check/dependencies/use_cycle_3.move
  language/move-lang/tests/move_check/dependencies/use_friend_direct.exp
  language/move-lang/tests/move_check/dependencies/use_friend_direct.move
  language/move-lang/tests/move_check/dependencies/use_friend_transitive_by_friend.exp
  language/move-lang/tests/move_check/dependencies/use_friend_transitive_by_friend.move
  language/move-lang/tests/move_check/dependencies/use_friend_transitive_by_use.exp
  language/move-lang/tests/move_check/dependencies/use_friend_transitive_by_use.move
Labels: cla-signed

#7895 [x] upgrade to guppy 0.9.0
  Cargo.lock
  devtools/x-core/Cargo.toml
  devtools/x-lint/Cargo.toml
  devtools/x/Cargo.toml
  devtools/x/src/lint/guppy.rs
  devtools/x/src/lint/workspace_classify.rs
Labels: cla-signed

#7896 [move-lang] propogate friend list to bytecode
  language/move-lang/src/cfgir/ast.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/hlir/ast.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/to_bytecode/context.rs
  language/move-lang/src/to_bytecode/translate.rs
  language/move-lang/src/typing/translate.rs
Labels: cla-signed

#7913 [move-prover] Add a check that opaque functions specs use modifies correctly.
  language/diem-framework/modules/DesignatedDealer.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/DiemConfig.move
  language/diem-framework/modules/DiemSystem.move
  language/diem-framework/modules/SlidingNonce.move
  language/diem-framework/modules/doc/DesignatedDealer.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/modules/doc/DiemConfig.md
  language/diem-framework/modules/doc/DiemSystem.md
  language/diem-framework/modules/doc/SlidingNonce.md
  language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
  language/diem-framework/transaction_scripts/preburn.move
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/tests/sources/functional/ModifiesTypeTest.exp
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#7867 [move-prover] add strong edges for vector writebacks
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/src/prelude.bpl
Labels: bors-squash, cla-signed

#7917 [State Sync] Ignore flaky tests and add a warning.
  state-sync/tests/integration_tests.rs
Labels: cla-signed

#7914 executor-benchmark: print accumulative tps
  execution/executor-benchmark/src/lib.rs
Labels: cla-signed

#7848 [move-lang-functional-tests] Reduce test time by 60%
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/cfgir/ast.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/compiled_unit.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/hlir/ast.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/naming/ast.rs
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/to_bytecode/translate.rs
  language/move-lang/src/typing/ast.rs
  language/move-lang/src/typing/core.rs
  language/move-lang/src/typing/translate.rs
  language/move-model/src/lib.rs
Labels: cla-signed

#7887 x: add guppy lint to prevent move crates from depending on diem ones
  devtools/x/src/config.rs
  devtools/x/src/lint/guppy.rs
  devtools/x/src/lint/mod.rs
  x.toml
Labels: cla-signed

#7921 [ci] json-rpc compat test through cluster-test
  .github/workflows/daily.yml
Labels: cla-signed

#7889 [move-prover] Implemented the feature of automatic inconsistency checking
  language/move-prover/boogie-backend/src/boogie_wrapper.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/function_target_pipeline.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/src/cli.rs
  language/move-prover/tests/sources/functional/inconsistency.exp
  language/move-prover/tests/sources/functional/inconsistency.move
  scripts/dev_setup.sh
Labels: cla-signed

#7932 [datatest-stable] support --format terse
  common/datatest-stable/src/runner.rs
Labels: cla-signed

#7933 [move prover][diem framework] fix timeouts in DiemAccount and preburn script
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
  language/diem-framework/transaction_scripts/preburn.move
Labels: cla-signed

#7901 [move-model] expose friend info to move model
  language/move-model/src/model.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/memory_instrumentation.rs
  language/move-prover/docgen/Cargo.toml
Labels: cla-signed

#7941 [backup] update local_folder.sample.toml
  storage/backup/backup-cli/src/storage/command_adapter/local_folder.sample.toml
Labels: cla-signed

#7940 [backup] metadata cache defaults to temp dir
  storage/backup/backup-cli/Cargo.toml
  storage/backup/backup-cli/src/metadata/cache.rs
Labels: cla-signed

#7845 [specifications] minor fixes to the move_adapter spec
  specifications/move_adapter/README.md
Labels: cla-signed

#7800 Cherry-pick PR #7060 into release-1.1: [state-sync][bug-fix] removing integer overflow
  state-synchronizer/src/executor_proxy.rs
  state-synchronizer/src/tests/helpers.rs
Labels: cla-signed

#7950 [diem-framework] fix some broken specs
  language/diem-framework/modules/DesignatedDealer.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/doc/DesignatedDealer.md
  language/diem-framework/modules/doc/DiemAccount.md
Labels: cla-signed

#7953 executor benchmark: report total vm/executor/commit time
  execution/executor-benchmark/src/lib.rs
  execution/executor/src/lib.rs
Labels: cla-signed

#7955 [language] remove unused file in diem-framework
  language/diem-framework/src/utils.rs
Labels: cla-signed

#7956 [x] add determinator rules for move-prover
  x.toml
Labels: cla-signed

#7971 [move-prover] Remove now obsolete hack to work around deps problem.
  language/move-model/src/lib.rs
  language/move-prover/bytecode/tests/from_move/regression_generic_and_native_type.exp
Labels: cla-signed

#7968 [diem-framework] Fixed the inconsistency in the verification of `txn::burn_txn_fees` and `TransactionFee::burn_fees`
  language/diem-framework/modules/XDX.move
  language/diem-framework/modules/doc/XDX.md
Labels: cla-signed, diem-framework, move-prover

#7969 [language] remove diem-types dependency from bytecode-verifier
  Cargo.lock
  language/bytecode-verifier/Cargo.toml
  language/bytecode-verifier/src/ability_field_requirements.rs
  language/bytecode-verifier/src/acquires_list_verifier.rs
  language/bytecode-verifier/src/binary_views.rs
  language/bytecode-verifier/src/check_duplication.rs
  language/bytecode-verifier/src/constants.rs
  language/bytecode-verifier/src/control_flow.rs
  language/bytecode-verifier/src/cyclic_dependencies.rs
  language/bytecode-verifier/src/dependencies.rs
  language/bytecode-verifier/src/friends.rs
  language/bytecode-verifier/src/instantiation_loops.rs
  language/bytecode-verifier/src/instruction_consistency.rs
  language/bytecode-verifier/src/locals_safety/mod.rs
  language/bytecode-verifier/src/reference_safety/abstract_state.rs
  language/bytecode-verifier/src/script_signature.rs
  language/bytecode-verifier/src/signature.rs
  language/bytecode-verifier/src/stack_usage_verifier.rs
  language/bytecode-verifier/src/struct_defs.rs
  language/bytecode-verifier/src/type_safety.rs
  x.toml
Labels: cla-signed

#7972 [language] remove diem-types dependency from bytecode-verifier-tests and invalid-mutations
  Cargo.lock
  language/bytecode-verifier/bytecode-verifier-tests/Cargo.toml
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/code_unit_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/constants_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/control_flow_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/negative_stack_size_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
  language/bytecode-verifier/invalid-mutations/Cargo.toml
  language/bytecode-verifier/invalid-mutations/src/bounds.rs
  language/bytecode-verifier/invalid-mutations/src/bounds/code_unit.rs
  x.toml
Labels: cla-signed

#7970 [tests] kill child processes on exit
  consensus/safety-rules/tests/binary.rs
  execution/execution-correctness/tests/binary.rs
Labels: cla-signed

#7976 [language] remove diem-types dependencies from move-ir-types
  Cargo.lock
  language/move-ir/types/Cargo.toml
  language/move-ir/types/src/ast.rs
  language/move-ir/types/src/spec_language_ast.rs
  x.toml
Labels: cla-signed

#7987 [language] remove diem-types dependencies from move-lang
  Cargo.lock
  language/move-lang/Cargo.toml
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/to_bytecode/context.rs
  language/move-lang/src/to_bytecode/translate.rs
  x.toml
Labels: cla-signed

#7990 [language] remove unused diem-types dependencies from a few prover crates
  Cargo.lock
  language/move-model/Cargo.toml
  language/move-prover/Cargo.toml
  language/move-prover/boogie-backend/Cargo.toml
  language/move-prover/errmapgen/Cargo.toml
  x.toml
Labels: cla-signed

#7986 [move-prover] Corrects the default "--cores" value displayed in the help message
  language/move-prover/src/cli.rs
Labels: cla-signed

#7982 [dependencies] disable rust dependabot
  .github/dependabot.yml
Labels: cla-signed

#8011 [ci] add RUSTSEC-2020-0146 to nightly ignore list
  .github/workflows/daily.yml
Labels: cla-signed

#8007 Add sdk versions to prometheus
  json-rpc/src/counters.rs
  json-rpc/src/fuzzing.rs
  json-rpc/src/runtime.rs
  json-rpc/src/tests/unit_tests.rs
  json-rpc/src/util.rs
Labels: cla-signed

#8012 [move cli] specify `main` branch in `cargo install --git` command
  language/tools/move-cli/README.md
Labels: cla-signed

#8014 [move-prover] Remove the crate `diagen`
  Cargo.lock
  Cargo.toml
  language/move-prover/diagen/Cargo.toml
  language/move-prover/diagen/README.md
  language/move-prover/diagen/diagrams/convert_all_dot_to_pdf.sh
  language/move-prover/diagen/diagrams/convert_all_dot_to_svg.sh
  language/move-prover/diagen/src/main.rs
Labels: cla-signed

#7984 [move-prover] Add the `MVP_TEST_INCONSISTENCY` to `cargo test -p move-prover`
  language/move-prover/tests/README.md
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#7998 [proof-of-solvency] Add diem-assets-proof CLI tool
  Cargo.lock
  Cargo.toml
  client/assets-proof/Cargo.toml
  client/assets-proof/src/lib.rs
  client/assets-proof/src/main.rs
Labels: cla-signed

#8015 [scratchpad] fix clowntown
  storage/scratchpad/src/sparse_merkle/mod.rs
  storage/scratchpad/src/sparse_merkle/node.rs
Labels: cla-signed

#7997 [GHA]Merge LBT workflow into ci-test workflow
  .github/actions/changes/action.yml
  .github/actions/changes/get_pr_info.sh
  .github/workflows/README.md
  .github/workflows/ci-test.yml
  .github/workflows/docker-publish.yml
  .github/workflows/land-blocking.yml
  docker/build-aws.sh
Labels: cla-signed

#7985 Create Broadcast Client 2
  Cargo.lock
  client/json-rpc/Cargo.toml
  client/json-rpc/src/broadcast_client.rs
  client/json-rpc/src/lib.rs
  sdk/client/src/client.rs
  sdk/client/src/request.rs
Labels: bors-squash, cla-signed

#7947 [network] Drop incoming self dials
  network/src/peer_manager/mod.rs
Labels: cla-signed, network

#8022 [RPC][Metrics] Add SDK language + version to prometheus metrics
  Cargo.lock
  json-rpc/Cargo.toml
  json-rpc/src/counters.rs
  json-rpc/src/runtime.rs
  json-rpc/src/tests/unit_tests.rs
  json-rpc/src/util.rs
Labels: cla-signed

#8024 [move-prover] turning strong edges on by default in borrow analysis
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/pipelines.rs
Labels: bors-squash, cla-signed

#8027 [move-prover] Add the Prover inconsistency test to the daily test routine
  .github/workflows/daily.yml
Labels: cla-signed

#8036 [move cli] better documentation for `--args` syntax
  language/tools/move-cli/README.md
  language/tools/move-cli/src/main.rs
Labels: cla-signed

#8006 [move-prover] functional tests for strong edges
  language/move-prover/tests/sources/functional/strong_edges.exp
  language/move-prover/tests/sources/functional/strong_edges.move
Labels: bors-squash, cla-signed

#8037 [GHA] remove deprecated LBT workflow
  .github/workflows/land-blocking.yml
Labels: cla-signed

#8025 AssetsProof readme
  client/assets-proof/src/README.md
Labels: cla-signed

#7983 [json-rpc] get_account by version
  client/assets-proof/src/lib.rs
  json-rpc/API-CHANGELOG.md
  json-rpc/docs/method_get_account.md
  json-rpc/docs/type_account.md
  json-rpc/src/methods.rs
  json-rpc/src/tests/unit_tests.rs
  json-rpc/tests/integration_test.rs
  json-rpc/types/src/proto/jsonrpc.proto
  json-rpc/types/src/views.rs
Labels: cla-signed

#7973 [type] switch to BCS bytes for txn args for the script function payload
  client/transaction-builder/src/stdlib.rs
  json-rpc/API-CHANGELOG.md
  json-rpc/docs/type_transaction.md
  json-rpc/src/util.rs
  json-rpc/tests/integration_test.rs
  json-rpc/types/src/proto/jsonrpc.proto
  json-rpc/types/src/views.rs
  language/diem-vm/src/diem_transaction_executor.rs
  language/transaction-builder/generator/src/common.rs
  language/transaction-builder/generator/src/cpp.rs
  language/transaction-builder/generator/src/csharp.rs
  language/transaction-builder/generator/src/golang.rs
  language/transaction-builder/generator/src/java.rs
  language/transaction-builder/generator/src/python3.rs
  language/transaction-builder/generator/src/rust.rs
  language/transaction-builder/generator/src/typescript.rs
  language/transaction-builder/generator/tests/cli.rs
  language/transaction-builder/generator/tests/generation.rs
  testsuite/generate-format/tests/staged/consensus.yaml
  testsuite/generate-format/tests/staged/diem.yaml
  types/src/lib.rs
  types/src/serde_helper/mod.rs
  types/src/serde_helper/vec_bytes.rs
  types/src/transaction/mod.rs
  types/src/transaction/script.rs
Labels: bors-squash, cla-signed

#8041 [move-prover] add edge information to writeback instruction printing
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/bytecode/tests/clean_and_optimize/pack_unpack.exp
  language/move-prover/bytecode/tests/data_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/update.exp
  language/move-prover/bytecode/tests/memory_instr/basic_test.exp
  language/move-prover/bytecode/tests/memory_instr/mut_ref.exp
  language/move-prover/bytecode/tests/spec_instrumentation/fun_spec.exp
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
Labels: bors-squash, cla-signed

#8050 [diem framework] Fix some links in script docs, make explanations clearer
  client/transaction-builder/src/stdlib.rs
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/add_currency_to_account.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/add_recovery_rotation_capability.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/create_recovery_address.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/publish_shared_ed25519_public_key.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_authentication_key.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_authentication_key_with_nonce.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_authentication_key_with_nonce_admin.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_authentication_key_with_recovery_address.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_dual_attestation_info.abi
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_shared_ed25519_public_key.abi
  language/diem-framework/compiled/script_abis/AccountCreationScripts/create_child_vasp_account.abi
  language/diem-framework/compiled/script_abis/AccountCreationScripts/create_designated_dealer.abi
  language/diem-framework/compiled/script_abis/AccountCreationScripts/create_parent_vasp_account.abi
  language/diem-framework/compiled/script_abis/AccountCreationScripts/create_validator_account.abi
  language/diem-framework/compiled/script_abis/AccountCreationScripts/create_validator_operator_account.abi
  language/diem-framework/compiled/script_abis/PaymentScripts/peer_to_peer_with_metadata.abi
  language/diem-framework/compiled/script_abis/SystemAdministrationScripts/update_diem_version.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/burn_txn_fees.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/burn_with_amount.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/cancel_burn_with_amount.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/freeze_account.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/preburn.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/tiered_mint.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/unfreeze_account.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/update_dual_attestation_limit.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/update_exchange_rate.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/update_minting_ability.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/add_validator_and_reconfigure.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/register_validator_config.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/remove_validator_and_reconfigure.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/set_validator_config_and_reconfigure.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/set_validator_operator.abi
  language/diem-framework/compiled/script_abis/ValidatorAdministrationScripts/set_validator_operator_with_nonce_admin.abi
  language/diem-framework/modules/AccountAdministrationScripts.move
  language/diem-framework/modules/AccountCreationScripts.move
  language/diem-framework/modules/PaymentScripts.move
  language/diem-framework/modules/SystemAdministrationScripts.move
  language/diem-framework/modules/TreasuryComplianceScripts.move
  language/diem-framework/modules/ValidatorAdministrationScripts.move
  language/diem-framework/modules/doc/AccountAdministrationScripts.md
  language/diem-framework/modules/doc/AccountCreationScripts.md
  language/diem-framework/modules/doc/PaymentScripts.md
  language/diem-framework/modules/doc/SystemAdministrationScripts.md
  language/diem-framework/modules/doc/TreasuryComplianceScripts.md
  language/diem-framework/modules/doc/ValidatorAdministrationScripts.md
  language/diem-framework/script_documentation/script_documentation.md
  language/diem-framework/script_documentation/script_documentation_template.md
Labels: bors-squash, cla-signed

#8049 [move-lang] Don't coalesce loop heads for the move-prover
  language/move-lang/src/cfgir/ast.rs
  language/move-lang/src/cfgir/cfg.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/to_bytecode/remove_fallthrough_jumps.rs
  language/move-lang/src/to_bytecode/translate.rs
Labels: cla-signed

#8052 [dev docs] fix typo in global storage docs
  developers.diem.com/docs/move/global-storage-structure.md
  developers.diem.com/docs/move/overview.md
Labels: cla-signed

#8046 initial transfer transaction spec
  specifications/transactions/README.md
Labels: cla-signed

#8069 [move prover] support verifying only one function
  language/move-model/src/model.rs
  language/move-prover/bytecode/src/verification_analysis.rs
  language/move-prover/src/cli.rs
Labels: cla-signed

#8070 [diem-framework] Updated the access control specs in the Diem Framework
  language/diem-framework/modules/AccountLimits.move
  language/diem-framework/modules/doc/AccountLimits.md
Labels: cla-signed, move-prover, move-stdlib

#8057 [Docs] Typo fix in move docs
  developers.diem.com/docs/move/structs-and-resources.md
Labels: cla-signed

#8058 onchain spec
  specifications/transactions/README.md
  specifications/transactions/onchain/README.md
Labels: cla-signed

#8059 initial off-chain api spec
  specifications/transactions/README.md
  specifications/transactions/offchain-api/README.md
Labels: cla-signed

#8078 [script documentation] Fix section nest errors with event docs
  client/transaction-builder/src/stdlib.rs
  language/diem-framework/compiled/script_abis/AccountAdministrationScripts/rotate_dual_attestation_info.abi
  language/diem-framework/compiled/script_abis/PaymentScripts/peer_to_peer_with_metadata.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/burn_txn_fees.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/burn_with_amount.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/cancel_burn_with_amount.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/freeze_account.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/preburn.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/tiered_mint.abi
  language/diem-framework/compiled/script_abis/TreasuryComplianceScripts/unfreeze_account.abi
  language/diem-framework/modules/AccountAdministrationScripts.move
  language/diem-framework/modules/PaymentScripts.move
  language/diem-framework/modules/TreasuryComplianceScripts.move
  language/diem-framework/modules/doc/AccountAdministrationScripts.md
  language/diem-framework/modules/doc/PaymentScripts.md
  language/diem-framework/modules/doc/TreasuryComplianceScripts.md
  language/diem-framework/script_documentation/script_documentation.md
  language/move-prover/docgen/src/docgen.rs
Labels: cla-signed

#8086 [GHA] extend LBT time duration to avoid test failed
  .github/workflows/ci-test.yml
Labels: bors-high-priority, cla-signed

#8084 [cargo] include missing dev-dep
  state-sync/Cargo.toml
Labels: cla-signed

#8079 [specifications] update the move_adapter spec with script function info
  specifications/move_adapter/README.md
Labels: cla-signed

#8085 [move-prover] Fix the problem with the pragma "aborts_if_is_partial"
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/tests/sources/functional/aborts_if.move
Labels: cla-signed, move-prover

#8056 [move-prover] Cleaning prelude and experimenting with vector theories.
  language/move-prover/boogie-backend-v2/src/boogie_helpers.rs
  language/move-prover/boogie-backend-v2/src/boogie_wrapper.rs
  language/move-prover/boogie-backend-v2/src/bytecode_translator.rs
  language/move-prover/boogie-backend-v2/src/lib.rs
  language/move-prover/boogie-backend-v2/src/options.rs
  language/move-prover/boogie-backend-v2/src/prelude/multiset-array-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude/prelude.bpl
  language/move-prover/boogie-backend-v2/src/prelude/vector-array-intern-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude/vector-array-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude/vector-smt-array-ext-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude/vector-smt-array-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude/vector-smt-seq-theory.bpl
  language/move-prover/boogie-backend-v2/src/prelude_template_helpers.rs
  language/move-prover/boogie-backend-v2/src/spec_translator.rs
  language/move-prover/boogie-backend/src/boogie_wrapper.rs
  language/move-prover/bytecode/src/verification_analysis.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
  language/move-prover/tests/sources/functional/address_serialization_constant_size.exp
  language/move-prover/tests/sources/functional/hash_model.exp
  language/move-prover/tests/sources/functional/hash_model_invalid.exp
  language/move-prover/tests/sources/functional/return_values.exp
  language/move-prover/tests/sources/functional/serialize_model.exp
  language/move-prover/tests/testsuite.rs
  language/move-prover/tools/benchmark.sh
  language/move-prover/tools/data/benchmark_fx.data
  language/move-prover/tools/data/benchmark_fx_vnext.data
  language/move-prover/tools/data/benchmark_fx_vnext_smtarray.data
  scripts/dev_setup.sh
Labels: cla-signed

#8074 [writeset-generator] Building the first release writeset
  language/diem-tools/writeset-transaction-generator/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/main.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/artifacts.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/create.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/mod.rs
  language/diem-tools/writeset-transaction-generator/src/release_flow/verify.rs
  language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
  language/e2e-testsuite/src/tests/writeset_builder.rs
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__writeset_builder__build_upgrade_writeset_version_1.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__writeset_builder__build_upgrade_writeset_version_2.exp
  testsuite/smoke-test/src/release_flow.rs
Labels: bors-high-priority
