Repository diem/diem, pull requests merged in 2021-06, with the labels that each got.

#8422 Rust Offchain API: Add Diem Intent Identifier and accompanying fields
  Cargo.lock
  common/workspace-hack/Cargo.toml
  sdk/offchain/Cargo.toml
  sdk/offchain/src/identifier.rs
  sdk/offchain/src/lib.rs
  sdk/offchain/src/subaddress.rs
  sdk/src/transaction_builder.rs
  testsuite/cluster-test/src/experiments/reconfiguration_test.rs
Labels: bors-squash, cla-signed, deps-changed, tcb-deps-changed

#8466 [docker-compose] rename file name for consistency
  docker/compose/README.md
  docker/compose/monitoring/docker-compose.yaml
  docker/compose/public_full_node/docker-compose.yaml
Labels: cla-signed

#8470 [time-service] Ensure sleep outputs are being used
  common/time-service/src/lib.rs
Labels: cla-signed, enhancement

#8482 [move-prover] Fixes a crash when someone tries to include a schema with a type check error.
  language/move-model/src/exp_rewriter.rs
  language/move-model/tests/sources/use_erroneous_schema.exp
  language/move-model/tests/sources/use_erroneous_schema.move
Labels: cla-signed

#8483 [language/changelog] Add changelog entry for Move unit tests
  language/changes/4-unit-testing.md
Labels: bors-squash, cla-signed

#8497 [ci] changing CI action time for weekly dependency report
  .github/workflows/weekly.yml
Labels: cla-unsigned

#8508 dev-setup: install cargo-guppy
  .github/workflows/weekly.yml
  docker/ci/alpine/Dockerfile
  docker/ci/arch/Dockerfile
  docker/ci/github/Dockerfile
  scripts/dev_setup.sh
Labels: cla-signed

#8511 [json-rpc-types] Reduce visual noise for param parsing tests
  json-rpc/types/src/request.rs
Labels: cla-signed

#8494 [diem genesis] some simplifications in Genesis module
  language/diem-framework/modules/DiemVersion.move
  language/diem-framework/modules/Genesis.move
  language/diem-framework/modules/doc/DiemVersion.md
  language/diem-framework/modules/doc/Genesis.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemVersion.md
  language/diem-framework/releases/artifacts/current/docs/modules/Genesis.md
  language/diem-framework/releases/artifacts/current/modules/DiemVersion.mv
  language/diem-framework/releases/artifacts/current/modules/Genesis.mv
  language/move-lang/functional-tests/tests/diem/diem_version/tests.move
  language/tools/move-cli/tests/testsuite/concretize_read_write_set_smoke/genesis.move
  language/tools/move-cli/tests/testsuite/diem_smoke/genesis.move
  language/tools/vm-genesis/src/lib.rs
Labels: cla-signed

#8507 [diem-framework] Add additional auth checks
  language/diem-framework/modules/Diem.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/TransactionFee.move
  language/diem-framework/modules/XUS.move
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/modules/doc/TransactionFee.md
  language/diem-framework/modules/doc/XUS.md
  language/diem-framework/releases/artifacts/current/docs/modules/Diem.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/diem-framework/releases/artifacts/current/docs/modules/TransactionFee.md
  language/diem-framework/releases/artifacts/current/docs/modules/XUS.md
  language/diem-framework/releases/artifacts/current/modules/Diem.mv
  language/diem-framework/releases/artifacts/current/modules/DiemAccount.mv
  language/diem-framework/releases/artifacts/current/modules/TransactionFee.mv
  language/diem-framework/releases/artifacts/current/modules/XUS.mv
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__multi_agent__multi_agent_mint.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__preburn_queue__concurrent_preburns_test_upgrade_empty_preburn.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__preburn_queue__concurrent_preburns_test_upgrade_empty_preburn_multiple_initial_preburns.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__preburn_queue__concurrent_preburns_test_upgrade_existing_balance_at_upgrade.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__preburn_queue__concurrent_preburns_test_upgrade_new_data_new_df_old_scripts_fail.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_add_max_number.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__publish_and_register_new_currency.exp
Labels: cla-signed

#8520 [move-cli] Update readme to reflect changes to Move syntax and CLI output
  language/tools/move-cli/README.md
  language/tools/move-cli/src/sandbox/commands/test.rs
Labels: cla-signed

#8525 [changelog] Add another name considered for abilities: kinds
  language/changes/3-abilities.md
Labels: cla-signed

#8529 [docker-compose] add data restore docker compose
  docker/compose/README.md
  docker/compose/data-restore/docker-compose.yaml
  docker/compose/data-restore/s3-public.toml
Labels: cla-signed

#8540 [network-spec] Fix dead links
  specifications/network/README.md
Labels: bug-fix, cla-signed, network

#8541 [move-prover] fix error filtering in boogie-wrapper
  language/move-prover/boogie-backend/src/boogie_wrapper.rs
Labels: cla-signed

#8533 [x] Improve code coverage generation (turn off sccache in code coverage by default, better warnings/logging, refactor)
  .github/workflows/ci-test.yml
  devtools/x/src/build.rs
  devtools/x/src/cargo.rs
  devtools/x/src/context.rs
  devtools/x/src/fmt.rs
  devtools/x/src/generate_workspace_hack.rs
  devtools/x/src/installer.rs
  devtools/x/src/nextest.rs
  devtools/x/src/test.rs
  devtools/x/src/utils.rs
  x.toml
Labels: bors-squash, cla-signed

#8539 [gha] consolidate artifact downloaders in prep to delete dupe in diem/actions
  .github/workflows/ci-test-complete.yml
Labels: cla-signed

#8550 [account universe] Update keygen for invalid auth key txns
  crypto/crypto/src/test_utils.rs
  language/testing-infra/e2e-tests/src/account_universe/bad_transaction.rs
  language/testing-infra/e2e-tests/src/account_universe/rotate_key.rs
  language/testing-infra/e2e-tests/src/common_transactions.rs
Labels: cla-signed

#8548 [language] add Move release notes for version 1.3
  CHANGELOG/CHANGELOG-1.3.md
  language/RELEASES.md
Labels: cla-signed

#8552 [circleci] fix fuzzing tests.
  devtools/x/src/test.rs
Labels: cla-signed

#8549 [gha] in case diem/logger coverage drops this will alert the author who can lower coverage restrictions.
  .github/workflows/ci-test.yml
Labels: cla-signed

#8558 [gha] allow go to force link on mac managed by github, should be safe locally as well.
  scripts/dev_setup.sh
Labels: cla-signed

#8564 [move-unit-test] Add location reporting for non-abort errors
  language/tools/move-unit-test/src/test_reporter.rs
  language/tools/move-unit-test/tests/test_sources/missing_data.exp
  language/tools/move-unit-test/tests/test_sources/missing_data.move
Labels: cla-signed

#8523 [move-lang] Update compiler API
  language/benchmarks/src/move_vm.rs
  language/diem-framework/src/lib.rs
  language/diem-tools/transaction-replay/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/admin_script_builder.rs
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/bin/move-build.rs
  language/move-lang/src/bin/move-check.rs
  language/move-lang/src/command_line/compiler.rs
  language/move-lang/src/command_line/mod.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/parser/comments.rs
  language/move-lang/src/parser/mod.rs
  language/move-lang/src/shared/mod.rs
  language/move-lang/tests/move_check_testsuite.rs
  language/move-lang/tests/stdlib_sanity_check.rs
  language/move-model/src/lib.rs
  language/move-vm/integration-tests/src/compiler.rs
  language/tools/move-cli/src/base/commands/check.rs
  language/tools/move-cli/src/base/commands/compile.rs
  language/tools/move-cli/src/sandbox/commands/publish.rs
  language/tools/move-cli/src/sandbox/commands/run.rs
  language/tools/move-cli/src/sandbox/utils/package.rs
  language/tools/move-unit-test/src/lib.rs
Labels: cla-signed

#8569 [bytecode verifier][invalid mutations] remove diem-dependency: diem-proptest-helper
  Cargo.lock
  language/bytecode-verifier/invalid-mutations/Cargo.toml
  language/bytecode-verifier/invalid-mutations/src/bounds.rs
  language/bytecode-verifier/invalid-mutations/src/bounds/code_unit.rs
  language/bytecode-verifier/invalid-mutations/src/helpers.rs
  language/bytecode-verifier/invalid-mutations/src/lib.rs
  x.toml
Labels: cla-signed

#8568 [language][binary-format] remove diem-dependency: num-variants
  Cargo.lock
  language/move-binary-format/Cargo.toml
  language/move-binary-format/src/file_format.rs
  language/move-vm/types/src/gas_schedule.rs
  x.toml
Labels: cla-signed, deps-changed, tcb-deps-changed

#8562 [move-vm][stackless-vm] fix warnings on unused items caused by conditional compilation in debug mode
  language/move-prover/interpreter/src/concrete/runtime.rs
  language/move-vm/runtime/src/tracing.rs
Labels: cla-signed

#8571 [forge] added dockerhub secrets for forge codebuild
  docker/forge/buildspec.yaml
Labels: cla-signed

#8531 [move-prover] Added invariant disabling pragmas to user doc
  language/move-prover/doc/user/spec-lang.md
Labels: cla-signed

#8537 [move][vm] Test bounds checker error codes
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
Labels: cla-signed

#8561 [docker] install helm in forge docker build
  docker/forge/Dockerfile
  scripts/dev_setup.sh
Labels: cla-signed

#8577 [dev-infra] Removing pre-command from install_pkg invocation
  scripts/dev_setup.sh
Labels: cla-signed

#8578 [move-prover] Qualify module names by address in Boogie output
  language/move-prover/boogie-backend/src/boogie_helpers.rs
  language/move-prover/boogie-backend/src/prelude/native.bpl
  language/move-prover/boogie-backend/src/prelude/prelude.bpl
Labels: cla-signed

#8598 [stackless-vm][crypto] fix missing feature section
  Cargo.lock
  language/move-prover/interpreter/crypto/Cargo.toml
Labels: cla-signed, deps-changed, tcb-deps-changed

#8600 [move-stdlib] Port vector mvir tests to Move unit tests
  language/diem-framework/releases/artifacts/current/modules/Vector.mv
  language/ir-testsuite/tests/move/natives/vector/vector_append.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_borrow_out_of_range.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_contains.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_destroy_empty.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_destroy_non_empty.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_get_set.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_pop_out_of_range.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_remove.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_reverse.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_simple_push_and_borrow.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_swap.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_swap_empty.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_swap_out_of_bounds.mvir
  language/ir-testsuite/tests/move/natives/vector/vector_swap_remove.mvir
  language/move-stdlib/docs/Vector.md
  language/move-stdlib/modules/Vector.move
  language/move-stdlib/tests/VectorTests.move
Labels: cla-signed

#8614 [gha] increase fetch depth in checkout
  .github/workflows/post-land.yml
Labels: cla-signed

#8622 [move-stdlib] Port option tests to Move unit tests
  language/move-lang/functional-tests/tests/move/natives/vector.move
  language/move-lang/functional-tests/tests/move/option/basics.move
  language/move-lang/functional-tests/tests/move/option/failures.move
  language/move-lang/functional-tests/tests/move/vector/index_of.move
  language/move-stdlib/tests/OptionsTests.move
  language/move-stdlib/tests/VectorTests.move
Labels: cla-signed

#8633 [gha] fix cluster test.
  .github/workflows/ci-test.yml
Labels: bors-high-priority, cla-signed

#8617 [gha] allure2 tests will now report flaky test results.
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test-complete.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-update-sccache.yml
  .github/workflows/docker-publish.yml
  scripts/dev_setup.sh
Labels: cla-signed

#8601 Cherry-pick PR #8550 into release-1.3: [account universe] Update keygen for invalid auth key txns
  crypto/crypto/src/test_utils.rs
  language/testing-infra/e2e-tests/src/account_universe/bad_transaction.rs
  language/testing-infra/e2e-tests/src/account_universe/rotate_key.rs
  language/testing-infra/e2e-tests/src/common_transactions.rs
Labels: cla-signed

#8639 [stackless-vm] clean-up unused deps in the crypto lib
  Cargo.lock
  language/move-prover/interpreter/crypto/Cargo.toml
Labels: cla-signed

#8641 [move-stdlib] Port fixedpoint32, compare, hash, bcs tests to unit tests, update bitvector tests
  language/ir-testsuite/tests/move/natives/check_native_sha2_256.mvir
  language/ir-testsuite/tests/move/natives/check_native_sha3_256.mvir
  language/move-lang/functional-tests/tests/diem/natives/bcs.move
  language/move-lang/functional-tests/tests/diem/natives/bcs_large_value.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/create_div_zero.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/create_overflow.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/create_underflow.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/create_zero.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/divide_by_zero.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/divide_overflow1.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/divide_overflow2.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/multiply_overflow1.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/multiply_overflow2.move
  language/move-lang/functional-tests/tests/move/fixedpoint32/test.move
  language/move-stdlib/nursery/BitVector.move
  language/move-stdlib/nursery/docs/BitVector.md
  language/move-stdlib/tests/BCSTests.move
  language/move-stdlib/tests/BitVectorTests.move
  language/move-stdlib/tests/CompareTests.move
  language/move-stdlib/tests/FixedPoint32Tests.move
  language/move-stdlib/tests/HashTests.move
  language/tools/move-cli/tests/testsuite/compare_smoke/args.exp
  language/tools/move-cli/tests/testsuite/compare_smoke/args.txt
  language/tools/move-cli/tests/testsuite/compare_smoke/src/scripts/compare.move
Labels: cla-signed

#8557 [move-vm] use tracing for logging
  Cargo.lock
  common/logger/Cargo.toml
  common/logger/src/lib.rs
  common/logger/src/logger.rs
  common/logger/src/tracing_adapter.rs
  common/logger/tests/tracing_translation_tests.rs
  common/workspace-hack/Cargo.toml
  language/benchmarks/src/move_vm.rs
  language/diem-tools/e2e-tests-replay/src/lib.rs
  language/diem-tools/transaction-replay/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
  language/diem-vm/Cargo.toml
  language/diem-vm/src/diem_transaction_executor.rs
  language/diem-vm/src/diem_transaction_validator.rs
  language/diem-vm/src/diem_vm.rs
  language/diem-vm/src/errors.rs
  language/diem-vm/src/logging.rs
  language/e2e-testsuite/Cargo.toml
  language/e2e-testsuite/src/tests/failed_transaction_tests.rs
  language/move-vm/integration-tests/src/tests/bad_entry_point_tests.rs
  language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  language/move-vm/integration-tests/src/tests/function_arg_tests.rs
  language/move-vm/integration-tests/src/tests/loader_tests.rs
  language/move-vm/integration-tests/src/tests/mutated_accounts_tests.rs
  language/move-vm/integration-tests/src/tests/return_value_tests.rs
  language/move-vm/runtime/Cargo.toml
  language/move-vm/runtime/src/interpreter.rs
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/logging.rs
  language/move-vm/runtime/src/native_functions.rs
  language/move-vm/runtime/src/runtime.rs
  language/move-vm/runtime/src/session.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
  language/testing-infra/e2e-tests/src/executor.rs
  language/testing-infra/test-generation/src/lib.rs
  language/tools/move-cli/src/sandbox/commands/publish.rs
  language/tools/move-cli/src/sandbox/commands/run.rs
  language/tools/move-unit-test/src/test_runner.rs
  language/tools/vm-genesis/src/lib.rs
  specifications/move_adapter/README.md
  x.toml
Labels: cla-signed, deps-changed, tcb-deps-changed

#8638 [move] Clean up `unwrap_or(&[])` in bounds checker
  language/move-binary-format/src/check_bounds.rs
Labels: cla-signed

#8625 [move documentation] update Move book for visibilities
  language/documentation/book/src/SUMMARY.md
  language/documentation/book/src/friends.md
  language/documentation/book/src/functions.md
  language/documentation/book/src/modules-and-scripts.md
Labels: cla-signed

#8651 [move-cli] add explicit dependency to stdlib with testing feature
  Cargo.lock
  language/tools/move-cli/Cargo.toml
Labels: cla-signed

#8654 [move] Remove `into_module` from loader
  language/move-vm/runtime/src/loader.rs
Labels: cla-signed

#8583 [forge] k8s backend implementation
  Cargo.lock
  scripts/fgi
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/k8s.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/node.rs
  testsuite/forge/src/backend/k8s/swarm.rs
  testsuite/forge/src/backend/local/mod.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/forge/src/backend/mod.rs
  testsuite/forge/src/interface/network.rs
  testsuite/forge/src/lib.rs
  testsuite/forge/src/main.rs
  testsuite/forge/src/report.rs
  testsuite/forge/src/runner.rs
  testsuite/forge/src/txn_emitter/mod.rs
Labels: cla-signed

#8646 jsonrpc-types: add default unknown variants to various enums
  json-rpc/types/src/views.rs
Labels: cla-signed

#8582 [Move documentation] Update book to use abilities
  language/documentation/book/.gitignore
  language/documentation/book/src/SUMMARY.md
  language/documentation/book/src/abilities.md
  language/documentation/book/src/abort-and-assert.md
  language/documentation/book/src/address.md
  language/documentation/book/src/bool.md
  language/documentation/book/src/coding-conventions.md
  language/documentation/book/src/conditionals.md
  language/documentation/book/src/constants.md
  language/documentation/book/src/creating-coins.md
  language/documentation/book/src/equality.md
  language/documentation/book/src/functions.md
  language/documentation/book/src/generics.md
  language/documentation/book/src/global-storage-operators.md
  language/documentation/book/src/global-storage-structure.md
  language/documentation/book/src/integers.md
  language/documentation/book/src/loops.md
  language/documentation/book/src/modules-and-scripts.md
  language/documentation/book/src/references.md
  language/documentation/book/src/signer.md
  language/documentation/book/src/standard-library.md
  language/documentation/book/src/structs-and-resources.md
  language/documentation/book/src/tuples.md
  language/documentation/book/src/uses.md
  language/documentation/book/src/variables.md
  language/documentation/book/src/vector.md
Labels: cla-signed

#8669 [x] force install cargo tools
  devtools/x/src/installer.rs
Labels: cla-signed

#8675 [Move RW set tests] remove -v flag from smoke test
  language/tools/move-cli/tests/testsuite/concretize_read_write_set_smoke/args.exp
  language/tools/move-cli/tests/testsuite/concretize_read_write_set_smoke/args.txt
Labels: cla-signed

#8676 [mempool] Prevent double decrements of upstream peers metric
  mempool/src/shared_mempool/peer_manager.rs
Labels: bug-fix, cla-signed, mempool
