Repository diem/diem, pull requests merged in 2021-12, with the labels that each got.

#9895 [shuffle] extract out deno diem client from devapi
  shuffle/move/examples/integration/devapi.test.ts
  shuffle/move/examples/main/client.ts
  shuffle/move/examples/main/context.ts
  shuffle/move/examples/main/devapi.ts
  shuffle/move/examples/main/mod.ts
Labels: cla-signed

#9904 [move-cli] Fix ordering issues in sandbox publish
  language/tools/move-cli/src/package/cli.rs
  language/tools/move-cli/src/sandbox/commands/publish.rs
  language/tools/move-cli/src/sandbox/commands/test.rs
  language/tools/move-cli/tests/testsuite/cyclic_multi_module_publish/args.exp
  language/tools/move-cli/tests/testsuite/republish/args.exp
  language/tools/move-package/src/compilation/compiled_package.rs
  shuffle/move/examples/main/sources/nft/NFTTests.move
Labels: cla-signed, bors-high-priority

#9915 [shuffle] Transfer NFT
  shuffle/move/examples/e2e/message.test.ts
  shuffle/move/examples/main/helpers.ts
  shuffle/move/examples/main/mod.ts
  shuffle/move/examples/main/sources/nft/NFTTests.move
Labels: cla-signed

#9917 [api] fix cors for accepting POST request with content-type header
  api/src/index.rs
  api/src/tests/index_test.rs
Labels: cla-signed

#9897 [forge] Add ability to commit txn through validators
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/cluster_helper.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: cla-signed, bors-high-priority

#9929 [shuffle] add strong typing to typescript SDK and invokeScriptFunction
  shuffle/move/examples/e2e/message.test.ts
  shuffle/move/examples/integration/helpers.test.ts
  shuffle/move/examples/main/helpers.ts
  shuffle/move/examples/main/mod.ts
  shuffle/move/examples/main/move.ts
Labels: cla-signed

#9932 [fuzzing] fix crash in fuzz_targets/move_vm.rs
  testsuite/diem-fuzzer/artifacts/ValueTarget/crash-7619620b59914850df844994de43e3d10684f2b6
  testsuite/diem-fuzzer/src/fuzz_targets/move_vm.rs
Labels: cla-signed

#9934 [move-tutorial] address tutorial comments for steps 0, 3, 4 and 6
  language/documentation/hackathon-tutorial/diagrams/move_state.png
  language/documentation/hackathon-tutorial/diagrams/solidity_state.png
  language/documentation/hackathon-tutorial/step_0/setup.sh
  language/documentation/hackathon-tutorial/step_6/BasicCoin/sources/MyOddCoin.move
  language/documentation/tutorial/README.md
  language/documentation/tutorial/diagrams/move_state.png
  language/documentation/tutorial/diagrams/solidity_state.png
  language/documentation/tutorial/step_1/BasicCoin/Move.toml
  language/documentation/tutorial/step_1/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2/BasicCoin/Move.toml
  language/documentation/tutorial/step_2/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_2_sol/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2_sol/solution_commands
  language/documentation/tutorial/step_3/BasicCoin.move
  language/documentation/tutorial/step_4/BasicCoin/Move.toml
  language/documentation/tutorial/step_4/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_4_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_4_sol/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_5/BasicCoin/Move.toml
  language/documentation/tutorial/step_5/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_5_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_5_sol/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_6/BasicCoin/Move.toml
  language/documentation/tutorial/step_6/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_6/BasicCoin/sources/MyOddCoin.move
  language/documentation/tutorial/step_7/BasicCoin/Move.toml
  language/documentation/tutorial/step_7/BasicCoin/sources/BasicCoin.move
  language/documentation/tutorial/step_7_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_7_sol/BasicCoin/sources/BasicCoin.move
Labels: cla-signed

#9931 [forge] state-sync performance test in Forge
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/node.rs
  testsuite/forge/src/backend/local/node.rs
  testsuite/forge/src/interface/node.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/state_sync_performance.rs
Labels: cla-signed

#9936 [move-docs] Update step 1, step 2, and step 5
  language/documentation/tutorial/README.md
  language/documentation/tutorial/step_1/BasicCoin/Move.toml
  language/documentation/tutorial/step_1/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2/BasicCoin/Move.toml
  language/documentation/tutorial/step_2/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_2_sol/BasicCoin/sources/FirstModule.move
  language/documentation/tutorial/step_2_sol/solution_commands
  language/documentation/tutorial/step_4/BasicCoin/Move.toml
  language/documentation/tutorial/step_4_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_5/BasicCoin/Move.toml
  language/documentation/tutorial/step_5_sol/BasicCoin/Move.toml
  language/documentation/tutorial/step_6/BasicCoin/Move.toml
  language/documentation/tutorial/step_7/BasicCoin/Move.toml
  language/documentation/tutorial/step_7_sol/BasicCoin/Move.toml
Labels: cla-signed

#9944 [shuffle] rm stale shuffle/README,use shuffle/cli/README
  shuffle/README.md
Labels: cla-signed

#9943 disable compatibility tests
  .github/workflows/ci-test.yml
Labels: cla-signed

#9945 [shuffle] add serde feature to url import
  shuffle/cli/Cargo.toml
Labels: cla-signed

#9946 [shuffle] replace stale stdlib w embedding language/move-stdlib
  shuffle/cli/src/new.rs
  shuffle/cli/src/shared.rs
  shuffle/move/examples/stdlib/Move.toml
  shuffle/move/examples/stdlib/Nursery/sources/Compare.move
  shuffle/move/examples/stdlib/Nursery/sources/Debug.move
  shuffle/move/examples/stdlib/Nursery/sources/Offer.move
  shuffle/move/examples/stdlib/Nursery/sources/Vault.move
  shuffle/move/examples/stdlib/Nursery/tests/CompareTests.move
  shuffle/move/examples/stdlib/error_description.errmap
  shuffle/move/examples/stdlib/sources/BCS.move
  shuffle/move/examples/stdlib/sources/BitVector.move
  shuffle/move/examples/stdlib/sources/Capability.move
  shuffle/move/examples/stdlib/sources/Errors.move
  shuffle/move/examples/stdlib/sources/Event.move
  shuffle/move/examples/stdlib/sources/FixedPoint32.move
  shuffle/move/examples/stdlib/sources/GUID.move
  shuffle/move/examples/stdlib/sources/Hash.move
  shuffle/move/examples/stdlib/sources/Option.move
  shuffle/move/examples/stdlib/sources/Signer.move
  shuffle/move/examples/stdlib/sources/UnitTest.move
  shuffle/move/examples/stdlib/sources/Vector.move
Labels: cla-signed

#9949 [data-client] Add Diem Data Client Config to State Sync Config
  config/src/config/state_sync_config.rs
  diem-node/src/lib.rs
  state-sync/diem-data-client/src/diemnet/mod.rs
  state-sync/diem-data-client/src/diemnet/tests.rs
  state-sync/state-sync-v2/state-sync-multiplexer/src/lib.rs
Labels: cla-signed

#9958 [move] Update Move tutorial to use `cargo install`
  language/documentation/tutorial/README.md
  language/move-analyzer/editors/code/README.md
Labels: cla-signed

#9953 [State Sync] Remove some dead code from the streaming service.
  state-sync/state-sync-v2/data-streaming-service/src/lib.rs
  state-sync/state-sync-v2/data-streaming-service/src/tests/stream_engine.rs
  state-sync/state-sync-v2/state-sync-multiplexer/Cargo.toml
Labels: cla-signed

#9974 [move-tutorial] update path in step 1 and minor fixes
  language/documentation/tutorial/README.md
Labels: cla-signed

#9972 [move] Update move-analyzer extension to 0.0.4
  language/move-analyzer/editors/code/package-lock.json
  language/move-analyzer/editors/code/package.json
Labels: cla-signed

#9959 draft: print `tracing::Span` data through diem::Logger
  Cargo.lock
  crates/diem-logger/Cargo.toml
  crates/diem-logger/src/diem_logger.rs
  crates/diem-logger/src/kv.rs
  crates/diem-logger/src/tracing_adapter.rs
  crates/diem-logger/tests/tracing_translation_tests.rs
  crates/diem-workspace-hack/Cargo.toml
  language/testing-infra/test-generation/Cargo.toml
Labels: cla-unsigned, tcb-deps-changed, deps-changed

#9992 [move] Bump extension's target VS Code to 1.58.2
  language/move-analyzer/editors/code/package.json
Labels: cla-signed

#9995 Revert "Bump .NET SDK from 5.0 to 6.0"
  scripts/dev_setup.sh
Labels: cla-signed, bors-high-priority

#9963 [forge] fix pre release test suite in changelog
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/node.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/partial_nodes_down_test.rs
  testsuite/testcases/src/state_sync_performance.rs
Labels: cla-signed

#9999 [scratchpad] trivial: fix build
  json-rpc/Cargo.toml
Labels: cla-signed

#10002 [forge] Fix forge test exit code
  scripts/fgi/run
Labels: cla-signed

#9993 [move-lang] Bug fixes associated with incorrect error gating
  language/move-lang/src/command_line/compiler.rs
  language/move-lang/src/diagnostics/codes.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/to_bytecode/translate.rs
  language/move-lang/src/unit_test/filter_test_members.rs
  language/move-lang/tests/move_check/naming/assert_one_arg.exp
  language/move-lang/tests/move_check/naming/assert_one_arg.move
  language/move-lang/tests/move_check/naming/other_builtins_invalid.exp
  language/move-lang/tests/move_check/naming/other_builtins_invalid.move
  language/move-lang/tests/move_check/typing/pack_unpack_private_script.exp
  language/move-lang/tests/move_check/typing/pack_unpack_private_script.move
  language/move-lang/tests/move_check/unit_test/attribute_location_invalid.exp
  language/move-lang/tests/move_check/unit_test/expected_failure_not_test.move
  language/move-lang/tests/move_check/unit_test/expected_failure_not_test.unit_test.exp
  language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.exp
  language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.move
  language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.unit_test
  language/move-lang/tests/move_check/unit_test/expected_failure_on_non_function.unit_test.exp
  language/move-lang/tests/move_check/unit_test/multiple_errors.unit_test.exp
  language/move-lang/tests/move_check/unit_test/multiple_test_annotations.unit_test.exp
  language/move-lang/tests/move_check_testsuite.rs
Labels: cla-signed

#10006 [helm] update fullnode helm chart
  helm/fullnode/Chart.yaml
  helm/fullnode/README.md
  helm/fullnode/files/backup/azure.toml
  helm/fullnode/files/backup/oci.toml
  helm/fullnode/files/fullnode.yaml
  helm/fullnode/templates/_backup.tpl
  helm/fullnode/templates/fullnode.yaml
  helm/fullnode/templates/restore.yaml
  helm/fullnode/templates/service.yaml
  helm/fullnode/values.yaml
Labels: cla-signed

#10011 [forge] Add support for more experiment optional args
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/interface/network.rs
  testsuite/forge/src/runner.rs
  testsuite/testcases/src/lib.rs
Labels: cla-signed

#10020 [shuffle] Named Address no longer needs to be Sender
  shuffle/cli/src/shared.rs
  shuffle/cli/src/test.rs
Labels: cla-signed

#10023 [move-prover] Added examples/experimental/math-puzzle
  language/documentation/examples/math-puzzle/Move.toml
  language/documentation/examples/math-puzzle/README.md
  language/documentation/examples/math-puzzle/sources/puzzle.move
Labels: cla-signed, move-prover

#10019 [tf][aws] add aws terraform for validator
  terraform/validator/aws/.terraform.lock.hcl
  terraform/validator/aws/auth.tf
  terraform/validator/aws/aws-calico/.helmignore
  terraform/validator/aws/aws-calico/Chart.yaml
  terraform/validator/aws/aws-calico/crds/calico.yaml
  terraform/validator/aws/aws-calico/templates/calico.yaml
  terraform/validator/aws/backend.tfvars
  terraform/validator/aws/backup.tf
  terraform/validator/aws/cluster.tf
  terraform/validator/aws/dns.tf
  terraform/validator/aws/kubernetes.tf
  terraform/validator/aws/main.tf
  terraform/validator/aws/network.tf
  terraform/validator/aws/templates/bastion_user_data.cloud
  terraform/validator/aws/templates/eks_user_data.sh
  terraform/validator/aws/templates/vault_user_data.sh
  terraform/validator/aws/terraform.tfvars
  terraform/validator/aws/variables.tf
  terraform/validator/aws/vault.tf
  terraform/validator/aws/vault_override.tf
  terraform/validator/aws/versions.tf
  x.toml
Labels: cla-signed

#10026 update transaction-emitter to use rest client and update related tests
  Cargo.lock
  crates/diem-rest-client/Cargo.toml
  crates/diem-rest-client/src/dpn.rs
  crates/diem-rest-client/src/lib.rs
  crates/transaction-emitter/Cargo.toml
  crates/transaction-emitter/src/cluster.rs
  crates/transaction-emitter/src/instance.rs
  crates/transaction-emitter/src/lib.rs
  crates/transaction-emitter/src/main.rs
  testsuite/cluster-test/Cargo.toml
  testsuite/cluster-test/src/cluster.rs
  testsuite/cluster-test/src/experiments/accurate_measurment.rs
  testsuite/cluster-test/src/experiments/compatibility_test.rs
  testsuite/cluster-test/src/experiments/cpu_flamegraph.rs
  testsuite/cluster-test/src/experiments/load_test.rs
  testsuite/cluster-test/src/experiments/performance_benchmark.rs
  testsuite/cluster-test/src/experiments/performance_benchmark_three_region_simulation.rs
  testsuite/cluster-test/src/experiments/reconfiguration_test.rs
  testsuite/cluster-test/src/experiments/recovery_time.rs
  testsuite/cluster-test/src/experiments/state_sync_performance.rs
  testsuite/cluster-test/src/experiments/twin_validator.rs
  testsuite/cluster-test/src/experiments/versioning_test.rs
  testsuite/cluster-test/src/instance.rs
  testsuite/cluster-test/src/lib.rs
  testsuite/cluster-test/src/main.rs
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/k8s/node.rs
  testsuite/forge/src/backend/k8s/swarm.rs
  testsuite/forge/src/backend/local/node.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/forge/src/interface/node.rs
  testsuite/testcases/Cargo.toml
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/reconfiguration_test.rs
Labels: cla-signed, bors-squash

#10028 [tf][vault-init] add terraform for vault initialization
  terraform/vault-init/.terraform.lock.hcl
  terraform/vault-init/README.md
  terraform/vault-init/backend.tf
  terraform/vault-init/backend.tf.example
  terraform/vault-init/backend.tfvars
  terraform/vault-init/diem-root.tf.example
  terraform/vault-init/kubernetes.tf
  terraform/vault-init/main.tf
  terraform/vault-init/policy.tf
  terraform/vault-init/versions.tf
Labels: cla-signed

#10029 [data-client] change data client config type to u64
  config/src/config/state_sync_config.rs
  state-sync/diem-data-client/src/diemnet/mod.rs
Labels: cla-signed

#10033 [tf][azure] add terraform files for validator deployment in Azure
  terraform/validator/azure/.terraform.lock.hcl
  terraform/validator/azure/aad/aks-aad.tf
  terraform/validator/azure/aad/aks-aad_override.tf
  terraform/validator/azure/auth.tf
  terraform/validator/azure/backend.tfvars
  terraform/validator/azure/backup.tf
  terraform/validator/azure/cluster.tf
  terraform/validator/azure/cost_override.tf.example
  terraform/validator/azure/dns.tf
  terraform/validator/azure/kubernetes.tf
  terraform/validator/azure/main.tf
  terraform/validator/azure/network.tf
  terraform/validator/azure/templates/bastion_user_data.cloud
  terraform/validator/azure/templates/vault_user_data.sh
  terraform/validator/azure/terraform.tfvars
  terraform/validator/azure/variables.tf
  terraform/validator/azure/vault.tf
  terraform/validator/azure/vault_override.tf
  terraform/validator/azure/versions.tf
Labels: cla-signed

#10042 [executor] fix anyhow error msg interpolation
  execution/executor/src/components/block_tree/mod.rs
Labels: cla-signed

#10032 Migrate smoke-tests test utils to call REST API
  api/types/src/transaction.rs
  crates/diem-rest-client/src/dpn.rs
  crates/diem-rest-client/src/lib.rs
  shuffle/cli/tests/common/mod.rs
  shuffle/cli/tests/shuffle-forge-cli-tests.rs
  testsuite/forge/src/interface/admin.rs
  testsuite/smoke-test/src/client.rs
  testsuite/smoke-test/src/full_nodes.rs
  testsuite/smoke-test/src/genesis.rs
  testsuite/smoke-test/src/release_flow.rs
  testsuite/smoke-test/src/scripts_and_modules.rs
  testsuite/smoke-test/src/state_sync.rs
  testsuite/smoke-test/src/state_sync_v2.rs
  testsuite/smoke-test/src/storage.rs
  testsuite/smoke-test/src/test_utils.rs
  types/src/on_chain_config/mod.rs
Labels: cla-signed

#10018 [move-stdlib] Add swap_or_fill
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/bytecode_modules/Option.mv
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/docs/Option.md
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/source_maps/Option.mvsm
  diem-move/diem-framework/DPN/releases/artifacts/current/build/MoveStdlib/sources/Option.move
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/bytecode_modules/Option.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/docs/Option.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/source_maps/Option.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/MoveStdlib/sources/Option.move
  language/move-stdlib/docs/Option.md
  language/move-stdlib/sources/Option.move
  language/move-stdlib/tests/OptionsTests.move
Labels: cla-signed

#10053 migrate forge interfaces to use rest client and update tests
  crates/debug-interface/src/lib.rs
  crates/diem-rest-client/src/lib.rs
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/cluster_helper.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/node.rs
  testsuite/forge/src/backend/k8s/swarm.rs
  testsuite/forge/src/backend/local/mod.rs
  testsuite/forge/src/backend/local/node.rs
  testsuite/forge/src/backend/local/swarm.rs
  testsuite/forge/src/interface/factory.rs
  testsuite/forge/src/interface/node.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/forge/src/runner.rs
  testsuite/smoke-test/src/client.rs
  testsuite/smoke-test/src/consensus.rs
  testsuite/smoke-test/src/full_nodes.rs
  testsuite/smoke-test/src/fullnode.rs
  testsuite/smoke-test/src/genesis.rs
  testsuite/smoke-test/src/key_manager.rs
  testsuite/smoke-test/src/network.rs
  testsuite/smoke-test/src/operational_tooling.rs
  testsuite/smoke-test/src/release_flow.rs
  testsuite/smoke-test/src/replay_tooling.rs
  testsuite/smoke-test/src/smoke_test_environment.rs
  testsuite/smoke-test/src/state_sync.rs
  testsuite/smoke-test/src/state_sync_v2.rs
  testsuite/smoke-test/src/storage.rs
  testsuite/testcases/src/compatibility_test.rs
  testsuite/testcases/src/lib.rs
  testsuite/testcases/src/partial_nodes_down_test.rs
  testsuite/testcases/src/state_sync_performance.rs
Labels: cla-signed, bors-squash

#10057 [data-client] Print less debug info for GlobalDataSummary
  state-sync/diem-data-client/src/diemnet/mod.rs
  state-sync/diem-data-client/src/lib.rs
  types/src/ledger_info.rs
Labels: cla-signed

#10071 Make absint public
  language/move-bytecode-verifier/src/absint.rs
  language/move-bytecode-verifier/src/lib.rs
Labels: cla-signed

#10087 [x] don't cancel test run on first failing test
  .config/nextest.toml
Labels: cla-signed

#10092 [Forge] Use append mode for node logs
  testsuite/forge/src/backend/local/node.rs
Labels: cla-signed

#10090 [move-prover] Partial specification of Vote module
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/BuildInfo.yaml
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/bytecode_modules/Vote.mv
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/docs/Vote.md
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/source_maps/Vote.mvsm
  diem-move/diem-framework/experimental/releases/artifacts/current/build/DiemExperimental/sources/Vote.move
  diem-move/diem-framework/experimental/releases/artifacts/current/error_description/error_description.errmap
  diem-move/diem-framework/experimental/sources/Vote.move
Labels: cla-signed, move-prover

#10099 [move-examples] Added more Move examples
  language/documentation/examples/experimental/basic-coin/Move.toml
  language/documentation/examples/experimental/basic-coin/sources/BasicCoin.move
  language/documentation/examples/experimental/coin-swap/Move.toml
  language/documentation/examples/experimental/coin-swap/sources/CoinSwap.move
  language/documentation/examples/experimental/coin-swap/sources/GoldCoin.move
  language/documentation/examples/experimental/coin-swap/sources/PoolToken.move
  language/documentation/examples/experimental/coin-swap/sources/SilverCoin.move
  language/documentation/examples/experimental/math-puzzle/Move.toml
  language/documentation/examples/experimental/math-puzzle/README.md
  language/documentation/examples/experimental/math-puzzle/sources/puzzle.move
  language/documentation/examples/experimental/rounding-error/Move.toml
  language/documentation/examples/experimental/rounding-error/sources/Reserve.move
  language/documentation/examples/experimental/rounding-error/sources/Uniswap.move
  language/documentation/tutorial/step_7/BasicCoin/sources/BasicCoin.move
Labels: cla-signed
