Repository diem/diem, pull requests merged in 2021-08, with the labels that each got.

#8851 [move-prover] make inconsistency check instrumentation a separate pass
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/function_target_pipeline.rs
  language/move-prover/bytecode/src/inconsistency_check.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/pipeline_factory.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
Labels: cla-signed

#8852 [move-prover] Report: updating introduction
  language/move-prover/doc/report/biblio.bib
  language/move-prover/doc/report/intro.tex
  language/move-prover/doc/report/macros.tex
  language/move-prover/doc/report/main.pdf
  language/move-prover/doc/report/move.tex
Labels: cla-signed

#8853 [move] Fix `Symbol` serialization
  Cargo.lock
  language/move-symbol-pool/Cargo.toml
  language/move-symbol-pool/src/lib.rs
  language/move-symbol-pool/src/pool.rs
  language/move-symbol-pool/src/symbol.rs
Labels: cla-signed

#8861 [move-prover] add a flag to toggle whether unconditional abort is inconsistency
  language/move-prover/bytecode/src/inconsistency_check.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/src/cli.rs
  language/move-prover/tests/sources/functional/inconsistency.exp
  language/move-prover/tests/sources/functional/inconsistency.move
  language/move-prover/tests/sources/functional/inconsistency.no_opaque_exp
  language/move-prover/tests/sources/functional/inconsistency_always_abort.exp
  language/move-prover/tests/sources/functional/inconsistency_always_abort.move
Labels: cla-signed

#8857 [move-lang] Improve tmp local generation
  language/diem-framework/releases/artifacts/current/modules/AccountFreezing.mv
  language/diem-framework/releases/artifacts/current/modules/AccountLimits.mv
  language/diem-framework/releases/artifacts/current/modules/Authenticator.mv
  language/diem-framework/releases/artifacts/current/modules/DesignatedDealer.mv
  language/diem-framework/releases/artifacts/current/modules/Diem.mv
  language/diem-framework/releases/artifacts/current/modules/DiemAccount.mv
  language/diem-framework/releases/artifacts/current/modules/DiemBlock.mv
  language/diem-framework/releases/artifacts/current/modules/DiemConfig.mv
  language/diem-framework/releases/artifacts/current/modules/DiemId.mv
  language/diem-framework/releases/artifacts/current/modules/DiemSystem.mv
  language/diem-framework/releases/artifacts/current/modules/DiemTimestamp.mv
  language/diem-framework/releases/artifacts/current/modules/DiemTransactionPublishingOption.mv
  language/diem-framework/releases/artifacts/current/modules/DiemVMConfig.mv
  language/diem-framework/releases/artifacts/current/modules/DiemVersion.mv
  language/diem-framework/releases/artifacts/current/modules/DualAttestation.mv
  language/diem-framework/releases/artifacts/current/modules/Event.mv
  language/diem-framework/releases/artifacts/current/modules/FixedPoint32.mv
  language/diem-framework/releases/artifacts/current/modules/Genesis.mv
  language/diem-framework/releases/artifacts/current/modules/NetworkIdentity.mv
  language/diem-framework/releases/artifacts/current/modules/Option.mv
  language/diem-framework/releases/artifacts/current/modules/RecoveryAddress.mv
  language/diem-framework/releases/artifacts/current/modules/RegisteredCurrencies.mv
  language/diem-framework/releases/artifacts/current/modules/Roles.mv
  language/diem-framework/releases/artifacts/current/modules/SharedEd25519PublicKey.mv
  language/diem-framework/releases/artifacts/current/modules/SlidingNonce.mv
  language/diem-framework/releases/artifacts/current/modules/TransactionFee.mv
  language/diem-framework/releases/artifacts/current/modules/VASP.mv
  language/diem-framework/releases/artifacts/current/modules/VASPDomain.mv
  language/diem-framework/releases/artifacts/current/modules/ValidatorConfig.mv
  language/diem-framework/releases/artifacts/current/modules/Vector.mv
  language/diem-framework/releases/artifacts/current/modules/XDX.mv
  language/move-lang/src/hlir/translate.rs
  language/move-prover/bytecode/tests/from_move/smoke_test.exp
  language/move-prover/bytecode/tests/read_write_set/pack_unpack.exp
  language/tools/move-cli/tests/testsuite/print_stack_trace/args.exp
Labels: cla-signed

#8856 [move-symbol-pool] Minor improvements
  language/move-symbol-pool/src/pool.rs
  language/move-symbol-pool/src/symbol.rs
Labels: cla-signed

#8827 [language] Add changelog for phantom types
  language/changes/6-phantom-type-params.md
Labels: cla-signed

#8863 adding a line in the beginning to help in debugging when gha fails
  scripts/weekly-dep-report.sh
Labels: cla-unsigned

#8870 [move-lang] Quick test fix
  language/move-lang/functional-tests/tests/move/dependencies/pack_unpack_private.exp
  language/move-lang/tests/move_check/typing/pack_unpack_private.exp
  language/move-lang/tests/move_check/typing/pack_unpack_private.move
Labels: cla-signed

#8865 [move-prover] Fixes a bug in the `choose` operator.
  language/move-model/src/ast.rs
  language/move-model/src/builder/module_builder.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/tests/sources/functional/choice.cvc4_exp
  language/move-prover/tests/sources/functional/choice.exp
  language/move-prover/tests/sources/functional/choice.move
Labels: cla-signed

#8850 [move] Lex Move IR source buffers in-place
  language/compiler/ir-to-bytecode/src/parser.rs
  language/compiler/ir-to-bytecode/syntax/src/lexer.rs
Labels: cla-signed

#8875 [move-prover] Cleanup benchmarks and add a new benchmark for opaque/ignore opaque
  language/move-prover/lab/data/mono/README.md
  language/move-prover/lab/data/mono/fun_by_fun.svg
  language/move-prover/lab/data/mono/mod_by_mod.svg
  language/move-prover/lab/data/mono/notebook.ipynb
  language/move-prover/lab/data/mono/notebook.pdf
  language/move-prover/lab/data/mono/notebook.sh
  language/move-prover/lab/data/mono/plot.sh
  language/move-prover/lab/data/mono/run.sh
  language/move-prover/lab/data/new-boogie/README.md
  language/move-prover/lab/data/new-boogie/fun_by_fun.svg
  language/move-prover/lab/data/new-boogie/mod_by_mod.svg
  language/move-prover/lab/data/new-boogie/notebook.ipynb
  language/move-prover/lab/data/new-boogie/notebook.pdf
  language/move-prover/lab/data/new-boogie/notebook.sh
  language/move-prover/lab/data/new-boogie/plot.sh
  language/move-prover/lab/data/opaque/README.md
  language/move-prover/lab/data/opaque/fun_by_fun.svg
  language/move-prover/lab/data/opaque/ignore_internal_opaque.fun_data
  language/move-prover/lab/data/opaque/ignore_internal_opaque.mod_data
  language/move-prover/lab/data/opaque/ignore_internal_opaque.toml
  language/move-prover/lab/data/opaque/ignore_opaque.fun_data
  language/move-prover/lab/data/opaque/ignore_opaque.mod_data
  language/move-prover/lab/data/opaque/ignore_opaque.toml
  language/move-prover/lab/data/opaque/mod_by_mod.svg
  language/move-prover/lab/data/opaque/opaque.fun_data
  language/move-prover/lab/data/opaque/opaque.mod_data
  language/move-prover/lab/data/opaque/opaque.toml
  language/move-prover/lab/data/opaque/plot.sh
  language/move-prover/lab/data/opaque/run.sh
  language/move-prover/lab/data/regression/README.md
  language/move-prover/lab/data/regression/default.last.mod_data
  language/move-prover/lab/data/regression/default.toml
  language/move-prover/lab/data/regression/notebook.ipynb
  language/move-prover/lab/data/regression/notebook.sh
  language/move-prover/lab/data/struct-as-adt/README.md
  language/move-prover/lab/data/struct-as-adt/fun_by_fun.svg
  language/move-prover/lab/data/struct-as-adt/mod_by_mod.svg
  language/move-prover/lab/data/struct-as-adt/notebook.ipynb
  language/move-prover/lab/data/struct-as-adt/notebook.pdf
  language/move-prover/lab/data/struct-as-adt/notebook.sh
  language/move-prover/lab/data/struct-as-adt/plot.sh
  language/move-prover/lab/data/struct-as-adt/run.sh
  language/move-prover/lab/data/vector-theories/README.md
  language/move-prover/lab/data/vector-theories/boogie_array.fun_data
  language/move-prover/lab/data/vector-theories/boogie_array.mod_data
  language/move-prover/lab/data/vector-theories/boogie_array_intern.toml
  language/move-prover/lab/data/vector-theories/fun_by_fun.svg
  language/move-prover/lab/data/vector-theories/mod_by_mod.svg
  language/move-prover/lab/data/vector-theories/notebook.ipynb
  language/move-prover/lab/data/vector-theories/notebook.pdf
  language/move-prover/lab/data/vector-theories/notebook.sh
  language/move-prover/lab/data/vector-theories/plot.sh
  language/move-prover/lab/data/vector-theories/smt_array.fun_data
  language/move-prover/lab/data/vector-theories/smt_array.mod_data
  language/move-prover/lab/data/vector-theories/smt_array_ext.fun_data
  language/move-prover/lab/data/vector-theories/smt_array_ext.mod_data
  language/move-prover/lab/data/vector-theories/smt_seq.toml
  language/move-prover/lab/src/benchmark.rs
Labels: cla-signed

#8868 [move-prover] Implemented is_signer in Prover
  language/diem-framework/modules/PaymentScripts.move
  language/diem-framework/modules/doc/PaymentScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/PaymentScripts.md
  language/diem-framework/releases/artifacts/current/docs/scripts/script_documentation.md
  language/diem-framework/script_documentation/script_documentation.md
  language/move-model/src/ty.rs
  language/move-prover/boogie-backend/src/boogie_helpers.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/boogie-backend/src/prelude/native.bpl
  language/move-prover/boogie-backend/src/prelude/prelude.bpl
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/tests/sources/functional/is_signer.cvc4_exp
  language/move-prover/tests/sources/functional/is_signer.exp
  language/move-prover/tests/sources/functional/is_signer.move
  language/move-prover/tests/sources/functional/is_signer.no_opaque_exp
  language/move-prover/tests/sources/functional/script_incorrect.no_opaque_exp
  language/move-stdlib/docs/Signer.md
  language/move-stdlib/modules/Signer.move
Labels: cla-signed, move-prover

#8881 [move-lang] Only stop at blocking errors
  language/diem-tools/transaction-replay/src/lib.rs
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/command_line/compiler.rs
  language/move-lang/src/diagnostics/mod.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/shared/mod.rs
  language/move-lang/tests/move_check/expansion/duplicate_field_assign.exp
  language/move-lang/tests/move_check/expansion/duplicate_field_unpack.exp
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/address_arg_is_not_signer.exp
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/address_arg_is_not_signer.move
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/double_signer.move
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/move_to_no_args.move
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/triple_signer.exp
  language/move-lang/tests/move_check/translated_ir_tests/move/signer/triple_signer.move
  language/move-lang/tests/move_check/typing/assign_duplicate_assigning.exp
  language/move-lang/tests/move_check/typing/bind_duplicate_binding.exp
  language/move-lang/tests/move_check/typing/bind_pop_resource.exp
  language/move-lang/tests/move_check/typing/borrow_field_internal.move
  language/move-lang/tests/move_check/typing/conditional_copy_invalid.move
  language/move-lang/tests/move_check/typing/conditional_drop_invalid.exp
  language/move-lang/tests/move_check/typing/conditional_global_operations.move
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_all_cases.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_all_cases.move
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_function_parameter.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_function_parameter.move
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_lvalues_bind_type.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_lvalues_decl_type.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_lvalues_decl_type.move
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_lvalues_pack_type_args.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_type_annotation.exp
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_type_annotation.move
  language/move-lang/tests/move_check/typing/constraints_not_satisfied_type_arguments_internal_pack.exp
  language/move-lang/tests/move_check/typing/duplicate_function_parameter_names.exp
  language/move-lang/tests/move_check/typing/implicit_deref_borrow_field_internal.move
  language/move-lang/tests/move_check/typing/implicit_deref_borrow_field_not_copyable.exp
  language/move-lang/tests/move_check/typing/implicit_deref_borrow_field_not_copyable.move
  language/move-lang/tests/move_check/typing/main_arguments_invalid.exp
  language/move-lang/tests/move_check/typing/main_arguments_invalid.move
  language/move-lang/tests/move_check/typing/module_call_constraints_not_satisfied.exp
  language/move-lang/tests/move_check/typing/module_call_constraints_not_satisfied.move
  language/move-lang/tests/move_check/typing/mutate_field_internal.move
  language/move-lang/tests/move_check/typing/phantom_param_op_abilities_invalid.exp
  language/move-lang/tests/move_check/typing/seq_cannot_ignore_resource.exp
  language/move-lang/tests/move_check_testsuite.rs
  language/move-model/src/lib.rs
  language/tools/move-unit-test/src/lib.rs
Labels: cla-signed

#8882 [move-prover] make the no_opaque test ignore internal functions only
  language/move-prover/tests/sources/functional/ModifiesErrorTest.exp
  language/move-prover/tests/sources/functional/ModifiesErrorTest.move
  language/move-prover/tests/sources/functional/ModifiesErrorTest.no_opaque_exp
  language/move-prover/tests/sources/functional/ModifiesTypeTest.exp
  language/move-prover/tests/sources/functional/ModifiesTypeTest.move
  language/move-prover/tests/sources/functional/ModifiesTypeTest.no_opaque_exp
  language/move-prover/tests/sources/functional/disable_inv.exp
  language/move-prover/tests/sources/functional/disable_inv.inv-v1_exp
  language/move-prover/tests/sources/functional/disable_inv.inv_v2_exp
  language/move-prover/tests/sources/functional/disable_inv.move
  language/move-prover/tests/sources/functional/disable_inv_friends.inv-v1_exp
  language/move-prover/tests/sources/functional/disable_inv_friends.move
  language/move-prover/tests/sources/functional/emits.cvc4_exp
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/emits.move
  language/move-prover/tests/sources/functional/emits.no_opaque_exp
  language/move-prover/tests/sources/functional/friend_error.inv-v1_exp
  language/move-prover/tests/sources/functional/friend_error.move
  language/move-prover/tests/sources/functional/global_invariants.exp
  language/move-prover/tests/sources/functional/global_invariants.move
  language/move-prover/tests/sources/functional/global_invariants.no_opaque_exp
  language/move-prover/tests/sources/functional/is_signer.no_opaque_exp
  language/move-prover/tests/sources/functional/resources.exp
  language/move-prover/tests/sources/functional/resources.move
  language/move-prover/tests/sources/functional/resources.no_opaque_exp
  language/move-prover/tests/sources/functional/script_incorrect.exp
  language/move-prover/tests/sources/functional/script_incorrect.move
  language/move-prover/tests/sources/functional/script_incorrect.no_opaque_exp
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#8873 [move-prover] Mutation testing framework
  Cargo.lock
  Cargo.toml
  language/move-prover/bytecode/src/mutation_tester.rs
  language/move-prover/mutation/Cargo.toml
  language/move-prover/mutation/README.md
  language/move-prover/mutation/src/lib.rs
  language/move-prover/mutation/src/main.rs
  language/move-prover/mutation/src/mutator.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
Labels: bors-squash

#8903 [ci] Add debugging option in weekly-dep-report
  scripts/weekly-dep-report.sh
Labels: cla-unsigned

#8899 [execution] Output all events not just reconfig events
  execution/executor/src/lib.rs
  state-sync/src/executor_proxy.rs
Labels: cla-signed

#8904 [transactional tests][bytecode verifier] Start bytecode verifier test migration
  Cargo.lock
  Cargo.toml
  language/bytecode-verifier/transactional-tests/Cargo.toml
  language/bytecode-verifier/transactional-tests/src/lib.rs
  language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_bad.exp
  language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_bad.mvir
  language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_ok.exp
  language/bytecode-verifier/transactional-tests/tests/reference_safety/eq_ok.mvir
  language/bytecode-verifier/transactional-tests/tests/tests.rs
  language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
  language/testing-infra/transactional-test-runner/tests/vm_test_harness/example.exp
  x.toml
Labels: cla-signed, bors-high-priority

#8905 [language] add Move release notes for version 1.4
  language/RELEASES.md
Labels: cla-signed

#8911 forge: move cli into its own crate
  Cargo.lock
  Cargo.toml
  testsuite/forge-cli/Cargo.toml
  testsuite/forge-cli/src/main.rs
  x.toml
Labels: cla-signed, forge

#8910 [deps] update hyper to fix two rustsecs
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-unsigned, tcb-deps-changed, deps-changed, bors-squash

#8914 [ci] use depdive=0.1.0
  .github/workflows/dep-update-review.yml
Labels: cla-unsigned

#8886 [move traits] Move VM MoveStorage trait to move-core-types
  Cargo.lock
  language/diem-tools/diem-read-write-set/Cargo.toml
  language/diem-tools/diem-read-write-set/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
  language/diem-vm/src/data_cache.rs
  language/diem-vm/src/diem_transaction_executor.rs
  language/diem-vm/src/diem_transaction_validator.rs
  language/diem-vm/src/diem_vm.rs
  language/move-core/types/src/lib.rs
  language/move-core/types/src/resolver.rs
  language/move-prover/interpreter/src/shared/bridge.rs
  language/move-prover/src/lib.rs
  language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  language/move-vm/runtime/src/data_cache.rs
  language/move-vm/runtime/src/move_vm.rs
  language/move-vm/runtime/src/runtime.rs
  language/move-vm/runtime/src/session.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
  language/move-vm/test-utils/src/storage.rs
  language/testing-infra/e2e-tests/src/data_store.rs
  language/testing-infra/test-generation/src/lib.rs
  language/testing-infra/transactional-test-runner/src/vm_test_harness.rs
  language/tools/diem-resource-viewer/Cargo.toml
  language/tools/diem-resource-viewer/src/lib.rs
  language/tools/genesis-viewer/Cargo.toml
  language/tools/genesis-viewer/src/main.rs
  language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs
  language/tools/read-write-set/Cargo.toml
  language/tools/read-write-set/src/dynamic_analysis.rs
  language/tools/read-write-set/src/lib.rs
  language/tools/resource-viewer/Cargo.toml
  language/tools/resource-viewer/src/lib.rs
  language/tools/resource-viewer/src/resolver.rs
Labels: cla-signed

#8925 [move-prover] Fixes a bug with shadowing of let-bound names in schemas
  language/move-model/src/builder/module_builder.rs
  language/move-prover/tests/sources/functional/let.move
Labels: cla-signed

#8931 Disable the OSX sscache job as cost savings
  .github/workflows/ci-post-land.yml
Labels: cla-signed

#8935 [gha] fix docker mount points
  .github/workflows/ci-post-land.yml
Labels: cla-signed

#8945 [move-prover] update spec lang doc on loop invariants
  language/move-prover/doc/user/spec-lang.md
Labels: cla-signed

#8939 [ci] update active branches
  .github/workflows/daily.yml
Labels: cla-signed

#8972 [move-model] allow the spec model to be built when compiler has warnings
  language/move-model/src/lib.rs
  language/move-prover/abigen/tests/sources/bad_script.abi
  language/move-prover/abigen/tests/sources/bad_script.move
Labels: cla-signed

#8966 [docker] new debian base image
  docker/ci/github/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/faucet/Dockerfile
  docker/forge/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#8967 [gha] fix up rustdoc for consistence & correct trigger. Fix up lint to not rerun on bors land.
  .github/workflows/ci-post-land.yml
  .github/workflows/ci-test.yml
Labels: cla-signed

#8979 Change reference ID to pub
  types/src/transaction/metadata.rs
Labels: cla-signed

#8990 [transaction-builder] Add support for `vector<vector<u8>>` in script functions
  language/transaction-builder/generator/src/common.rs
  language/transaction-builder/generator/src/cpp.rs
  language/transaction-builder/generator/src/rust.rs
Labels: cla-signed

#8976 Cherry-pick PR #8910 into release-1.4: [deps] update hyper to fix two rustsecs
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-unsigned

#8977 Cherry-pick PR #8910 into release-1.3: [deps] update hyper to fix two rustsecs
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-unsigned, tcb-deps-changed, deps-changed

#8988 [move-prover] Re-enables invariant disabling analysis.
  language/diem-framework/modules/DesignatedDealer.move
  language/diem-framework/modules/Diem.move
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/modules/doc/DesignatedDealer.md
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/releases/artifacts/current/docs/modules/DesignatedDealer.md
  language/diem-framework/releases/artifacts/current/docs/modules/Diem.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/diem-framework/releases/artifacts/current/modules/DesignatedDealer.mv
  language/diem-framework/releases/artifacts/current/modules/Diem.mv
  language/diem-framework/releases/artifacts/current/modules/DiemAccount.mv
  language/move-lang/functional-tests/tests/diem/designated_dealer/basics.move
  language/move-lang/functional-tests/tests/diem/diem/add_currency_to_system.move
  language/move-lang/functional-tests/tests/diem/diem/functionality.move
  language/move-lang/functional-tests/tests/diem/diem/multi_currency.move
  language/move-lang/functional-tests/tests/diem/diem_account/add_currency.move
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/bytecode/src/verification_analysis_v2.rs
  language/move-prover/tests/sources/functional/cross_module_invariant.move
  language/move-prover/tests/sources/functional/disable_inv.exp
  language/move-prover/tests/sources/functional/disable_inv_indirect.exp
  language/move-prover/tests/sources/functional/disable_inv_indirect.move
  language/move-prover/tools/check_pr.sh
Labels: cla-signed, bors-squash

#8998 [executor-benchmark] report time in DB commission
  execution/executor-benchmark/src/lib.rs
Labels: cla-signed

#9001 [diem-framework] remove the spec in NetworkIdentity causing timeout
  language/diem-framework/modules/NetworkIdentity.move
  language/diem-framework/modules/doc/NetworkIdentity.md
  language/diem-framework/releases/artifacts/current/docs/modules/NetworkIdentity.md
Labels: cla-signed

#8999 update crossbeam-deque to v0.8.1 to fix RUSTSEC-2021-0093
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-signed, tcb-deps-changed, deps-changed

#9004 [forge] implement logs_location for k8s swarm
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: cla-signed

#9008 Fix markdown issue in global-storage-operators.md
  language/documentation/book/src/global-storage-operators.md
Labels: cla-signed

#9005 [move] Fix empty source mappings for scripts
  language/compiler/bytecode-source-map/src/source_map.rs
  language/compiler/bytecode-source-map/tests/dummies.rs
Labels: cla-signed

#9000 [json-rpc]: remove null values when serializing Views to JSON
  json-rpc/types/src/views.rs
Labels: cla-signed

#8929 [diem-framework] Send NetworkIdentity events to a central event stream
  language/diem-framework/modules/NetworkIdentity.move
  language/diem-framework/modules/doc/NetworkIdentity.md
  language/diem-framework/releases/artifacts/current/docs/modules/NetworkIdentity.md
  language/diem-framework/releases/artifacts/current/error_description/error_description.errmap
  language/diem-framework/releases/artifacts/current/modules/NetworkIdentity.mv
  language/move-lang/functional-tests/tests/diem/network_identity/network_identity.move
Labels: cla-signed, diem-framework

#9006 [State Sync] Add MempoolNotifier interface and implementation.
  Cargo.lock
  Cargo.toml
  consensus/Cargo.toml
  consensus/src/txn_manager.rs
  diem-node/Cargo.toml
  diem-node/src/lib.rs
  mempool/Cargo.toml
  mempool/src/counters.rs
  mempool/src/lib.rs
  mempool/src/logging.rs
  mempool/src/shared_mempool/coordinator.rs
  mempool/src/shared_mempool/runtime.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  mempool/src/tests/mocks.rs
  mempool/src/tests/node.rs
  mempool/src/tests/shared_mempool_test.rs
  state-sync/inter-component/mempool-notifications/Cargo.toml
  state-sync/inter-component/mempool-notifications/src/lib.rs
  state-sync/state-sync-v1/Cargo.toml
  state-sync/state-sync-v1/src/bootstrapper.rs
  state-sync/state-sync-v1/src/coordinator.rs
  state-sync/state-sync-v1/src/counters.rs
  state-sync/state-sync-v1/src/error.rs
  state-sync/state-sync-v1/src/fuzzing.rs
  state-sync/state-sync-v1/src/shared_components.rs
  state-sync/state-sync-v1/tests/test_harness.rs
Labels: cla-signed, deps-changed

#9047 [State Sync] Small cleanups to MempoolNotifier.
  mempool/src/tests/shared_mempool_test.rs
  state-sync/inter-component/mempool-notifications/src/lib.rs
  state-sync/state-sync-v1/src/coordinator.rs
Labels: cla-signed

#9015 [RUSTSEC-2021-0093][rel-1.4] crossbeam-deque 0.8.0 -> 0.8.1
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-signed, tcb-deps-changed, deps-changed

#9016 [RUSTSEC-2021-0093][rel-1.3] crossbeam-deque 0.8.0 -> 0.8.1
  Cargo.lock
  common/workspace-hack/Cargo.toml
Labels: cla-signed, tcb-deps-changed, deps-changed
