Repository diem/diem, pull requests merged in 2021-09, with the labels that each got.

#9053 [move-prover] minor improvements to the verification analysis pass
  language/move-prover/bytecode/src/verification_analysis.rs
Labels: cla-signed

#9056 [move-prover] algorithm for progressive instantiation
  language/move-model/src/ty.rs
Labels: cla-signed

#9052 [move-prover] dump bytecode and result in output dir
  language/move-prover/src/lib.rs
Labels: cla-signed

#9079 [diem-framework] Port `DiemTimestamp` to unit tests
  language/diem-framework/tests/DiemTimestampTests.move
  language/move-lang/functional-tests/tests/diem/diem_timestamp/basic.move
Labels: cla-signed

#9077 [move-prover] an instrumentation pass for the global invariants
  language/move-prover/bytecode/src/global_invariant_analysis.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/src/cli.rs
Labels: cla-signed

#9096 [decoupled-execution] add linked list for the buffer manager.
  consensus/src/experimental/linkedlist.rs
  consensus/src/experimental/mod.rs
Labels: cla-signed

#9091 incorporate christy's comments
  developers.diem.com/docs/governance.mdx
  developers.diem.com/docs/welcome-to-diem.mdx
Labels: cla-signed

#9103 [decoupled-execution] process incoming ordered blocks and sync requests
  consensus/src/experimental/buffer_manager.rs
  consensus/src/experimental/commit_phase.rs
  consensus/src/experimental/ordering_state_computer.rs
  consensus/src/experimental/tests/commit_phase_tests.rs
  consensus/src/experimental/tests/ordering_state_computer_tests.rs
  consensus/src/experimental/tests/test_utils.rs
Labels: cla-signed

#9112 [docker] update base image to debian:buster-20210902
  docker/ci/github/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/faucet/Dockerfile
  docker/forge/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
Labels: cla-signed

#9118 Fix broken doc link
  developers.diem.com/docs/technical-papers/publication-archive.mdx
  developers.diem.com/docs/technical-papers/state-machine-replication-paper.md
Labels: cla-signed

#9100 ci: use Swatinem/rust-cache for caching dependencies
  .github/actions/build-teardown/action.yml
  .github/workflows/ci-test.yml
Labels: cla-signed

#9122 [State Sync] Small cleanups to notification listener tests.
  state-sync/inter-component/consensus-notifications/src/lib.rs
  state-sync/inter-component/mempool-notifications/src/lib.rs
Labels: cla-signed

#9115 [language][diem-framework] migrate registered currency tests
  language/diem-framework/tests/RegisteredCurrencyTests.move
  language/move-lang/functional-tests/tests/diem/registered_currencies/basic.move
Labels: cla-signed

#9125 [docker] fix up base image for DLC
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/forge/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#9128 json-rpc: implement missing MockDB methods to fix fuzzer
  json-rpc/src/fuzzing.rs
  json-rpc/src/tests/utils.rs
Labels: cla-signed

#9133 [network] Fix JSON consensus protocol name
  network/src/protocols/wire/handshake/v1/mod.rs
Labels: cla-signed

#9126 [decoupled-execution] buffer manager execution phase logic
  consensus/src/experimental/buffer_item.rs
  consensus/src/experimental/buffer_manager.rs
  consensus/src/experimental/execution_phase.rs
  consensus/src/experimental/linkedlist.rs
  consensus/src/experimental/mod.rs
  consensus/src/experimental/persisting_phase.rs
  consensus/src/experimental/pipeline_phase.rs
  consensus/src/experimental/signing_phase.rs
  consensus/src/experimental/tests/execution_phase_tests.rs
Labels: cla-signed

#9039 [Forge] Add forge LBT in ci-test
  .github/workflows/ci-test.yml
  docker/build_push.sh
  scripts/fgi/kube.py
  scripts/fgi/run
  testsuite/forge/src/txn_emitter/mod.rs
Labels: cla-signed

#9127 Cherry-pick PR #9119 into release-1.4: [reconfiguration] another attempt to fix the bug and better test cove…
  consensus/consensus-types/src/block_data.rs
  consensus/consensus-types/src/executed_block.rs
  consensus/src/network.rs
  consensus/src/round_manager.rs
  testsuite/forge/src/backend/local/cargo.rs
Labels: bors-high-priority

#9148 [decoupled-execution] add signing / aggregating logic
  consensus/src/experimental/buffer_item.rs
  consensus/src/experimental/buffer_manager.rs
  consensus/src/experimental/execution_phase.rs
  consensus/src/experimental/signing_phase.rs
Labels: cla-signed

#9154 [move-prover] Implement spec (ghost) vars by mapping them to regular memory.
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/parser/syntax.rs
  language/move-model/src/ast.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/builder/model_builder.rs
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/exp_generator.rs
  language/move-model/src/exp_rewriter.rs
  language/move-model/src/lib.rs
  language/move-model/src/model.rs
  language/move-model/src/spec_translator.rs
  language/move-model/src/ty.rs
  language/move-model/tests/sources/invariants_err.exp
  language/move-model/tests/testsuite.rs
  language/move-prover/boogie-backend/src/boogie_helpers.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/access_path.rs
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/tests/spec_instrumentation/fun_spec.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
  language/move-prover/bytecode/tests/usage_analysis/test.exp
  language/move-prover/interpreter/src/concrete/evaluator.rs
  language/move-prover/tests/sources/functional/global_vars.exp
  language/move-prover/tests/sources/functional/global_vars.move
Labels: cla-signed, bors-squash

#9114 [language][diem-framework] migrate authenticator tests
  language/diem-framework/tests/AuthenticatorTests.move
  language/move-lang/functional-tests/tests/diem/authenticator/authenticator.exp
  language/move-lang/functional-tests/tests/diem/authenticator/authenticator.move
Labels: cla-signed

#9174 [move-prover] warn on unused global invariants
  language/move-prover/bytecode/src/verification_analysis.rs
  language/move-prover/tests/sources/functional/unused_global_invariant.exp
  language/move-prover/tests/sources/functional/unused_global_invariant.move
Labels: cla-signed

#9178 [decoupled-execution] buffer manager main loop logic (w/o message retry)
  consensus/src/experimental/buffer_manager.rs
  consensus/src/experimental/execution_phase.rs
  consensus/src/experimental/persisting_phase.rs
  consensus/src/experimental/pipeline_phase.rs
  consensus/src/experimental/tests/execution_phase_tests.rs
Labels: cla-signed

#9181 logger: allow configuring what logs get sent to the remote logging service
  common/logger/src/diem_logger.rs
  common/logger/tests/remote.rs
Labels: cla-signed

#9184 [forge] extend waiting time for node recovery to catch up peers
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: cla-signed

#9175 [move-lang] Don't stop at first parser error
  language/move-lang/src/command_line/compiler.rs
  language/move-lang/src/diagnostics/codes.rs
  language/move-lang/src/parser/lexer.rs
  language/move-lang/src/parser/mod.rs
  language/move-lang/src/parser/syntax.rs
  language/move-lang/tests/move_check/expansion/unpack_all_field_cases.exp
  language/move-lang/tests/move_check/expansion/unpack_all_field_cases.move
  language/move-lang/tests/move_check/parser/address_too_long_decimal_exp.exp
  language/move-lang/tests/move_check/parser/address_too_long_exp.exp
  language/move-lang/tests/move_check/parser/doc_comments_placement.exp
  language/move-lang/tests/move_check/parser/doc_comments_placement.move
  language/move-lang/tests/move_check/parser/native_main.exp
  language/move-lang/tests/move_check/translated_ir_tests/move/commands/mixed_lvalue.exp
  language/move-lang/tests/move_check/translated_ir_tests/move/commands/mixed_lvalue.move
  language/move-lang/tests/move_check/typing/assign_nested.exp
  language/move-lang/tests/move_check/typing/assign_nested.move
Labels: cla-signed

#9197 [move-prover] Changes to report
  language/move-prover/doc/report/arch.tex
  language/move-prover/doc/report/injection.tex
  language/move-prover/doc/report/main.pdf
  language/move-prover/doc/report/move.tex
  language/move-prover/doc/report/references.tex
Labels: cla-signed, move-prover

#9171 [diemdb] add transaction_by_hash cf
  storage/diemdb/src/lib.rs
  storage/diemdb/src/schema/mod.rs
  storage/diemdb/src/schema/transaction_by_hash/mod.rs
  storage/diemdb/src/schema/transaction_by_hash/test.rs
Labels: cla-signed

#9192 Cherry-pick PR #9181 into release-1.4: logger: allow configuring what logs get sent to the remote logging service
  common/logger/src/diem_logger.rs
  common/logger/tests/remote.rs
Labels: cla-signed

#9208 [move-prover] Do not generate or use inline attr for uninterpreted functions
  language/move-prover/boogie-backend/src/prelude/prelude.bpl
  language/move-prover/boogie-backend/src/spec_translator.rs
Labels: cla-signed

#9207 [decoupled-execution] process_sync_req now tries to advance a buffer item to aggregated
  consensus/src/experimental/buffer_item.rs
  consensus/src/experimental/buffer_manager.rs
Labels: cla-signed

#9215 [move-prover] Move generation of well-formed assumptions into its own processor
  language/move-prover/bytecode/src/function_data_builder.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/pipeline_factory.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/src/well_formed_instrumentation.rs
  language/move-prover/bytecode/tests/global_invariant_analysis/disable_in_body.exp
  language/move-prover/bytecode/tests/global_invariant_analysis/mutual_inst.exp
  language/move-prover/bytecode/tests/global_invariant_analysis/uninst_type_param_in_inv.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/move.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/update.exp
  language/move-prover/bytecode/tests/spec_instrumentation/fun_spec.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/tests/sources/functional/aborts_if_with_code.exp
  language/move-prover/tests/sources/functional/address_serialization_constant_size.exp
  language/move-prover/tests/sources/functional/choice.cvc4_exp
  language/move-prover/tests/sources/functional/choice.exp
  language/move-prover/tests/sources/functional/global_vars.exp
  language/move-prover/tests/sources/functional/global_vars.move
  language/move-prover/tests/sources/functional/global_vars.no_opaque_exp
  language/move-prover/tests/sources/functional/hash_model.cvc4_exp
  language/move-prover/tests/sources/functional/hash_model.exp
  language/move-prover/tests/sources/functional/hash_model_invalid.exp
  language/move-prover/tests/sources/functional/invariants_resources.cvc4_exp
  language/move-prover/tests/sources/functional/invariants_resources.exp
  language/move-prover/tests/sources/functional/mono.cvc4_exp
  language/move-prover/tests/sources/functional/mono.exp
  language/move-prover/tests/sources/functional/mut_ref.exp
  language/move-prover/tests/sources/functional/schema_exp.exp
  language/move-prover/tests/sources/functional/serialize_model.cvc4_exp
  language/move-prover/tests/sources/functional/serialize_model.exp
  language/move-prover/tests/sources/functional/verify_vector.cvc4_exp
Labels: cla-signed, bors-squash

#9216 [tools][dataflow] Add node type specifications; misc improvements
  language/tools/mirai-dataflow-analysis/README.md
  language/tools/mirai-dataflow-analysis/rust-toolchain
  language/tools/mirai-dataflow-analysis/src/configuration.rs
  language/tools/mirai-dataflow-analysis/src/datalog.rs
  language/tools/mirai-dataflow-analysis/src/ddlog_output.rs
  language/tools/mirai-dataflow-analysis/src/lib.rs
  language/tools/mirai-dataflow-analysis/src/main.rs
  language/tools/mirai-dataflow-analysis/src/souffle_output.rs
Labels: cla-signed

#9217 [language] Refactor BoundsChecker::verify_impl for MIRAI analysis
  language/move-binary-format/src/check_bounds.rs
Labels: cla-signed, bors-squash

#9234 [docker] add experimental move bytecode
  docker/init/Dockerfile
  docker/tools/Dockerfile
Labels: cla-signed

#9225 [mempool/state-sync] Make PeerNetworkId copyable
  config/src/config/upstream_config.rs
  mempool/src/shared_mempool/coordinator.rs
  mempool/src/shared_mempool/peer_manager.rs
  mempool/src/shared_mempool/tasks.rs
  mempool/src/shared_mempool/types.rs
  state-sync/state-sync-v1/src/coordinator.rs
  state-sync/state-sync-v1/src/request_manager.rs
Labels: cla-signed

#9238 [move-prover][paper] Extracting paper from tech report.
  language/move-prover/doc/paper21/analysis.tex
  language/move-prover/doc/paper21/arch.png
  language/move-prover/doc/paper21/biblio.bib
  language/move-prover/doc/paper21/conclusion.tex
  language/move-prover/doc/paper21/design.tex
  language/move-prover/doc/paper21/function-injection-apx.tex
  language/move-prover/doc/paper21/intro.tex
  language/move-prover/doc/paper21/llncs.cls
  language/move-prover/doc/paper21/main.pdf
  language/move-prover/doc/paper21/main.tex
  language/move-prover/doc/paper21/move.tex
  language/move-prover/doc/paper21/prelude.tex
  language/move-prover/doc/paper21/references-apx.tex
  language/move-prover/doc/paper21/splncs04.bst
Labels: cla-signed

#9239 [move-prover] Generate the backward call graphs for the Diem Framework documentation
  language/move-prover/docgen/src/docgen.rs
Labels: cla-signed, move-prover

#9250 [tools][mirai-dataflow] Dataflow analysis examples and configuration
  language/tools/mirai-dataflow-analysis/README.md
  language/tools/mirai-dataflow-analysis/analyses/ddlog.dl
  language/tools/mirai-dataflow-analysis/analyses/souffle.dl
  language/tools/mirai-dataflow-analysis/config/BoundsChecker_config.json
  language/tools/mirai-dataflow-analysis/config/CompiledModule_type_relations.json
  language/tools/mirai-dataflow-analysis/config/DuplicationChecker_config.json
  language/tools/mirai-dataflow-analysis/examples/BoundsChecker.md
  language/tools/mirai-dataflow-analysis/examples/DuplicationChecker.md
  language/tools/mirai-dataflow-analysis/examples/examples.md
Labels: cla-signed, bors-squash

#9243 [test-infra][e2e] make sure to test until the latest DiemVersion
  language/e2e-testsuite/src/tests/emergency_admin_script.rs
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__emergency_admin_script__halt_network_version_3.exp
  language/testing-infra/e2e-tests/src/versioning.rs
Labels: cla-signed

#9256 [api] get account modules
  api/src/accounts.rs
  api/src/test_utils.rs
  api/types/Cargo.toml
  api/types/src/address.rs
  api/types/src/error.rs
  api/types/src/lib.rs
  api/types/src/move_types.rs
Labels: cla-signed

#9262 [api] first draft version api blueprint document for implemented API
  api/README.md
  api/blueprint.apib
  api/dredd.yml
Labels: cla-signed

#8807 [prover] escape analysis to detect leaks of module-internal references
  language/move-model/src/ast.rs
  language/move-model/src/model.rs
  language/move-prover/bytecode/src/escape_analysis.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/tests/escape_analysis/global_spec_relevance.exp
  language/move-prover/bytecode/tests/escape_analysis/global_spec_relevance.move
  language/move-prover/bytecode/tests/escape_analysis/global_struct_eq.exp
  language/move-prover/bytecode/tests/escape_analysis/global_struct_eq.move
  language/move-prover/bytecode/tests/escape_analysis/return_internal_refs.exp
  language/move-prover/bytecode/tests/escape_analysis/return_internal_refs.move
  language/move-prover/bytecode/tests/escape_analysis/return_refs_into_vec.exp
  language/move-prover/bytecode/tests/escape_analysis/return_refs_into_vec.move
  language/move-prover/bytecode/tests/escape_analysis/return_refs_safe.exp
  language/move-prover/bytecode/tests/escape_analysis/return_refs_safe.move
  language/move-prover/bytecode/tests/escape_analysis/struct_eq.exp
  language/move-prover/bytecode/tests/escape_analysis/struct_eq.move
  language/move-prover/bytecode/tests/escape_analysis/struct_spec_relevance.exp
  language/move-prover/bytecode/tests/escape_analysis/struct_spec_relevance.move
  language/move-prover/bytecode/tests/escape_analysis/vec_eq.exp
  language/move-prover/bytecode/tests/escape_analysis/vec_eq.move
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
Labels: cla-signed

#9294 [forge] make genesis always uses pr tag image
  testsuite/forge/src/backend/k8s/mod.rs
Labels: cla-signed

#9298 [forge] change compatibility test suite start with older version
  testsuite/forge-cli/src/lib.rs
  testsuite/forge-cli/src/main.rs
  testsuite/forge/src/backend/k8s/mod.rs
  testsuite/forge/src/backend/k8s/swarm.rs
Labels: cla-signed
