Repository diem/diem, pull requests merged in 2021-04, with the labels that each got.

#8102 [lbt] add missing checkout step in image lookup
  .github/workflows/ci-test.yml
Labels: bors-high-priority, cla-signed

#8104 [gha] use standard cargo
  .github/workflows/daily.yml
Labels: cla-signed

#8100 describes off-chain identity for transactions
  specifications/transactions/README.md
  specifications/transactions/offchain-identity/README.md
Labels: cla-signed

#8106 [gha] more cargo/rustc version cleanup
  .github/actions/build-setup/action.yml
  .github/workflows/ci-publish-base-image.yml
  x.toml
Labels: cla-signed

#7966 [Configs] Remove UpstreamConfig.
  config/src/config/mod.rs
  config/src/config/test_data/public_full_node.yaml
  config/src/config/test_data/validator_full_node.yaml
  config/src/config/upstream_config.rs
  docker/compose/public_full_node/public_full_node.yaml
  helm/fullnode/files/fullnode.yaml
  mempool/src/counters.rs
  state-sync/tests/integration_tests.rs
  state-sync/tests/test_harness.rs
  testsuite/cluster-test/src/cluster_swarm/configs/fullnode.yaml
Labels: cla-signed

#8103 [network] Add connection limit metrics
  network/src/counters.rs
  network/src/peer_manager/mod.rs
Labels: cla-signed, network

#8110 [language] remove `compiled-stdlib` from the move-to-diem dependency check list
  x.toml
Labels: cla-signed

#8109 [sdk] use symbolic link for generated file
  language/diem-framework/releases/artifacts/current/transaction_script_builder.rs
  language/transaction-builder/generator/src/rust.rs
  sdk/transaction-builder/src/stdlib.rs
Labels: cla-signed

#8113 ci: run the sdk-compatability test from the release branch against main
  .github/workflows/ci-test.yml
  Cargo.lock
  Cargo.toml
  sdk/compatibility/Cargo.toml
  sdk/compatibility/src/env.rs
  sdk/compatibility/src/lib.rs
  x.toml
Labels: cla-signed

#8111 [language][prover] remove diem-types as a dependency from stackless bytecode
  Cargo.lock
  language/move-prover/bytecode/Cargo.toml
  language/move-prover/bytecode/src/packed_types_analysis.rs
  x.toml
Labels: cla-signed

#8120 [gha] use latest version of actions
  .github/workflows/dep-summaries.yml
  .github/workflows/hyperjump-comment.yml
  .github/workflows/hyperjump-labels.yml
  .github/workflows/hyperjump-request-review.yml
  .github/workflows/jsonrpc-compat.yml
Labels: cla-signed

#8116 [move-lang] use destruction pattern consistently for ModuleDefinition
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/typing/translate.rs
Labels: cla-signed

#8117 [cluster-test] Fix invalid dashboard link
  testsuite/cluster-test/src/prometheus.rs
Labels: cla-signed, cluster_test

#8123 [scratchpad] iterative drop
  storage/scratchpad/src/sparse_merkle/mod.rs
  storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
Labels: cla-signed

#8128 [disassembler] format abilities, deprecate kind
  language/tools/disassembler/src/disassembler.rs
Labels: cla-signed

#8114 [language] remove unused diem-types dependency from disassembler
  Cargo.lock
  language/tools/disassembler/Cargo.toml
  x.toml
Labels: cla-signed

#8142 [network] Remove rate-limit key from metrics
  network/src/counters.rs
Labels: bug-fix, cla-signed, network

#8147 correct typo in node.rs
  storage/scratchpad/src/sparse_merkle/node.rs
Labels: cla-signed

#8135 travel rule spec
  specifications/transactions/README.md
  specifications/transactions/travel-rule/README.md
  specifications/transactions/travel-rule/flow.png
Labels: cla-signed

#8153 [gha] fix typo in env
  .github/workflows/docker-publish.yml
Labels: cla-signed

#8149 [cluster-test] let CT has ability to support new feature of script fu…
  Cargo.lock
  testsuite/cluster-test/Cargo.toml
  testsuite/cluster-test/src/experiments/reconfiguration_test.rs
  testsuite/cluster-test/src/tx_emitter.rs
Labels: cla-signed

#8146 [cherry-pick][network] Fix rate limit metrics
  network/src/counters.rs
Labels: cla-signed

#8154 [move-model] replace TypeConstraint with AbilityConstraint
  language/diem-framework/releases/artifacts/current/docs/modules/AccountAdministrationScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/AccountCreationScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/AccountLimits.md
  language/diem-framework/releases/artifacts/current/docs/modules/DesignatedDealer.md
  language/diem-framework/releases/artifacts/current/docs/modules/Diem.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemConfig.md
  language/diem-framework/releases/artifacts/current/docs/modules/DualAttestation.md
  language/diem-framework/releases/artifacts/current/docs/modules/PaymentScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/TransactionFee.md
  language/diem-framework/releases/artifacts/current/docs/modules/TreasuryComplianceScripts.md
  language/diem-framework/releases/artifacts/current/docs/modules/VASP.md
  language/diem-framework/releases/artifacts/current/docs/modules/XDX.md
  language/diem-framework/releases/artifacts/current/docs/scripts/script_documentation.md
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/model.rs
  language/move-prover/docgen/src/docgen.rs
  language/move-prover/docgen/tests/sources/DiemTest.spec_inline.md
  language/move-prover/docgen/tests/sources/DiemTest.spec_inline_no_fold.md
  language/move-prover/docgen/tests/sources/DiemTest.spec_separate.md
  language/move-stdlib/docs/Event.md
  language/move-stdlib/docs/Option.md
Labels: cla-signed

#8139 [move-lang] Add CompilationEnv to passes in the compiler
  language/benchmarks/src/move_vm.rs
  language/diem-framework/src/lib.rs
  language/diem-tools/transaction-replay/src/lib.rs
  language/diem-tools/writeset-transaction-generator/src/admin_script_builder.rs
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/bin/move-build.rs
  language/move-lang/src/bin/move-check.rs
  language/move-lang/src/cfgir/borrows/mod.rs
  language/move-lang/src/cfgir/liveness/mod.rs
  language/move-lang/src/cfgir/locals/mod.rs
  language/move-lang/src/cfgir/mod.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/command_line/mod.rs
  language/move-lang/src/errors/mod.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/shared/mod.rs
  language/move-lang/src/to_bytecode/translate.rs
  language/move-lang/src/typing/core.rs
  language/move-lang/src/typing/expand.rs
  language/move-lang/src/typing/globals.rs
  language/move-lang/src/typing/infinite_instantiations.rs
  language/move-lang/src/typing/recursive_structs.rs
  language/move-lang/src/typing/translate.rs
  language/move-lang/tests/move_check_testsuite.rs
  language/move-lang/tests/stdlib_sanity_check.rs
  language/move-model/src/lib.rs
  language/move-vm/integration-tests/src/compiler.rs
  language/tools/move-cli/src/main.rs
  language/tools/move-cli/src/package.rs
Labels: cla-signed

#8165 [dev docs] clarify local network instructions
  developers.diem.com/docs/core/run-local-network.md
Labels: cla-signed

#8160 [language] remove unused dependency on diem-types from move-vm-runtime
  Cargo.lock
  language/move-vm/runtime/Cargo.toml
Labels: cla-signed

#8163 [diem framework] remove DiemAccount::destroy_signer + associated nati…
  language/diem-framework/modules/DiemAccount.move
  language/diem-framework/releases/artifacts/current/docs/modules/DiemAccount.md
  language/diem-framework/releases/artifacts/current/modules/028_DiemAccount.mv
  language/move-prover/boogie-backend/src/prelude/prelude.bpl
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-vm/natives/src/account.rs
  language/move-vm/runtime/src/native_functions.rs
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__account_limits__account_limits_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__create_account__create_account_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__emergency_admin_script__validator_batch_remove_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__mint__mint_to_existing_not_dd_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__mint__tiered_mint_designated_dealer_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__add_child_currencies_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__create_child_vasp_all_currencies_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__create_child_vasp_with_balance_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__create_parent_and_child_vasp_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__dd_dual_attestation_payments_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__dual_attestation_payment_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__freeze_unfreeze_account_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__recovery_address_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_fees__burn_txn_fees_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_add_max_number.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_add_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_rotate_key_and_reconfigure_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__validator_set_management__validator_set_operator_set_key_reconfigure_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__vasps__max_child_accounts_for_vasp_recovery_address_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__vasps__valid_creator_already_vasp_version_2.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__verify_txn__publish_and_register_new_currency.exp
Labels: cla-signed

#8171 [cluster-test] disable debug log in LBT test
  .github/workflows/ci-test.yml
Labels: bors-high-priority, cla-signed

#8174 [move-prover] Enable some cvc4 functional tests.
  .github/actions/build-setup/action.yml
  Cargo.lock
  docker/ci/github/Dockerfile
  language/move-prover/Cargo.toml
  language/move-prover/boogie-backend/src/boogie_wrapper.rs
  language/move-prover/boogie-backend/src/options.rs
  language/move-prover/src/lib.rs
  language/move-prover/tests/README.md
  language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if.move
  language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if_with_code.move
  language/move-prover/tests/sources/functional/address_quant.cvc4_exp
  language/move-prover/tests/sources/functional/address_quant.move
  language/move-prover/tests/sources/functional/arithm.cvc4_exp
  language/move-prover/tests/sources/functional/arithm.move
  language/move-prover/tests/sources/functional/cast.cvc4_exp
  language/move-prover/tests/sources/functional/cast.move
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#8175 [move-model] bytecode-agnostic exp generator and spec translator
  language/move-model/src/exp_generator.rs
  language/move-model/src/lib.rs
  language/move-model/src/spec_translator.rs
  language/move-prover/bytecode/src/data_invariant_instrumentation.rs
  language/move-prover/bytecode/src/debug_instrumentation.rs
  language/move-prover/bytecode/src/function_data_builder.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/loop_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
Labels: cla-signed

#8176 [move-prover] Fixes a bug with empty struct pack in the spec language
  language/move-model/src/builder/exp_translator.rs
  language/move-prover/tests/sources/functional/resources.move
Labels: cla-signed

#8168 [gha] add LBT KS
  .github/workflows/ci-test.yml
Labels: cla-signed

#8173 remove unused diem-trace crate
  Cargo.lock
  Cargo.toml
  common/trace/Cargo.toml
  common/trace/src/counters.rs
  common/trace/src/lib.rs
  common/trace/src/main.rs
  common/trace/src/trace.rs
  config/src/config/debug_interface_config.rs
  consensus/Cargo.toml
  consensus/src/block_storage/block_store.rs
  consensus/src/persistent_liveness_storage.rs
  consensus/src/round_manager.rs
  consensus/src/txn_manager.rs
  diem-node/Cargo.toml
  diem-node/src/lib.rs
  execution/executor/Cargo.toml
  execution/executor/src/lib.rs
  json-rpc/Cargo.toml
  json-rpc/src/methods.rs
  language/diem-vm/Cargo.toml
  language/diem-vm/src/diem_transaction_executor.rs
  mempool/Cargo.toml
  mempool/src/core_mempool/mempool.rs
  mempool/src/shared_mempool/coordinator.rs
  testsuite/cluster-test/Cargo.toml
  testsuite/cluster-test/src/experiments/mod.rs
  testsuite/cluster-test/src/experiments/performance_benchmark.rs
  testsuite/cluster-test/src/health/debug_interface_log_tail.rs
  testsuite/cluster-test/src/health/log_tail.rs
  testsuite/cluster-test/src/health/mod.rs
  testsuite/cluster-test/src/main.rs
  testsuite/smoke-test/Cargo.toml
  testsuite/smoke-test/src/client.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#8190 [gha] rename lbt switches and rework its workflow ctrl
  .github/workflows/ci-test.yml
Labels: cla-signed

#8192 [diem-framework] Fix issues with documentation generation and broken links
  language/diem-framework/modules/doc/AccountAdministrationScripts.md
  language/diem-framework/modules/doc/AccountCreationScripts.md
  language/diem-framework/modules/doc/AccountFreezing.md
  language/diem-framework/modules/doc/AccountLimits.md
  language/diem-framework/modules/doc/Authenticator.md
  language/diem-framework/modules/doc/ChainId.md
  language/diem-framework/modules/doc/CoreAddresses.md
  language/diem-framework/modules/doc/DesignatedDealer.md
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/modules/doc/DiemBlock.md
  language/diem-framework/modules/doc/DiemConfig.md
  language/diem-framework/modules/doc/DiemConsensusConfig.md
  language/diem-framework/modules/doc/DiemSystem.md
  language/diem-framework/modules/doc/DiemTimestamp.md
  language/diem-framework/modules/doc/DiemTransactionPublishingOption.md
  language/diem-framework/modules/doc/DiemVMConfig.md
  language/diem-framework/modules/doc/DiemVersion.md
  language/diem-framework/modules/doc/DualAttestation.md
  language/diem-framework/modules/doc/Genesis.md
  language/diem-framework/modules/doc/PaymentScripts.md
  language/diem-framework/modules/doc/RecoveryAddress.md
  language/diem-framework/modules/doc/RegisteredCurrencies.md
  language/diem-framework/modules/doc/Roles.md
  language/diem-framework/modules/doc/SharedEd25519PublicKey.md
  language/diem-framework/modules/doc/Signature.md
  language/diem-framework/modules/doc/SlidingNonce.md
  language/diem-framework/modules/doc/SystemAdministrationScripts.md
  language/diem-framework/modules/doc/TransactionFee.md
  language/diem-framework/modules/doc/TreasuryComplianceScripts.md
  language/diem-framework/modules/doc/VASP.md
  language/diem-framework/modules/doc/ValidatorAdministrationScripts.md
  language/diem-framework/modules/doc/ValidatorConfig.md
  language/diem-framework/modules/doc/ValidatorOperatorConfig.md
  language/diem-framework/modules/doc/XDX.md
  language/diem-framework/modules/doc/XUS.md
  language/diem-framework/modules/doc/overview.md
  language/diem-framework/script_documentation/script_documentation.md
  language/diem-framework/script_documentation/spec_documentation.md
  language/diem-framework/src/main.rs
  language/diem-framework/src/release.rs
Labels: cla-signed

#8180 [move-lang] make sources_shadow_deps part of parsing
  language/move-lang/functional-tests/tests/functional_testsuite.rs
  language/move-lang/src/lib.rs
  language/move-model/src/lib.rs
Labels: cla-signed

#8179 [move-model] relocate model building logic fully to move model
  Cargo.lock
  language/move-model/src/lib.rs
  language/move-model/tests/testsuite.rs
  language/move-prover/Cargo.toml
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/lab/src/benchmark.rs
  language/move-prover/src/lib.rs
Labels: cla-signed

#8194 [docker] debian base image update
  docker/ci/github/Dockerfile
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/faucet/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#8191 forge: new unified e2e testing framework
  Cargo.lock
  Cargo.toml
  common/workspace-hack/Cargo.toml
  sdk/src/types.rs
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/k8s.rs
  testsuite/forge/src/backend/local.rs
  testsuite/forge/src/backend/mod.rs
  testsuite/forge/src/interface/admin.rs
  testsuite/forge/src/interface/factory.rs
  testsuite/forge/src/interface/mod.rs
  testsuite/forge/src/interface/network.rs
  testsuite/forge/src/interface/node.rs
  testsuite/forge/src/interface/public.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/forge/src/interface/test.rs
  testsuite/forge/src/lib.rs
  testsuite/forge/src/runner.rs
  testsuite/forge/tests/fire.rs
  x.toml
Labels: cla-signed

#8172 [Cluster Test] Add state sync performance test to new_pre_release suite
  testsuite/cluster-test/src/suite.rs
Labels: cla-signed

#8207 sdk: use correct response types in experimental proof API's
  client/json-rpc/src/broadcast_client.rs
  sdk/client/src/client.rs
Labels: cla-signed

#8210 [Cluster Test] Update the state sync benchmark to format the throughput displayed.
  testsuite/cluster-test/src/experiments/state_sync_performance.rs
Labels: cla-signed

#8169 [move-lang] Attributes
  language/move-lang/src/cfgir/ast.rs
  language/move-lang/src/cfgir/translate.rs
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/hlir/ast.rs
  language/move-lang/src/hlir/translate.rs
  language/move-lang/src/lib.rs
  language/move-lang/src/naming/ast.rs
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/parser/lexer.rs
  language/move-lang/src/parser/syntax.rs
  language/move-lang/src/to_bytecode/translate.rs
  language/move-lang/src/typing/ast.rs
  language/move-lang/src/typing/core.rs
  language/move-lang/src/typing/translate.rs
  language/move-lang/tests/move_check/expansion/friend_decl_aliased_duplicates.exp
  language/move-lang/tests/move_check/expansion/friend_decl_imported_duplicates.exp
  language/move-lang/tests/move_check/expansion/friend_decl_qualified_duplicates.exp
  language/move-lang/tests/move_check/parser/attribute_no_closing_bracket.exp
  language/move-lang/tests/move_check/parser/attribute_no_closing_bracket.move
  language/move-lang/tests/move_check/parser/attribute_num_sign_no_bracket.exp
  language/move-lang/tests/move_check/parser/attribute_num_sign_no_bracket.move
  language/move-lang/tests/move_check/parser/attribute_placement.move
  language/move-lang/tests/move_check/parser/attribute_variants.move
  language/move-model/src/lib.rs
Labels: cla-signed

#8204 [cluster-test] deprecate accountData in CT
  sdk/src/transaction_builder.rs
  sdk/src/types.rs
  testsuite/cluster-test/src/experiments/load_test.rs
  testsuite/cluster-test/src/experiments/reconfiguration_test.rs
  testsuite/cluster-test/src/experiments/versioning_test.rs
  testsuite/cluster-test/src/main.rs
  testsuite/cluster-test/src/tx_emitter.rs
  testsuite/forge/src/backend/local.rs
Labels: cla-signed, cluster_test

#8213 [move-prover] Representing memory as structs with type instantiation in model and bytecode
  language/move-model/src/ast.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/builder/model_builder.rs
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/exp_generator.rs
  language/move-model/src/model.rs
  language/move-model/src/spec_translator.rs
  language/move-model/src/ty.rs
  language/move-prover/boogie-backend-exp/src/boogie_helpers.rs
  language/move-prover/boogie-backend-exp/src/bytecode_translator.rs
  language/move-prover/boogie-backend-exp/src/spec_translator.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/function_target.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation_v2.rs
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/src/verification_analysis.rs
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/bytecode/tests/usage_analysis/test.exp
  language/move-prover/bytecode/tests/usage_analysis/test.move
  language/move-prover/lab/data/struct-as-adt/notebook.ipynb
  language/move-prover/lab/data/struct-as-adt/notebook.pdf
  language/move-prover/lab/data/struct-as-adt/struct_as_adt.fun_data
  language/move-prover/lab/data/struct-as-adt/struct_as_adt.mod_data
  language/move-prover/lab/data/struct-as-adt/struct_as_vec.fun_data
  language/move-prover/lab/data/struct-as-adt/struct_as_vec.mod_data
Labels: cla-signed

#8215 [smt] Parallelize smt batch update with rayon::join
  Cargo.lock
  storage/scratchpad/Cargo.toml
  storage/scratchpad/src/sparse_merkle/mod.rs
  storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#8216 [docker] deprecate vcs-upstream label
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/diem-build.sh
  docker/faucet/Dockerfile
  docker/init/Dockerfile
  docker/tag-and-push.sh
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#8222 [move-prover] Add a test for checking parse errors.
  language/move-prover/tests/sources/functional/parse_error.exp
  language/move-prover/tests/sources/functional/parse_error.move
Labels: cla-signed

#8221 forge: add more methods to the Swarm and Node traits
  Cargo.lock
  testsuite/forge/Cargo.toml
  testsuite/forge/src/backend/local.rs
  testsuite/forge/src/interface/node.rs
  testsuite/forge/src/interface/swarm.rs
  testsuite/forge/src/main.rs
Labels: cla-signed

#8225 [smt] added missed rayon::join() and some fixes
  storage/scratchpad-benchmark/src/main.rs
  storage/scratchpad/src/sparse_merkle/mod.rs
  storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
Labels: cla-signed

#8226 [datatest-stable] use version from crates.io
  Cargo.lock
  Cargo.toml
  common/datatest-stable/Cargo.toml
  common/datatest-stable/src/lib.rs
  common/datatest-stable/src/macros.rs
  common/datatest-stable/src/runner.rs
  common/datatest-stable/src/utils.rs
  common/datatest-stable/tests/example.rs
  common/datatest-stable/tests/files/a
  common/datatest-stable/tests/files/b
  language/diem-framework/Cargo.toml
  language/ir-testsuite/Cargo.toml
  language/move-lang/Cargo.toml
  language/move-lang/functional-tests/Cargo.toml
  language/move-lang/test-utils/Cargo.toml
  language/move-lang/test-utils/src/lib.rs
  language/move-model/Cargo.toml
  language/move-prover/Cargo.toml
  language/move-prover/abigen/Cargo.toml
  language/move-prover/bytecode/Cargo.toml
  language/move-prover/docgen/Cargo.toml
  language/move-prover/errmapgen/Cargo.toml
  language/move-prover/lab/Cargo.toml
  language/testing-infra/functional-tests/Cargo.toml
  language/tools/move-cli/Cargo.toml
  testsuite/diem-fuzzer/Cargo.toml
  x.toml
Labels: bors-high-priority, cla-signed

#8232 [dkr] restore script needed in buildspec
  docker/tag-and-push.sh
Labels: cla-signed

#8224 [move-cli] refactoring to separate cli and library logic
  Cargo.lock
  language/diem-tools/transaction-replay/src/lib.rs
  language/tools/move-cli/Cargo.toml
  language/tools/move-cli/src/commands.rs
  language/tools/move-cli/src/lib.rs
  language/tools/move-cli/src/main.rs
  language/tools/move-cli/src/mode.rs
  language/tools/move-cli/src/on_disk_state_view.rs
  language/tools/move-cli/src/package.rs
Labels: cla-signed

#8228 [language] add Move release notes for version 1.2
  CHANGELOG/CHANGELOG-1.2.md
  language/RELEASES.md
Labels: cla-signed

#8214 [move-lang][move-model] selective compilation for move-model building
  language/move-lang/src/expansion/ast.rs
  language/move-lang/src/expansion/dependency_ordering.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/naming/translate.rs
  language/move-model/src/lib.rs
Labels: cla-signed

#8238 [gha] use matches and changes actions from diem/actions
  .github/actions/changes/action.yml
  .github/actions/changes/get_pr_info.sh
  .github/actions/changes/readme.md
  .github/actions/matches/action.yml
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test.yml
  .github/workflows/ci-update-sccache.yml
  .github/workflows/docker-publish.yml
Labels: cla-signed

#8240 [read/write set analysis] Use FunctionEnv instead of FunctionTarget i…
  language/move-prover/bytecode/src/access_path.rs
  language/move-prover/bytecode/src/access_path_trie.rs
  language/move-prover/bytecode/src/read_write_set_analysis.rs
Labels: cla-signed

#8217 [gha] create issue for RUSTSEC found in audit
  .github/workflows/daily.yml
Labels: cla-signed

#8243 [move prover] CompositionalAnalysis::summarize returns a Summary
  language/move-prover/bytecode/src/compositional_analysis.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-prover/bytecode/src/usage_analysis.rs
Labels: cla-signed

#8252 [move-lang] ensure that `dependency_order` is unique for each module
  language/move-lang/src/expansion/dependency_ordering.rs
Labels: cla-signed

#8254 [storage] delete unimplemented multi_get interface
  execution/executor/src/mock_vm/mock_vm_test.rs
  language/benchmarks/src/move_vm.rs
  language/diem-tools/diem-validator-interface/src/lib.rs
  language/diem-vm/src/data_cache.rs
  language/testing-infra/e2e-tests/src/data_store.rs
  language/tools/resource-viewer/src/lib.rs
  language/tools/vm-genesis/src/genesis_context.rs
  specifications/move_adapter/README.md
  storage/state-view/src/lib.rs
  storage/storage-interface/src/state_view.rs
Labels: cla-signed

#8258 [read/write set analysis] fix crash when updating return value via join
  language/move-prover/bytecode/src/access_path_trie.rs
  language/move-prover/bytecode/tests/read_write_set/update_return.exp
  language/move-prover/bytecode/tests/read_write_set/update_return.move
Labels: cla-signed

#8256 Cherry-pick PR #8123 into release-1.2: [scratchpad] iterative drop
  storage/scratchpad/src/sparse_merkle/mod.rs
  storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
Labels: cla-signed

#8272 [read/writes set analysis] always use weak updates in access domain
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-prover/bytecode/tests/read_write_set/counter.exp
  language/move-prover/bytecode/tests/read_write_set/counter.move
Labels: cla-signed

#8271 [read/write set analysis] Remove Borrow access type
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-prover/bytecode/tests/read_write_set/borrow.exp
  language/move-prover/bytecode/tests/read_write_set/borrow.move
  language/move-prover/bytecode/tests/read_write_set/counter.exp
  language/move-prover/bytecode/tests/read_write_set/functions.exp
  language/move-prover/bytecode/tests/read_write_set/summary.exp
Labels: cla-signed

#8267 [language] remove unused Move-to-Diem dependencies
  Cargo.lock
  language/move-binary-format/Cargo.toml
  language/move-vm/types/Cargo.toml
  x.toml
Labels: cla-signed

#8260 [move-prover] Add a lab to compare current vs next version of Boogie
  common/workspace-hack/Cargo.toml
  language/move-prover/boogie-backend/src/options.rs
  language/move-prover/lab/Cargo.toml
  language/move-prover/lab/README.md
  language/move-prover/lab/data/new-boogie/README.md
  language/move-prover/lab/data/new-boogie/current_boogie.fun_data
  language/move-prover/lab/data/new-boogie/current_boogie.mod_data
  language/move-prover/lab/data/new-boogie/current_boogie.toml
  language/move-prover/lab/data/new-boogie/new_boogie.fun_data
  language/move-prover/lab/data/new-boogie/new_boogie.mod_data
  language/move-prover/lab/data/new-boogie/new_boogie.toml
  language/move-prover/lab/data/new-boogie/notebook.ipynb
  language/move-prover/lab/data/new-boogie/notebook.pdf
  language/move-prover/lab/data/new-boogie/notebook.sh
  language/move-prover/lab/data/new-boogie/run.sh
  language/move-prover/lab/src/benchmark.rs
  language/move-prover/src/cli.rs
Labels: cla-signed

#8259 [read/write set analysis] Don't allow local or return paths in the fo…
  language/move-prover/bytecode/src/access_path.rs
  language/move-prover/bytecode/src/access_path_trie.rs
  language/move-prover/bytecode/src/read_write_set_analysis.rs
  language/move-prover/bytecode/tests/read_write_set/bool_footprint.exp
  language/move-prover/bytecode/tests/read_write_set/bool_footprint.move
  language/move-prover/bytecode/tests/read_write_set/borrow.exp
  language/move-prover/bytecode/tests/read_write_set/counter.exp
  language/move-prover/bytecode/tests/read_write_set/exists.exp
  language/move-prover/bytecode/tests/read_write_set/fields.exp
  language/move-prover/bytecode/tests/read_write_set/footprint.exp
  language/move-prover/bytecode/tests/read_write_set/functions.exp
  language/move-prover/bytecode/tests/read_write_set/summary.exp
  language/move-prover/bytecode/tests/read_write_set/update_return.exp
  language/tools/move-cli/tests/testsuite/diem_read_write_set_smoke/args.exp
  language/tools/move-cli/tests/testsuite/diem_read_write_set_smoke/args.txt
  language/tools/move-cli/tests/testsuite/diem_read_write_set_smoke/src/modules/Dummy.move
  language/tools/move-cli/tests/testsuite/read_write_set/args.exp
Labels: cla-signed

#8241 [json-rpc]: add raw BCS bytes to unknown event data
  json-rpc/API-CHANGELOG.md
  json-rpc/docs/type_event.md
  json-rpc/types/src/proto/jsonrpc.proto
  json-rpc/types/src/views.rs
Labels: cla-signed

#8278 [JSONRPC] Separate data fetching from RPC Server implementation
  json-rpc/src/data.rs
  json-rpc/src/lib.rs
  json-rpc/src/methods.rs
Labels: cla-signed

#8281 [move-prover] Make mono backend default + multiple fixes in prep for removing timeouts.
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/parser/syntax.rs
  language/move-model/src/ast.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/builder/module_builder.rs
  language/move-model/src/builder/spec_builtins.rs
  language/move-model/src/model.rs
  language/move-model/src/ty.rs
  language/move-prover/boogie-backend-exp/src/boogie_helpers.rs
  language/move-prover/boogie-backend-exp/src/boogie_wrapper.rs
  language/move-prover/boogie-backend-exp/src/bytecode_translator.rs
  language/move-prover/boogie-backend-exp/src/lib.rs
  language/move-prover/boogie-backend-exp/src/prelude/native.bpl
  language/move-prover/boogie-backend-exp/src/prelude/prelude.bpl
  language/move-prover/boogie-backend-exp/src/spec_translator.rs
  language/move-prover/boogie-backend/src/boogie_helpers.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/bytecode/src/options.rs
  language/move-prover/lab/data/mono/mono_backend.toml
  language/move-prover/lab/data/mono/poly_backend.toml
  language/move-prover/src/cli.rs
  language/move-prover/src/lib.rs
  language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
  language/move-prover/tests/sources/functional/address_quant.cvc4_exp
  language/move-prover/tests/sources/functional/arithm.cvc4_exp
  language/move-prover/tests/sources/functional/axioms.move
  language/move-prover/tests/sources/functional/cast.cvc4_exp
  language/move-prover/tests/sources/functional/mono.move
  language/move-prover/tests/sources/functional/restrictions.exp
  language/move-prover/tests/sources/functional/restrictions.move
  language/move-prover/tests/sources/functional/type_values.exp
  language/move-prover/tests/sources/functional/type_values.move
  language/move-prover/tests/sources/regression/generic_invariant200518.exp
  language/move-prover/tests/sources/regression/generic_invariant200518.move
  language/move-prover/tests/testsuite.rs
Labels: cla-signed

#8283 [move-prover] replace diem-temppath with tempfile
  Cargo.lock
  language/move-prover/Cargo.toml
  language/move-prover/abigen/Cargo.toml
  language/move-prover/abigen/tests/testsuite.rs
  language/move-prover/bytecode/Cargo.toml
  language/move-prover/docgen/Cargo.toml
  language/move-prover/docgen/tests/testsuite.rs
  language/move-prover/tests/testsuite.rs
  x.toml
Labels: cla-signed

#8286 [gha] split docker build in to a matrix build, should cut time in half.
  .github/workflows/ci-test.yml
  docker/build-common.sh
  docker/client/Dockerfile
  docker/cluster-test/Dockerfile
  docker/diem-build.sh
  docker/docker_republish.sh
  docker/faucet/Dockerfile
  docker/init/Dockerfile
  docker/safety-rules/Dockerfile
  docker/tools/Dockerfile
  docker/validator/Dockerfile
Labels: cla-signed

#8284 [cluster-test] extend newly added StateSyncPerformance test duration
  testsuite/cluster-test/src/experiments/state_sync_performance.rs
Labels: cla-signed

#8287 [diem-vm] Use remapping on WriteSet transactions
  language/diem-vm/src/diem_transaction_executor.rs
  language/e2e-testsuite/src/tests/transaction_builder.rs
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__test_rotate_authentication_key_with_nonce_admin_version_1.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__test_rotate_authentication_key_with_nonce_admin_version_2.exp
Labels: cla-signed

#8294 [move-prover] Introduce choice operator for spec language.
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/parser/syntax.rs
  language/move-model/src/ast.rs
  language/move-model/src/builder/exp_translator.rs
  language/move-model/src/spec_translator.rs
  language/move-model/src/ty.rs
  language/move-model/tests/sources/quantifiers_ok.move
  language/move-prover/boogie-backend-exp/src/boogie_helpers.rs
  language/move-prover/boogie-backend-exp/src/bytecode_translator.rs
  language/move-prover/boogie-backend-exp/src/spec_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/mono_analysis.rs
  language/move-prover/tests/sources/functional/choice.exp
  language/move-prover/tests/sources/functional/choice.move
Labels: cla-signed

#8302 [move-prover] Streamline builtin functions for vectors.
  language/diem-framework/modules/Diem.move
  language/diem-framework/modules/DiemSystem.move
  language/diem-framework/modules/DiemTransactionPublishingOption.move
  language/diem-framework/modules/RegisteredCurrencies.move
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemSystem.md
  language/diem-framework/modules/doc/DiemTransactionPublishingOption.md
  language/diem-framework/modules/doc/RegisteredCurrencies.md
  language/diem-framework/releases/artifacts/current/docs/modules/Diem.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemSystem.md
  language/diem-framework/releases/artifacts/current/docs/modules/DiemTransactionPublishingOption.md
  language/diem-framework/releases/artifacts/current/docs/modules/RegisteredCurrencies.md
  language/move-model/src/ast.rs
  language/move-model/src/builder/spec_builtins.rs
  language/move-model/tests/sources/expressions_ok.move
  language/move-prover/boogie-backend-exp/src/prelude/native.bpl
  language/move-prover/boogie-backend-exp/src/spec_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/tests/usage_analysis/test.exp
  language/move-prover/tests/sources/functional/aborts_if.cvc4_exp
  language/move-prover/tests/sources/functional/aborts_if_with_code.cvc4_exp
  language/move-prover/tests/sources/functional/address_quant.cvc4_exp
  language/move-prover/tests/sources/functional/arithm.cvc4_exp
  language/move-prover/tests/sources/functional/cast.cvc4_exp
  language/move-prover/tests/sources/functional/verify_vector.move
  language/move-prover/tests/sources/regression/trace200527.move
  language/move-stdlib/docs/Option.md
  language/move-stdlib/docs/Vector.md
  language/move-stdlib/modules/Option.move
  language/move-stdlib/modules/Vector.move
Labels: cla-signed

#8295 [move-prover] record the loop header label in stop operation
  language/move-prover/boogie-backend-exp/src/bytecode_translator.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/loop_analysis.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
Labels: cla-signed

#8298 Cherry-pick PR #8287 into release-1.2: [diem-vm] Use remapping on WriteSet transactions
  language/diem-vm/src/diem_transaction_executor.rs
  language/e2e-testsuite/src/tests/transaction_builder.rs
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__test_rotate_authentication_key_with_nonce_admin_version_1.exp
  language/testing-infra/e2e-tests/goldens/language_e2e_testsuite__tests__transaction_builder__test_rotate_authentication_key_with_nonce_admin_version_2.exp
Labels: cla-signed
