Repository diem/diem, pull requests merged in 2021-02, with the labels that each got.

#7443 [cluster-test] revert vault image pulling location
  testsuite/cluster-test/src/cluster_swarm/templates/vault_spec_template.yaml
Labels: cla-signed

#7441 [time-service] Add `Instant` support to time service
  common/time-service/src/lib.rs
  common/time-service/src/mock.rs
  common/time-service/src/real.rs
  secure/key-manager/src/tests.rs
Labels: cla-signed, enhancement

#7437 update diemdb rocksdb property map names
  storage/diemdb/src/lib.rs
Labels: cla-signed

#7440 [gha] re-enable sccache
  .github/actions/build-setup/action.yml
Labels: cla-signed, cla-unsigned

#7429 Remove myself from codeowners
  .github/CODEOWNERS
Labels: cla-signed

#7436 [move][bytecode verifier] Restructure dependency verifications
  language/bytecode-verifier/src/binary_views.rs
  language/bytecode-verifier/src/cyclic_dependencies.rs
  language/bytecode-verifier/src/dependencies.rs
  language/bytecode-verifier/src/lib.rs
  language/compiler/src/main.rs
  language/move-vm/runtime/src/loader.rs
  language/stdlib/compiled/src/lib.rs
  language/stdlib/src/lib.rs
  language/testing-infra/functional-tests/src/evaluator.rs
  language/tools/move-cli/src/main.rs
Labels: cla-signed

#7462 [diemdb_bench] expose rocksdb stats after bench
  Cargo.lock
  storage/diemdb-benchmark/Cargo.toml
  storage/diemdb-benchmark/src/lib.rs
  storage/diemdb/src/lib.rs
  storage/diemdb/src/metrics.rs
  storage/diemdb/src/schema/mod.rs
Labels: cla-signed

#7470 [x] add a custom rule abi -> transaction-builder-generator
  language/transaction-builder/generator/tests/generation.rs
  x.toml
Labels: cla-signed

#7466 [language] filter out file names in compiler error messages
  language/ir-testsuite/tests/move/commands/if_branch_diverges_5.mvir
  language/ir-testsuite/tests/move/commands/if_branch_diverges_6.mvir
  language/ir-testsuite/tests/move/commands/if_branch_diverges_8.mvir
  language/move-lang/functional-tests/tests/move/commands/unpack_top_level.move
  language/testing-infra/functional-tests/src/evaluator.rs
Labels: cla-signed

#7421 [move core types] fix bugs in parse_type_tag
  language/move-core/types/src/identifier.rs
  language/move-core/types/src/parser.rs
Labels: cla-signed

#7502 add RefundMetadata struct for generating types
  testsuite/generate-format/src/diem.rs
  testsuite/generate-format/tests/staged/diem.yaml
  types/src/transaction/metadata.rs
Labels: cla-signed

#7409 [move source language] Fix spec context bugs
  language/move-lang/src/cfgir/liveness/mod.rs
  language/move-lang/src/expansion/translate.rs
  language/move-lang/src/naming/translate.rs
  language/move-lang/src/parser/ast.rs
  language/move-lang/src/parser/syntax.rs
  language/move-lang/tests/move_check/expansion/assign_non_simple_name.exp
  language/move-lang/tests/move_check/expansion/assign_non_simple_name.move
  language/move-lang/tests/move_check/expansion/invalid_local_name.exp
  language/move-lang/tests/move_check/expansion/spec_block_in_spec_context.exp
  language/move-lang/tests/move_check/expansion/spec_block_in_spec_context.move
Labels: bug-fix, cla-signed, language, move-compiler

#7509 [move-prover] Update boogie
  language/move-prover/src/boogie_wrapper.rs
  scripts/dev_setup.sh
Labels: cla-signed

#7540 [move-prover][refactoring] Implementing global invariants + other fixes
  language/move-model/src/ast.rs
  language/move-model/src/exp_rewriter.rs
  language/move-model/src/model.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/clean_and_optimize.rs
  language/move-prover/bytecode/src/data_invariant_instrumentation.rs
  language/move-prover/bytecode/src/debug_instrumentation.rs
  language/move-prover/bytecode/src/eliminate_imm_refs.rs
  language/move-prover/bytecode/src/eliminate_mut_refs.rs
  language/move-prover/bytecode/src/function_data_builder.rs
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/memory_instrumentation.rs
  language/move-prover/bytecode/src/packed_types_analysis.rs
  language/move-prover/bytecode/src/reaching_def_analysis.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/spec_translator.rs
  language/move-prover/bytecode/src/stackless_bytecode.rs
  language/move-prover/bytecode/src/stackless_bytecode_generator.rs
  language/move-prover/bytecode/src/usage_analysis.rs
  language/move-prover/bytecode/tests/data_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/borrow.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/borrow.move
  language/move-prover/bytecode/tests/global_invariant_instrumentation/move.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/move.move
  language/move-prover/bytecode/tests/global_invariant_instrumentation/update.exp
  language/move-prover/bytecode/tests/global_invariant_instrumentation/update.move
  language/move-prover/bytecode/tests/spec_instrumentation/fun_spec.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.exp
  language/move-prover/bytecode/tests/spec_instrumentation/generics.move
  language/move-prover/bytecode/tests/spec_instrumentation/modifies.exp
  language/move-prover/bytecode/tests/spec_instrumentation/opaque_call.exp
  language/move-prover/bytecode/tests/testsuite.rs
  language/move-prover/src/boogie_wrapper.rs
  language/move-prover/src/bytecode_translator.rs
  language/move-prover/src/lib.rs
  language/move-prover/tests/sources/functional/aborts_if_with_code.exp
  language/move-prover/tests/sources/functional/global_invariants.exp
  language/move-prover/tests/sources/functional/global_invariants.move
Labels: cla-signed

#7536 [ir-compiler] parser support for public(script)
  language/compiler/ir-to-bytecode/src/compiler.rs
  language/compiler/ir-to-bytecode/syntax/src/lexer.rs
  language/compiler/ir-to-bytecode/syntax/src/syntax.rs
  language/compiler/src/unit_tests/function_tests.rs
  language/move-ir/types/src/ast.rs
Labels: cla-signed

#7555 [network] Consolidate repeated code in ConnMgr tests
  network/src/connectivity_manager/test.rs
Labels: cla-signed, network

#7533 Update reset-cookie.js
  developers.diem.com/src/theme/ContactForm/reset-cookie.js
Labels: cla-signed

#7576 [gha] sccache publish osx object files.
  .github/actions/build-setup/action.yml
  .github/workflows/osx-sccache.yml
Labels: cla-signed

#7581 [docker] work well with automation
  docker/client/Dockerfile
  docker/tools/Dockerfile
Labels: cla-signed

#7535 [move vm][loader] Execute funciton should verify a missing module and function
  language/diem-vm/src/diem_vm.rs
  language/move-vm/integration-tests/src/tests/bad_entry_point_tests.rs
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/logging.rs
Labels: cla-signed

#7549 [move-prover] Remove the installation scripts in the move-prover directory
  language/move-prover/scripts/README.md
  language/move-prover/scripts/install-boogie.sh
  language/move-prover/scripts/install-cvc4.sh
  language/move-prover/scripts/install-dotnet-centos.sh
  language/move-prover/scripts/install-dotnet-ubuntu.sh
  language/move-prover/scripts/install-dotnet.sh
  language/move-prover/scripts/install-z3-ubuntu.sh
  language/move-prover/scripts/install-z3.sh
Labels: cla-signed, move-prover

#7590 fix doc links
  developers.diem.com/docs/core/run-local-network.md
Labels: cla-signed

#7498 [json-rpc] health-check for checking latest ledger info timestamp
  json-rpc/src/runtime.rs
  json-rpc/src/tests/unit_tests.rs
Labels: cla-signed

#7605 [diem-framework] fix spec bug
  language/diem-framework/modules/DiemTransactionPublishingOption.move
Labels: cla-signed

#7598 [language] move move-vm-test-utils::effects into move-core-types
  language/diem-tools/transaction-replay/src/lib.rs
  language/diem-tools/transaction-replay/src/main.rs
  language/diem-tools/transaction-replay/src/unit_tests/bisection_tests.rs
  language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
  language/move-core/types/src/effects.rs
  language/move-core/types/src/lib.rs
  language/move-vm/integration-tests/src/tests/bad_storage_tests.rs
  language/move-vm/test-utils/src/lib.rs
  language/move-vm/test-utils/src/misc.rs
  language/move-vm/test-utils/src/storage.rs
Labels: cla-signed

#7602 [move-prover] Fix bugs in flow analysis
  language/move-prover/bytecode/src/borrow_analysis.rs
  language/move-prover/bytecode/src/compositional_analysis.rs
  language/move-prover/bytecode/src/dataflow_analysis.rs
  language/move-prover/bytecode/src/livevar_analysis.rs
  language/move-prover/bytecode/src/stackless_control_flow_graph.rs
Labels: cla-signed

#7508 [language/tools] Add a bytecode-to-source explorer for Move
  Cargo.lock
  Cargo.toml
  language/tools/disassembler/src/disassembler.rs
  language/tools/move-bytecode-viewer/Cargo.toml
  language/tools/move-bytecode-viewer/src/bytecode_viewer.rs
  language/tools/move-bytecode-viewer/src/interfaces.rs
  language/tools/move-bytecode-viewer/src/lib.rs
  language/tools/move-bytecode-viewer/src/main.rs
  language/tools/move-bytecode-viewer/src/source_viewer.rs
  language/tools/move-bytecode-viewer/src/tui/mod.rs
  language/tools/move-bytecode-viewer/src/tui/text_builder.rs
  language/tools/move-bytecode-viewer/src/tui/tui_interface.rs
  language/tools/move-bytecode-viewer/src/viewer.rs
Labels: cla-signed

#7584 [vm] Add execute_script_function and verification
  language/bytecode-verifier/src/lib.rs
  language/bytecode-verifier/src/script_signature.rs
  language/bytecode-verifier/src/verifier.rs
  language/move-core/types/src/vm_status.rs
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/runtime.rs
  language/move-vm/runtime/src/session.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
Labels: cla-signed

#7601 [move-prover] Multiset implementation for verifying emits specs
  language/move-prover/src/prelude.bpl
  language/move-prover/src/spec_translator.rs
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/emits.move
Labels: cla-signed, move-prover

#7606 [diemdb_bench] add prune window
  storage/diemdb-benchmark/src/lib.rs
  storage/diemdb-benchmark/src/main.rs
Labels: cla-signed

#7610 mint -> faucet for docker containers
  .github/actions/dockerhub_login/readme.md
  .github/dependabot.yml
  docker/build-aws.sh
  docker/build_push.sh
  docker/compose/README.md
  docker/compose/faucet/.gitignore
  docker/compose/faucet/docker-compose.yaml
  docker/faucet/Dockerfile
  docker/faucet/build.sh
  docker/faucet/buildspec.yaml
Labels: cla-signed

#7595 [State Sync] Use optimistic fetch when making waypoint and verifiable ledger info requests.
  state-sync/src/coordinator.rs
  state-sync/src/error.rs
  state-sync/src/logging.rs
  state-sync/tests/integration_tests.rs
Labels: cla-signed

#7629 [gha] remove canary from daily audit checks.
  .github/workflows/daily.yml
Labels: cla-signed

#7583 [cluster-test] Added new invalid tx suite
  testsuite/cluster-test/src/experiments/compatibility_test.rs
  testsuite/cluster-test/src/experiments/cpu_flamegraph.rs
  testsuite/cluster-test/src/experiments/load_test.rs
  testsuite/cluster-test/src/experiments/performance_benchmark.rs
  testsuite/cluster-test/src/experiments/performance_benchmark_three_region_simulation.rs
  testsuite/cluster-test/src/experiments/reconfiguration_test.rs
  testsuite/cluster-test/src/experiments/recovery_time.rs
  testsuite/cluster-test/src/experiments/twin_validator.rs
  testsuite/cluster-test/src/experiments/versioning_test.rs
  testsuite/cluster-test/src/main.rs
  testsuite/cluster-test/src/suite.rs
  testsuite/cluster-test/src/tx_emitter.rs
Labels: cla-signed, cluster_test

#7578 [move-prover] Add borrow edge info to borrow analysis (v2 experimental version)
  language/move-prover/bytecode/src/borrow_analysis_v2.rs
  language/move-prover/bytecode/src/dataflow_analysis.rs
  language/move-prover/bytecode/src/lib.rs
Labels: cla-signed

#7604 [network] Rename Network Role to Network Type
  config/management/operational/src/network_checker.rs
  config/src/config/mod.rs
  config/src/config/network_config.rs
  config/src/network_id.rs
  diem-node/src/lib.rs
  network/builder/src/builder.rs
  network/builder/src/dummy.rs
  network/simple-onchain-discovery/src/lib.rs
  network/src/counters.rs
  network/src/noise/mod.rs
  network/src/peer_manager/mod.rs
  state-sync/tests/test_harness.rs
Labels: cla-signed, network

#7639 [diem-framework] Move DiemTransactionPublishingOption back to V1
  language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv
Labels: cla-signed

#7645 short-hex-str: use trait to eliminate dep for crypto and move-core-types
  Cargo.lock
  common/short-hex-str/Cargo.toml
  common/short-hex-str/src/lib.rs
  config/Cargo.toml
  config/src/config/network_config.rs
  config/src/config/upstream_config.rs
  config/src/network_id.rs
  consensus/Cargo.toml
  consensus/consensus-types/Cargo.toml
  consensus/consensus-types/src/block_retrieval.rs
  consensus/consensus-types/src/proposal_msg.rs
  consensus/consensus-types/src/vote.rs
  consensus/src/block_storage/block_store.rs
  crypto/crypto/Cargo.toml
  crypto/crypto/src/hash.rs
  language/move-core/types/Cargo.toml
  language/move-core/types/src/account_address.rs
  network/simple-onchain-discovery/Cargo.toml
  network/simple-onchain-discovery/src/lib.rs
  network/src/connectivity_manager/mod.rs
  network/src/counters.rs
  network/src/noise/handshake.rs
  network/src/peer/mod.rs
  network/src/peer_manager/mod.rs
  network/src/protocols/health_checker/mod.rs
  network/src/protocols/network/mod.rs
  network/src/protocols/rpc/mod.rs
  network/src/transport/mod.rs
Labels: cla-signed

#7664 [move prover] fix broken link in prover guide
  language/move-prover/doc/user/prover-guide.md
Labels: cla-signed

#7661 [move-prover] Add illustration of computing global information for a pipeline step
  language/move-prover/bytecode/src/global_invariant_instrumentation.rs
Labels: cla-signed

#7660 [gha/docker] use a docker image per branch
  .github/actions/build-setup/action.yml
  .github/actions/dockerhub_login/action.yml
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test.yml
  docker/ci/github/Dockerfile
  scripts/dev_setup.sh
Labels: cla-signed

#7649 [release] docker base image for each release/master branch and one single large layer so dotnet doesn't fail to install tooling.
  .github/actions/build-setup/action.yml
  .github/actions/dockerhub_login/action.yml
  .github/workflows/ci-publish-base-image.yml
  .github/workflows/ci-test.yml
  docker/ci/github/Dockerfile
  scripts/dev_setup.sh
Labels: cla-signed

#7667 [diem-trace] restore previous behavior of set_diem_trace
  common/trace/src/trace.rs
Labels: cla-signed

#7652 nibble: use trait to eliminate dep for crypto
  Cargo.lock
  crypto/crypto/Cargo.toml
  crypto/crypto/src/hash.rs
  crypto/crypto/src/unit_tests/hash_test.rs
  storage/jellyfish-merkle/src/lib.rs
  storage/jellyfish-merkle/src/restore/mod.rs
Labels: cla-signed, deps-changed, tcb-deps-changed

#7653 Doc updates
  developers.diem.com/docs/core/diem-cli.md
  developers.diem.com/docs/core/life-of-a-transaction.md
  developers.diem.com/docs/merchant/merchant-guide.md
  developers.diem.com/docs/reference/glossary.md
  developers.diem.com/docs/wallet-app/wallet-guide.md
  developers.diem.com/static/img/docs/consensus.svg
  developers.diem.com/static/img/docs/execution.svg
  developers.diem.com/static/img/docs/json-rpc-service.svg
  developers.diem.com/static/img/docs/mempool.svg
  developers.diem.com/static/img/docs/storage.svg
  developers.diem.com/static/img/docs/validator-sequence.svg
  developers.diem.com/static/img/docs/validator.svg
  developers.diem.com/static/img/docs/virtual-machine.svg
Labels: bors-squash

#7676 [sccache] linux builds and a little cleanup
  .github/actions/changes/get_pr_info.sh
  .github/workflows/ci-test.yml
  .github/workflows/ci-update-sccache.yml
Labels: cla-signed

#7701 [diem framework] Fix naming issue in script docs
  language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
  language/diem-framework/transaction_scripts/publish_shared_ed25519_public_key.move
  language/diem-framework/transaction_scripts/rotate_authentication_key.move
  language/diem-framework/transaction_scripts/rotate_authentication_key_with_nonce.move
  language/diem-framework/transaction_scripts/rotate_authentication_key_with_nonce_admin.move
  language/diem-framework/transaction_scripts/rotate_authentication_key_with_recovery_address.move
Labels: cla-signed

#7705 [Move SDK codegen] Bump textwrap from 0.13.2 to 0.13.3
  Cargo.lock
  language/transaction-builder/generator/Cargo.toml
  language/transaction-builder/generator/src/cpp.rs
  language/transaction-builder/generator/src/golang.rs
  language/transaction-builder/generator/src/java.rs
  language/transaction-builder/generator/src/rust.rs
  language/transaction-builder/generator/src/typescript.rs
Labels: deps-changed

#7704 Add printing of x25519 keys to optool
  config/management/operational/src/command.rs
  config/management/operational/src/print.rs
Labels: cla-signed

#7675 [Vault Storage] Make the vault client support configurable timeouts
  config/management/network-address-encryption/src/lib.rs
  config/management/src/config.rs
  config/management/src/secure_backend.rs
  config/src/config/secure_backend_config.rs
  consensus/safety-rules/benches/safety_rules.rs
  consensus/safety-rules/src/tests/vault.rs
  secure/storage/src/tests/vault.rs
  secure/storage/src/vault.rs
  secure/storage/vault/src/dev.rs
  secure/storage/vault/src/lib.rs
  testsuite/cluster-test/src/cluster_builder.rs
Labels: cla-signed

#7703 [gha] switch to machine size, means we should switch the parameters we're looking for to default
  .github/workflows/ci-test.yml
Labels: cla-signed

#7690 [mempool] Remove legacy failover logic
  mempool/src/shared_mempool/peer_manager.rs
  mempool/src/tests/shared_mempool_test.rs
Labels: cla-signed, mempool

#7707 [logging] Add documentation to all structs and macros
  common/logger/src/counters.rs
  common/logger/src/diem_logger.rs
  common/logger/src/event.rs
  common/logger/src/filter.rs
  common/logger/src/kv.rs
  common/logger/src/logger.rs
  common/logger/src/macros.rs
  common/logger/src/metadata.rs
  common/logger/src/sample.rs
  common/logger/src/security.rs
  common/logger/src/struct_log.rs
Labels: cla-signed, documentation, logging

#7725 [diem framework] Generate compiled modules, docs, and scripts
  language/diem-framework/compiled/src/tmp_new_transaction_script_builders.rs
  language/diem-framework/compiled/stdlib/000_Signer.mv
  language/diem-framework/compiled/stdlib/001_Errors.mv
  language/diem-framework/compiled/stdlib/002_CoreAddresses.mv
  language/diem-framework/compiled/stdlib/003_DiemTimestamp.mv
  language/diem-framework/compiled/stdlib/004_Roles.mv
  language/diem-framework/compiled/stdlib/005_Vector.mv
  language/diem-framework/compiled/stdlib/006_BCS.mv
  language/diem-framework/compiled/stdlib/007_Event.mv
  language/diem-framework/compiled/stdlib/008_AccountFreezing.mv
  language/diem-framework/compiled/stdlib/009_AccountLimits.mv
  language/diem-framework/compiled/stdlib/010_Hash.mv
  language/diem-framework/compiled/stdlib/011_Authenticator.mv
  language/diem-framework/compiled/stdlib/012_ChainId.mv
  language/diem-framework/compiled/stdlib/013_FixedPoint32.mv
  language/diem-framework/compiled/stdlib/014_DiemConfig.mv
  language/diem-framework/compiled/stdlib/015_RegisteredCurrencies.mv
  language/diem-framework/compiled/stdlib/016_Diem.mv
  language/diem-framework/compiled/stdlib/017_XUS.mv
  language/diem-framework/compiled/stdlib/018_DesignatedDealer.mv
  language/diem-framework/compiled/stdlib/019_XDX.mv
  language/diem-framework/compiled/stdlib/020_ValidatorOperatorConfig.mv
  language/diem-framework/compiled/stdlib/021_Signature.mv
  language/diem-framework/compiled/stdlib/022_Option.mv
  language/diem-framework/compiled/stdlib/023_ValidatorConfig.mv
  language/diem-framework/compiled/stdlib/024_VASP.mv
  language/diem-framework/compiled/stdlib/025_TransactionFee.mv
  language/diem-framework/compiled/stdlib/026_SlidingNonce.mv
  language/diem-framework/compiled/stdlib/027_DualAttestation.mv
  language/diem-framework/compiled/stdlib/028_DiemTransactionPublishingOption.mv
  language/diem-framework/compiled/stdlib/029_DiemAccount.mv
  language/diem-framework/compiled/stdlib/031_DiemBlock.mv
  language/diem-framework/compiled/stdlib/032_DiemVMConfig.mv
  language/diem-framework/compiled/stdlib/033_DiemVersion.mv
  language/diem-framework/compiled/stdlib/034_Genesis.mv
  language/diem-framework/compiled/stdlib/035_RecoveryAddress.mv
  language/diem-framework/compiled/stdlib/036_SharedEd25519PublicKey.mv
  language/diem-framework/compiled/transaction_scripts/abi/add_validator_and_reconfigure.abi
  language/diem-framework/compiled/transaction_scripts/abi/publish_shared_ed25519_public_key.abi
  language/diem-framework/compiled/transaction_scripts/abi/rotate_authentication_key.abi
  language/diem-framework/compiled/transaction_scripts/abi/rotate_authentication_key_with_nonce.abi
  language/diem-framework/compiled/transaction_scripts/abi/rotate_authentication_key_with_nonce_admin.abi
  language/diem-framework/compiled/transaction_scripts/abi/rotate_authentication_key_with_recovery_address.abi
  language/diem-framework/modules/doc/AccountFreezing.md
  language/diem-framework/modules/doc/Authenticator.md
  language/diem-framework/modules/doc/Diem.md
  language/diem-framework/modules/doc/DiemAccount.md
  language/diem-framework/modules/doc/DiemBlock.md
  language/diem-framework/modules/doc/DiemConfig.md
  language/diem-framework/modules/doc/DiemTimestamp.md
  language/diem-framework/modules/doc/DiemTransactionPublishingOption.md
  language/diem-framework/modules/doc/DualAttestation.md
  language/diem-framework/modules/doc/FixedPoint32.md
  language/diem-framework/modules/doc/RecoveryAddress.md
  language/diem-framework/modules/doc/Roles.md
  language/diem-framework/modules/doc/ValidatorConfig.md
  language/diem-framework/tests/generated_files.rs
Labels: cla-signed

#7722 [move-prover] add weak and strong borrow boogie instructions
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/src/prelude.bpl
Labels: cla-signed

#7724 [x] switch to new versions of guppy and camino
  Cargo.lock
  devtools/x-core/Cargo.toml
  devtools/x-core/src/errors.rs
  devtools/x-core/src/git.rs
  devtools/x-core/src/workspace_subset.rs
  devtools/x-lint/Cargo.toml
  devtools/x-lint/src/file_path.rs
  devtools/x-lint/src/lib.rs
  devtools/x-lint/src/package.rs
  devtools/x-lint/src/runner.rs
  devtools/x/Cargo.toml
  devtools/x/src/lint/allowed_paths.rs
  devtools/x/src/lint/guppy.rs
  devtools/x/src/lint/license.rs
  devtools/x/src/lint/toml.rs
  devtools/x/src/lint/whitespace.rs
  devtools/x/src/lint/workspace_hack.rs
Labels: cla-signed

#7723 [deps][audit] ignore rustsec in hyper 0.13.9
  .github/workflows/daily.yml
Labels: cla-signed

#7669 [cherry-pick-release-1.1][network] Metric if network identity doesn't match onchain
  Cargo.lock
  network/builder/src/builder.rs
  network/simple-onchain-discovery/Cargo.toml
  network/simple-onchain-discovery/src/builder.rs
  network/simple-onchain-discovery/src/lib.rs
Labels: cla-signed, network

#7738 [file-format] make a separate vec of module handles for friend decls
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/bounds_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/duplication_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/generic_ops_tests.rs
  language/bytecode-verifier/bytecode-verifier-tests/src/unit_tests/signature_tests.rs
  language/bytecode-verifier/invalid-mutations/src/bounds.rs
  language/bytecode-verifier/src/check_duplication.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
  language/vm/src/access.rs
  language/vm/src/check_bounds.rs
  language/vm/src/deserializer.rs
  language/vm/src/file_format.rs
  language/vm/src/proptest_types.rs
  language/vm/src/serializer.rs
Labels: cla-signed

#7749 [gha] add ignore list to audit
  .github/workflows/daily.yml
Labels: cla-signed

#7671 [language][vm] make execute_function return values (in serialized format)
  language/diem-tools/writeset-transaction-generator/src/writeset_builder.rs
  language/diem-vm/src/diem_transaction_executor.rs
  language/diem-vm/src/diem_vm.rs
  language/move-vm/integration-tests/src/tests/function_arg_tests.rs
  language/move-vm/integration-tests/src/tests/mod.rs
  language/move-vm/integration-tests/src/tests/return_value_tests.rs
  language/move-vm/runtime/src/interpreter.rs
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/runtime.rs
  language/move-vm/runtime/src/session.rs
  language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs
  language/testing-infra/test-generation/src/lib.rs
  language/tools/vm-genesis/src/lib.rs
Labels: cla-signed

#7746 [move-prover] Enabled loops
  language/diem-framework/modules/Authenticator.move
  language/diem-framework/modules/DiemSystem.move
  language/diem-framework/modules/RecoveryAddress.move
  language/diem-framework/modules/doc/Authenticator.md
  language/diem-framework/modules/doc/DiemSystem.md
  language/diem-framework/modules/doc/RecoveryAddress.md
  language/diem-framework/transaction_scripts/doc/transaction_script_documentation.md
  language/diem-framework/transaction_scripts/rotate_authentication_key_with_recovery_address.move
  language/move-model/src/model.rs
  language/move-prover/boogie-backend/src/bytecode_translator.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/lib.rs
  language/move-prover/bytecode/src/loop_analysis.rs
  language/move-prover/src/pipelines.rs
  language/move-prover/tests/sources/functional/loops.exp
  language/move-prover/tests/sources/functional/loops.move
  language/move-prover/tests/sources/functional/specs_in_fun_ref.exp
  language/move-prover/tests/sources/functional/specs_in_fun_ref.move
  language/move-prover/tests/sources/functional/verify_vector.move
Labels: cla-signed

#7618 mint -> faucet cherry-pick 1.1
  .github/actions/dockerhub_login/readme.md
  .github/dependabot.yml
  docker/build-aws.sh
  docker/build_push.sh
  docker/compose/README.md
  docker/compose/faucet/.gitignore
  docker/compose/faucet/docker-compose.yaml
  docker/faucet/Dockerfile
  docker/faucet/build.sh
  docker/faucet/buildspec.yaml
Labels: cla-signed

#7741 [move-prover] Implemented the spec pragmas "emits_is_partial" and "emits_is_strict"
  language/move-model/src/ast.rs
  language/move-model/src/pragmas.rs
  language/move-prover/boogie-backend/src/spec_translator.rs
  language/move-prover/bytecode/src/spec_instrumentation.rs
  language/move-prover/bytecode/src/spec_translator.rs
  language/move-prover/src/prelude.bpl
  language/move-prover/tests/sources/functional/emits.exp
  language/move-prover/tests/sources/functional/emits.move
Labels: cla-signed, move-prover

#7757 [move cli] print number of bytes written in verbose output
  language/tools/move-cli/src/main.rs
  language/tools/move-cli/tests/testsuite/compile_modules_and_scripts/args.exp
  language/tools/move-cli/tests/testsuite/diem_smoke/args.exp
  language/tools/move-cli/tests/testsuite/diem_smoke/args.txt
  language/tools/move-cli/tests/testsuite/events_emit_view/args.exp
  language/tools/move-cli/tests/testsuite/module_publish_view/args.exp
  language/tools/move-cli/tests/testsuite/module_run_view/args.exp
  language/tools/move-cli/tests/testsuite/republish/args.exp
  language/tools/move-cli/tests/testsuite/republish_cyclic/args.exp
  language/tools/move-cli/tests/testsuite/republish_cyclic_transitive/args.exp
Labels: cla-signed

#7750 [bytecode-verifier] add compatibility checking for friend visibility
  language/move-vm/runtime/src/loader.rs
  language/move-vm/runtime/src/runtime.rs
  language/vm/src/compatibility.rs
  language/vm/src/normalized.rs
Labels: cla-signed
